### PR TITLE
Modified progressive / progressive disease post-mortem tumor descript…

### PR DESCRIPTION
**Pull request by sjspielman**
Address Issue #1217 by tweaking hex code for tumor descriptors progressive and progressive post-mortem. Colors are now different shades (hues? tints? ....) of the same "dark teal".

#### What GitHub issue does your pull request address?

#1217

#### Which areas should receive a particularly close look?

Agree with color choices?

### Results

None

### CODE REVIEW

**Review by jaclyn-taroni — COMMENTED** [review]
Hm... I just realized these are in a different format than all the other colors. Because if you put a hex code in back ticks it'll render on GitHub comments (`#c7e9c0`) and this wasn't working!

**Comment by sjspielman** [comment]
`#05403AFF`

**Comment by jaclyn-taroni** [comment]
Yep, I mean the trailing `FF`. I don't know why it's there and #1161 (where it was added) does not explicitly say. My tired brain knew these were too long, but not that they were too long in the exact same way. That is to say that I expect them to be pretty easy to standardize, then.

**Comment by sjspielman** [comment]
OK, I vote merge this in first, and then I can open a separate issue/PR to track removing the `FF` opacity digits where appropriate?

**Comment by jaclyn-taroni** [comment]
I don't really see a reason to wait, but okay.

**Comment by sjspielman** [comment]
> I don't really see a reason to wait to make those updates, but okay.

Miscellaneous conflict avoidance, but I'll get everything in now.

**Comment by jaclyn-taroni** [comment]
I'm factoring in that it takes a bunch of time to run CI - so two minor PRs is double the waiting time!

**Review by jaclyn-taroni — APPROVED** [review]

**Pull request merged**
