### PR TITLE
chromosomal-instability cdf function updates

### PR DESCRIPTION
**Pull request by cansavvy**
#### What scientific question is your analysis addressing?
No new scientific question, just a re-vamp of some plots that can use a recently functionalize CDF plotter that has been merged (#612). 

#### What was your approach?
I used the function I recently separated into its own script and now made this 02b-plot-chr-instability-by-histology.Rmd CDF plots use this function instead of having their own separate CDF function in the `chr-break-plot.R` script. 

#### What GitHub issue does your pull request address?
[This issue](https://github.com/cansavvy/openpbta-notebook-concept/issues/6)

#### Which areas should receive a particularly close look?
- Is there anything missing with this update? 
- Outdated comments? 
- Note that the color palette needs to be updated but that will be in a different PR.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes. 

### Results
Results are not actually different just how we got the plots is. 

***No changes were made to the below items. 
#### Reproducibility Checklist
- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist
- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
These CDF plots are not the same. 

* SV breaks is empty: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=3e9d2ec#diff-3e9d2ec9cb00ce64531c1ad8f191458f
* ATRT, for example, is missing from the intersection plot even though I suspect that it meets the minimum samples threshold: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=f0bbbb2#diff-f0bbbb2f537c67ca9388a0ed5e13aaca

I thought it might be an issue with the underlying density files needing to be rerun, but I got:

```
$ bash run_breakpoint_analysis.sh
run_breakpoint_analysis.sh: line 19: scratch/cnv_surveyed_wgs.bed: No such file or directory
```

This is following the directions in the README - I think it's a paths issue which I will address in an upcoming commit. If, however, I need to run something _upstream_ before I can generated `cnv_surveyed_wgs.bed`, we should get that added to the documentation as well. Also wondering if it's a good time to address some of the TODOs in the shell script (may be beyond the scope of this pull request).

**Comment by jaclyn-taroni** [comment]
I ran into trouble debugging this due to the instructions in the README, which is a very easy fix that I will address, and the design pattern here:  https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/796fcf2eb32e970fb2995cd593746a40265cfb98/analyses/chromosomal-instability/00-setup-breakpoint-data.R#L104

I am going to alter this module to remove the pattern where an Rscript accepts the path relative to the root directory and instead accepts a "generic" path that should be relative to the current working directory when you run it.

I will then make it such that the bash script has a working directory of where it is saved:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/796fcf2eb32e970fb2995cd593746a40265cfb98/analyses/interaction-plots/01-create-interaction-plots.sh#L14

That ensures that the shell script will run correctly no matter where it is called from.

**Comment by jaclyn-taroni** [comment]
Rerunning all steps did not "fix" the plots. I am going to leave it there and let @cansavvy take another look.

**Comment by cansavvy** [comment]
- [SV breaks plot is fixed](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=3e9d2ec#diff-3e9d2ec9cb00ce64531c1ad8f191458f)
- [ATRT plot is here and looks fine](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=a51bf31#diff-a51bf313b3e96e31d2ed4867dac8633b)
- The TODOs here are either not applicable at this time [because we don't have WXS data](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7e000418b106e34040325d2fbd642f63080966c8/analyses/chromosomal-instability/run_breakpoint_analysis.sh#L23), or cannot really be addressed until [the unsurveyed cnv regions of the genome gets added to the data release ](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7e000418b106e34040325d2fbd642f63080966c8/analyses/chromosomal-instability/run_breakpoint_analysis.sh#L16) . Speaking of which, is that to happen in #601 v16?
This all being said, I edited the comments around those steps in the bash script so it is more clear why they are still TODOs that have not been acted upon. 

To be addressed but not in this particular PR: 
- Color palette needs to be applied (But need #622 to be merged first). 
- Documentation around relative file paths needs to be made more clear (This is tracked here: #632)

Is there anything else that is still at large for this PR, @jaclyn-taroni ? I believe your comments have been addressed (or are being tracked elsewhere) and this runs fine for me and CircleCI right now.

**Comment by jaclyn-taroni** [comment]
Two quick comments:

> * ATRT, for example, is missing from the intersection plot even though I suspect that it meets the minimum samples threshold: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=f0bbbb2#diff-f0bbbb2f537c67ca9388a0ed5e13aaca

The plot linked there is `analyses/chromosomal-instability/plots/intersection_breaks_cdf_plot.png` not `analyses/chromosomal-instability/plots/tumor-type/ATRT_breaks.png` which you link to above. It still looks like ATRT is not in `intersection_breaks_cdf_plot.png` in the most recent update to me. I wanted to verify that this is expected.

> Documentation around relative file paths needs to be made more clear (This is tracked here: #632)

I removed this pattern in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/commits/323db4b110d0660c34b619f45897bd2c033a358f, but perhaps I missed something.

**Comment by cansavvy** [comment]
> The plot linked there is `analyses/chromosomal-instability/plots/intersection_breaks_cdf_plot.png` not `analyses/chromosomal-instability/plots/tumor-type/ATRT_breaks.png` which you link to above. 

I may have accidentally linked to the wrong plot. 

>It still looks like ATRT is not in `intersection_breaks_cdf_plot.png` in the most recent update to me. I wanted to verify that this is expected.

ATRT is there its just not the first one listed because it is order by median and previously the median was not being calculated with `na.rm` so this has changed the order of the histologies in the plots: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=f0bbbb2#diff-f0bbbb2f537c67ca9388a0ed5e13aaca

**Comment by cansavvy** [comment]
> ATRT is there its just not the first one listed because it is order by median and previously the median was not being calculated with `na.rm` so this has changed the order of the histologies in the plots: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/625/files?short_path=f0bbbb2#diff-f0bbbb2f537c67ca9388a0ed5e13aaca

Actually, I think the change is the reverse of what I said here, the `na.rm = TRUE` was there before but is not now. I'm going to add back `na.rm = TRUE` because I think that is more what we want.

**Comment by jaclyn-taroni** [comment]
👍 I thought it was alphabetical in both so that is my confusion

**Comment by cansavvy** [comment]
> 👍 I thought it was alphabetical in both so that is my confusion

It's good we got to the bottom of it. I didn't realize the `na.rm = TRUE` got lost in the shuffle.

**Comment by jaclyn-taroni** [comment]
The system is working!

**Comment by cansavvy** [comment]
Okay, @jaclyn-taroni , feel free to take another look to see if everything has been addressed.

**Pull request merged**
