### PR TITLE
Compiled figure4

### PR DESCRIPTION
**Pull request by sjspielman**
This PR compiles Figure 4 as a PNG and PDF, and includes some code changes (namely sizing and `useDingbats = FALSE`) that are needed to support compilation.

Note the top row panels A-C are a bit tricky to center, because panel A is smaller than B and C are, but I don't think this looks too jarring.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
My only comment is that the overall width can probably be decreased because there is a bit of whitespace in every row which can be reduced.

**Comment by sjspielman** [comment]
@jharenza I was able to drop the width by just shy of an inch. How does this look?

**Review by jharenza — APPROVED** [review]
👍

**Comment by sjspielman** [comment]
Code changes do not require CI; merging before checks complete.

**Pull request merged**
