### PR TITLE
Compiled Figure 5 for V22

### LINKED ISSUE #1490: Re-compile Figure 5
We'll need to re-compile updated panels into an overall Figure 5.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #1490 
This PR adds compiled Figure 5 for V22. No other changes!

### CODE REVIEW

**Comment by sjspielman** [comment]
An updated commit is coming shortly...one wonky y-axis label in panel D!

**Comment by sjspielman** [comment]
I'm looking over how these figures have rendered within vs. outside the app. Entirely different appearance! Many of the points are not retaining their shapes upon export. Going to have to take a step back with this compilation.

**Comment by sjspielman** [comment]
This is now ready for review. I had to use Illustrator for this one.

**Review by jharenza — APPROVED** [review]
This one looks good to me and no changes needed based on past manuscript text.

**Comment by sjspielman** [comment]
No code is added with this PR, so we can merge before checks.

**Pull request merged**
