### PR TITLE
PBTA Histologies: Update collapse-rnaseq to v18 (1 of N)

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Rna summary modules needed for subtyping need to be updated because of the 8 new stranded files. In this PR re-run collapse-rnaseeq 

| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`collapse-rnaseq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/collapse-rnaseq) | adding 8 samples #749 and used in subtyping  | Collapses RSEM FPKM matrices such that gene symbols are de-duplicated. | `results/pbta-gene-expression-rsem-fpkm-collapsed.polya.rds` (included in data download; too large for tracking via GitHub) <br> `results/pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` (included in data download; too large for tracking via GitHub)

#### What GitHub issue does your pull request address?
#861 

#### Which areas should receive a particularly close look?
There are no major changes here just re-ran the module since it's used in subtyping, other modules that need to be rerun for subtyping are in #861 

#### What types of results are included (e.g., table, figure)?
RDS 

#### What is your summary of the results?
pbta-gene-expression-rsem-fpkm-collapsed_table.stranded.rds  has 8 new samples in total there are 978 stranded files now.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Hi @kgaonkar6! Since the resulting collapsed matrices are too big for GitHub tracking, perhaps for me to review those, you can write out your command with options, add the resulting numbers of BS_IDs in each polyA and stranded RDS file, and show that they match the new histologies file?

cc @jaclyn-taroni

**Comment by jharenza** [comment]
NOTE: Once these PRs have completed a full histology file and it is uploaded to S3, then #857 should be merged first, as these PRs use the V18 files and `pbta-histologies-base.tsv' @jaclyn-taroni

**Review by cansavvy — APPROVED** [review]
This seems reasonable to me and like this PR does what is described.

**Comment by kgaonkar6** [comment]
thanks for review @cansavvy @jharenza , latest commit was from a re-run with updated base histology(minor change to Normal sample rows) file which doesn't change any results files.

**Review by jharenza — APPROVED** [review]

**Comment by cansavvy** [comment]
This re-run with pbta-histologies-base.tsv causes problems downstream with `molecular-subtyping-EPN`. I think it has to do with the new samples? 
```
Error: Unknown columns `BS_07ANYSYQ`, `BS_0BXY0F9N`, `BS_0QYS36NR`, `BS_0WQJP6ZG`, `BS_0XEG6SNV` and ...
```
@kgaonkar6 can you explain what you mean by `adding 8 samples #749 and used in subtyping`? Because now that I've done the subtyping for v18 we know what these samples are. (But we didn't previously).

**Comment by kgaonkar6** [comment]
Hmm collapse-rnaseq-base is not dependent on any broad/short histology so I don't think the issue with molecular-subtyping-EPN will be fixed with a re-run of this module. I'll anyways check the collapse file generated here for the samples that error out for EPN

**Pull request merged**
