### PR TITLE
Add python3 tk to docker

### LINKED ISSUE #1361: Add dependency: `python-tk`
The `tp53_nf1_score` module relies heavily on Python libraries for running the classifier. In addition, this module makes some plots using `matplotlib`.

It turns out this module can _only run_ if it's not being run in interactive mode, e.g. from the rocker IDE, because of a `matplotlib` dependency.. It runs perfectly fine directly from the command line with `docker run`, but not from within a server session. The problem occurs when importing `matplotlib` - 

```
import matplotlib.pyplot as plt

Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

According to [the internet](https://askubuntu.com/questions/815874/importerror-no-named-tkinter-please-install-the-python3-tk-package), this can be pretty easily addressed with a **ubuntu** installation of `python3-tk`. 

Therefore, for the `tp53_nf1_score` module to run without errors in an interactive session, we will need to add a line installing `python3-tk` to the Dockerfile.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #1361 

This PR addresses errors that occur when running `tp53_nf1_score` from an interactive RStudio Server session due to graphics engines. Specific changes include:

+ Adding the `python3-tk` dependency to Docker
+ Removing `matplotlib` import from a script that doesn't do any plotting
+ Adding import lines to python scripts that DO do plotting so it will use a different plotting engine

### CODE REVIEW

**Comment by sjspielman** [comment]
Quick note - we do not want to merge this PR before checks are complete since want to confirm the Docker change does not affect _other_ analyses.

**Comment by sjspielman** [comment]
This failed due to a timeout, but the relevant module passed CI.

**Comment by jaclyn-taroni** [comment]
I believe updating `requirements.txt` is required as well.

**Comment by jaclyn-taroni** [comment]
Ah, okay, you're right. I assumed based on the name.

**Comment by sjspielman** [comment]
Yeah, it's _very_ misleading..

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻

**Comment by sjspielman** [comment]
Relevant module has passed CI before the timeout occurred, so this can be merged.

**Pull request merged**
