### PR TITLE
PBTA Histologies v19 Part 5 of N: Update tsne

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Re-running transcriptomic-dimension-reduction to get tsne/umap score for v19

| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`transcriptomic-dimension-reduction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/transcriptomic-dimension-reduction)| BS_JXF8A2A6 is removed as per #862 | Dimension reduction and visualization of RNA-seq data  | N/A

#### What was your approach?
Just re-run as part of the scripts/run-for-subtyping.sh in kgaonkar6:v19-release in #1028
Then create a new branch for module specific review:
git checkout v19-release analyses/transcriptomic-dimension-reduction/

#### What GitHub issue does your pull request address?
#867 

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
tables

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
BS_JXF8A2A6 is stranded sample so you will see updates *stranded*  where we expect changes along with tsne/umap coordinates.  Since files have some histology columns like CNS_region update and some broad_histology and tumor_descriptors could have also changed.

In general I have seen that each run causes very very small numeric changes in the coordinates resulting in diff files.


plots updated:
```
 analyses/transcriptomic-dimension-reduction/plots/kallisto_polyA_log_broad_histology.pdf  
 analyses/transcriptomic-dimension-reduction/plots/kallisto_polyA_none_broad_histology.pdf 
 analyses/transcriptomic-dimension-reduction/plots/kallisto_stranded_log_broad_histology.pdf  
 analyses/transcriptomic-dimension-reduction/plots/kallisto_stranded_none_broad_histology.pdf
 analyses/transcriptomic-dimension-reduction/plots/rsem_polyA_log_broad_histology.pdf 
 analyses/transcriptomic-dimension-reduction/plots/rsem_polyA_none_broad_histology.pdf 
 analyses/transcriptomic-dimension-reduction/plots/rsem_stranded_log_broad_histology.pdf
 analyses/transcriptomic-dimension-reduction/plots/rsem_stranded_none_broad_histology.pdf 
```

files updated:
```
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_log_pca_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_log_tsne_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_log_umap_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_none_pca_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_none_tsne_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_polyA_none_umap_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_log_pca_scores_aligned.tsv   
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_log_tsne_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_log_umap_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_none_pca_scores_aligned.tsv    
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_none_tsne_scores_aligned.tsv 
 analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_none_umap_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_log_pca_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_log_tsne_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_log_umap_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_none_pca_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_none_tsne_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_polyA_none_umap_scores_aligned.tsv 
 analyses/transcriptomic-dimension-reduction/results/rsem_stranded_log_pca_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_stranded_log_tsne_scores_aligned.tsv 
 analyses/transcriptomic-dimension-reduction/results/rsem_stranded_log_umap_scores_aligned.tsv  
 analyses/transcriptomic-dimension-reduction/results/rsem_stranded_none_pca_scores_aligned.tsv
 analyses/transcriptomic-dimension-reduction/results/rsem_stranded_none_tsne_scores_aligned.tsv    
```

**Review by jashapiro — COMMENTED** [review]
> In general I have seen that each run causes very very small numeric changes in the coordinates resulting in diff files.

In my quick perusal, it looks like most of the changes in the polyA samples are in tsne plots; the UMAP and PCA plots seem to be more stable. As expected, the stranded files change much more.

However, it looks like the results tables here need to be updated with the latest histologies files: they still contain `PNOC003` rather than `PNOC`

**Comment by kgaonkar6** [comment]
Did you mean the results files in analyses/transcriptomic-dimension-reduction/results?  I checked some files and they seem to have the updated histology info like https://github.com/kgaonkar6/OpenPBTA-analysis/blob/update-tsne/analyses/transcriptomic-dimension-reduction/results/rsem_polyA_log_tsne_scores_aligned.tsv has the `PNOC` cohort name and updated seq_center names etc.

**Comment by jashapiro** [comment]
> Did you mean the results files in analyses/transcriptomic-dimension-reduction/results? I checked some files and they seem to have the updated histology info like https://github.com/kgaonkar6/OpenPBTA-analysis/blob/update-tsne/analyses/transcriptomic-dimension-reduction/results/rsem_polyA_log_tsne_scores_aligned.tsv has the `PNOC` cohort name and updated seq_center names etc.

Oh, you are right! I must have been looking at the wrong diff somehow.

**Review by jashapiro — APPROVED** [review]
Changes seem to be as expected, even if tsne isn't stable for some reason.

**Pull request merged**
