### PR TITLE
adding annoFuse for kinase status

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Adding annoFuse to docker to get pfam domain annotation and kinase domain status

#### What was your approach?
Added 
RUN R -e "BiocManager::install(c('EnsDb.Hsapiens.v86', 'ensembldb'))"
RUN R -e "remotes::install_github('d3b-center/annoFuse', dependencies = TRUE)"

#### What GitHub issue does your pull request address?
#812 

#### Which areas should receive a particularly close look?
Adding annoFuse will make adding kinase domain status 1 line command by running something similar to the example in the function here: 
https://github.com/d3b-center/annoFuse/blob/master/R/fusion_driver.R

So do we want to use this function from annoFuse or replicate the internal functions *fusion_driver()* and *get_Pfam_domain()* in OpenPBTA? 
Asking mainly for 
 - some aggregating steps will need to be updated to keep `LeftBreakpoint` and `RightBreakpoint` columns so domain retention status can be added with respect to where the breakpoints are within the genes
 - consistency, since the other scripts in fusion_filtering are base functions and not functions called from annoFuse?

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
No

#### What types of results are included (e.g., table, figure)?

NA

#### What is your summary of the results?

NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
>So do we want to use this function from annoFuse or replicate the internal functions fusion_driver() and get_Pfam_domain() in OpenPBTA?

I think we can use from annoFuse directly.

**Comment by jashapiro** [comment]
Please follow the instructions in https://github.com/AlexsLemonade/OpenPBTA-analysis#docker-image for adding files to the docker image. In particular, note that `BiocManager::install()` should not be used. Please use `install_bioc.R` instead. Also, any packages installed from github must include a specific commit id. 

If `annoFuse` requires a more recent version of `tidyverse` than we currently have in the image, this will require special accommodations in order to not break other modules.

**Comment by kgaonkar6** [comment]
Thanks for the link @jashapiro 

Yeah it seems annoFuse imports tidyr::one_of() which was only added to tidyr1.02 or later but we have tidyr0.8.3 in openpbat docker so I was trying to update the version but without luck. 

Do you think we can update the tidyr to 1.0.2 or I was gonna try changing the `@importFrom` to dplyr::one_of() in a branch of annoFuse to check if that works in the docker.

**Comment by jashapiro** [comment]
> Yeah it seems annoFuse imports tidyr::one_of() which was only added to tidyr1.02 or later but we have tidyr0.8.3 in openpbat docker so I was trying to update the version but without luck.
> 
> Do you think we can update the tidyr to 1.0.2 or I was gonna try changing the `@importFrom` to dplyr::one_of() in a branch of annoFuse to check if that works in the docker.

Unfortunately, updating `tidyr` is a pretty big project given the other dependencies across the project and the major changes that came with 1.0. We might be able to come up with a solution, but it may not be straightforward. If you do need `one_of` then using the `dplyr` version is probably the best solution for now, and that can be installed pretty easily by pointing `install_github()` to a commit on that branch.

**Comment by kgaonkar6** [comment]
Importing one_of from dplyr seems to have worked! Thanks!

**Review by jashapiro — APPROVED** [review]
Looks good! Looking forward to seeing the analysis this enables!

**Pull request merged**
