### PR TITLE
re-create 5D forest plot

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
With #1356 in, we had to re-create 5D forest plot

#### What was your approach?
rerun script

#### What GitHub issue does your pull request address?
NA

#### Which areas should receive a particularly close look?
na

#### Is there anything that you want to discuss further?
no

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
new FP

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by sjspielman** [comment]
This PR only has the figure. Code?

**Comment by sjspielman** [comment]
The code here should also be updated, not just rerun. For example, see the `term_order` and `term_labels` variables in the script - Unknown/Unavailable should be removed from there. 

In addition, I want to note that in this updated model, Macrophage 1 now has an estimate, but it's lower bound and upper bounds are -Inf and Inf respectively. I think we should continue to exclude this point from the figure, but describe in figure caption that it's coefficient is `-8.951217e+04` with infinite CIs and P=0.99.

**Comment by jharenza** [comment]
Ahhh thanks for catching this. Will update as soon as I can!

**Comment by jharenza** [comment]
@sjspielman code/plot is updated

**Review by sjspielman — COMMENTED** [review]
One more change here and then I think we're good to go. The _comments_ on lines 35-38 should be updated, since Macrophage M1 estimates/CIs have changed from the original model. We want to indicate in these comments it is NOT significant but has infinite CIs.

**Comment by jharenza** [comment]
> One more change here and then I think we're good to go. The _comments_ on lines 35-38 should be updated, since Macrophage M1 estimates/CIs have changed from the original model. We want to indicate in these comments it is NOT significant but has infinite CIs.

whoops, updated

**Review by sjspielman — APPROVED** [review]
👍

**Comment by sjspielman** [comment]
This code does not run through CI so we can merge before checks complete.

**Pull request merged**
