### PR TITLE
Create subset files for V18 Circle CI

### LINKED ISSUE #871: v18 CI files
We need to update the CI files to reflect the v18 release. The v18 release makes the following changes (quoting from #857): 

> - changes:
>   - Add RNA independent specimen lists from [#795](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/795) and [#797](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/797)
>   - Update DNA independent specimen lists per comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691526896)
>   - Add LGAT fusion summary file from [#808](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/808) and [#830](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/830)
>   - Update fusion files per comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691529675)
> - Add kinase domain and reciprocal information to pbta-fusion-putative-oncogenic.tsv per [#812](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/812) and [#816](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/816) and [#821](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/821)
>   - Add 8 rRNA-depleted, total stranded RNA-Seq for tumors which previously had polyA sequencing performed: BS_FXJY0MNH, BS_KABQQA0T, BS_D7XRFE0R, BS_SHJA4MR0, BS_HE0WJRW6, BS_8QB4S4VA, BS_FN07P04C, BS_SB12W1XT per [#749](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/749)
>   - Update pbta-histologies.tsv:
>     - Add new RNA samples above
>     - Pull latest clinical data
>     - Add extent of tumor resection per [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issue-688364970)
>     - Rerun molecular subtyping modules to date

#### _Known_ changes required to `create-subset-files`

- We need copy the `pbta-histologies-base.tsv` file in the shell script like we do for `pbta-histologies.tsv` 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/83d3e1ca17ba5bfa420d1194a5ee19e96ec93bf8/analyses/create-subset-files/create_subset_files.sh#L56

- Update the release

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/83d3e1ca17ba5bfa420d1194a5ee19e96ec93bf8/analyses/create-subset-files/create_subset_files.sh#L10

#### Potential "gotchas"

I think some of the v18 file additions, which usually break things, should be covered by the existing code. I'm including this section just in case there's anything unexpected.

>   - Add RNA independent specimen lists from [#795](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/795) and [#797](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/79

These files are named `independent-specimens.rnaseq.primary-plus-polya.tsv` and `independent-specimens.rnaseq.primary-plus-stranded.tsv` according to #857. That _should be_ covered by:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/83d3e1ca17ba5bfa420d1194a5ee19e96ec93bf8/analyses/create-subset-files/create_subset_files.sh#L66

>   - Add LGAT fusion summary file from [#808](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/808) and [#830](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/830)

This file is called `fusion_summary_lgat_foi.tsv` according to #857. That should be covered by:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/83d3e1ca17ba5bfa420d1194a5ee19e96ec93bf8/analyses/create-subset-files/create_subset_files.sh#L85

#### Next steps 

These steps are adapted from #670 

1. Start AWS instance with 128 GB RAM
2. Clone OpenPBTA-analysis
3. Create a new branch off of `jharenza:v18-files` called `v18-ci`
4. Update `analyses/create-subset-files/create_subset_files.sh` as outlined above ☝️ 
5. Run `bash analyses/create-subset-files/create_subset_files.sh` 
6. Commit the biospecimen RDS file to `v18-ci` branch. 
7. Zip up the subset files in `data/testing/release-v18-20201123/` to `testing_v18.zip`
8. Download `testing_v18.zip` 
9. File a pull request from `v18-ci`

### PR DESCRIPTION
**Pull request by cansavvy**
### Purpose/implementation Section

This PR is for creating the subset files for circle CI testing for v18 release. 
Closes #871 

#### What was your approach?

This branch was created from `jharenza:v18-files`. 
I made the changes to `analyses/create-subset-files/create_subset_files.sh` as described by #871 in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/873/commits/9510df5d366d9fc4093a8c71042c60552d4733a3 : 
- Update RELEASE to v18 
- Add copy over step for pbta-histologies-base.tsv file. 

With those changes I ran this on AWS as described by #871 and then in f14ca50 I added `biospecimen_ids_for_subset.RDS` file to this branch. 

I have testing_v18.zip it seems reasonable (82 files, md5sum shows 80 files because no release notes or md5sum). I can upload whenever we are ready. 

#### What GitHub issue does your pull request address?
Closes #871

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Hmmm, the instructions on https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/871 are out of date for what we need _now_ which is to:

1. Start merging the early `PBTA histologies` PRs to facilitate review of the later PRs.
2. Review the later PRs
2. Merge the release #857 

Which is to say that we don't want to add the changes from the #857 branch _yet_.  Do we want to cherry pick https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/873/commits/9510df5d366d9fc4093a8c71042c60552d4733a3 onto a new branch?

**Comment by jaclyn-taroni** [comment]
Make that https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/9510df5d366d9fc4093a8c71042c60552d4733a3 and https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/873/commits/f14ca5003376a85f45e2d3421ae9f3a9f6506015.

**Comment by cansavvy** [comment]
> Which is to say that we don't want to add the changes from the #857 branch _yet_. Do we want to cherry pick [9510df5](https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/9510df5d366d9fc4093a8c71042c60552d4733a3) onto a new branch?

Ah. Right. Forgot about that aspect. Yes so we'd like a PR with only the changes here and not the v18 changes from `jharenza:v18-files`?

**Comment by jaclyn-taroni** [comment]
> Yes so we'd like a PR with only the changes here and not the v18 changes from `jharenza:v18-files`?

Yep!

> And how should this relate to the order of me adding the actual subset files to S3?

I think we were holding off on merging the `PBTA Histologies` PRs so that they can be tested and the "depth" of that stack of stacked PRs can make it a little tricky to do a thorough review. I believe we also sometimes have testing files on CI "early" or ahead of the release itself so we can find and remedy any breaking changes. Which is to say - let's get them on S3 and see what happens!

**Comment by cansavvy** [comment]
v18 subset files have been uploaded to S3 bucket.

**Comment by cansavvy** [comment]
This reverting the unwanted commits was not as cleaned as I hoped. Going to close this PR and only copy over the actual wanted changes from 9510df5 and f14ca50 as mentioned previously. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/873#issuecomment-749105004

**Comment by cansavvy** [comment]
Closing this PR in favor of #888

**Pull request closed without merging**
