### PR TITLE
Remove R script/notebook package installs (Part 1 of N) 

### PR DESCRIPTION
**Pull request by cansavvy**
#### What was your approach?
I'm removing R package installations in the scripts in accordance with #690 
I'm keeping track of the PRs I file for that issue here and going through the modules alphabetically. 

This PR is me having gone through `chromosomal-instability` - `focal-cn-file-preparation`, here are the changes in this PR: 

- cnv-chrom-plot: In `gistic_plot.Rmd` got rid of:  `install.packages("BiocManager")` and `BiocManager::install("ggbio")` and refreshed `gistic_plot.Rmd` only. 
- cnv-comparison: is deprecated, so I didn't get rid of the install.packages there
- focal-cn-file-preparation: Got rid of series of installs in `04-prepare-cn-file.R`, re-ran ` bash run-prepare-cn.sh`.

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Everything look okay? 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes, but the results shouldn't really be different. 

#### Reproducibility Checklist
No changes are needed here. 

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

### CODE REVIEW

**Comment by cansavvy** [comment]
> These changes look just about ready to merge 👍
> 
> I am just concerned about what appears to be the removal of a plot: `focal-cn-file-preparation/plots/consensus_seg_cn_autosomes_stranded_stacked_plot.png`
> Any idea why this may be the case here?

The script seemed to finish without any errors, but I'm also not super familiar with this code. This may be something I could use your help investigating, @cbethell . What notebook/script creates that plot?

**Comment by cbethell** [comment]
> > These changes look just about ready to merge 👍
> > I am just concerned about what appears to be the removal of a plot: `focal-cn-file-preparation/plots/consensus_seg_cn_autosomes_stranded_stacked_plot.png`
> > Any idea why this may be the case here?
> 
> The script seemed to finish without any errors, but I'm also not super familiar with this code. This may be something I could use your help investigating, @cbethell . What notebook/script creates that plot?

The script that creates that plot is the `rna-expression-validation.R` script of the `focal-cn-file-preparation` module. It's strange to me that it is just that one plot that is missing. I can look into it on your branch to see if I could figure out what's going on there.

**Comment by cansavvy** [comment]
@cbethell , I'm looking [at this line](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/8ac1772145833d015483a4ceb5249c77c9bd68a6/analyses/focal-cn-file-preparation/run-prepare-cn.sh#L65): 

```
--filename_lead "consensus_seg_annotated_cn"_${chromosome_type}_${strategy}
```
And don't think this file `consensus_seg_cn_autosomes_stranded_stacked_plot.png`  which doesn't have the `annotated` bit in there, would be saved. Is there somewhere else that you expect this file would be saved from? 

As of right now, my best guess is that that file is from an older edition where before you added the `annotated` part in the name. Let me know if there's somewhere else I should be looking.

**Comment by cansavvy** [comment]
My other guess is maybe you had previously included the consensus file in this next loop: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/8ac1772145833d015483a4ceb5249c77c9bd68a6/analyses/focal-cn-file-preparation/run-prepare-cn.sh#L92

Let me know if either of my guesses ring a bell, or if not, where in the code you would expect that file should be saved from.

**Comment by cansavvy** [comment]
I don't think either of my theories regarding `consensus_seg_annotated_cn_autosomes_stranded_stacked_plot.png` are corrrect. I think it should have been saved. My best guess now is that a step got skipped because of memory intensive requirements. I think my plan is to run this on a bigger boat.

**Comment by cansavvy** [comment]
@cbethell I re-ran the `run-prepare-cn.sh` script on AWS. It looks like those files were created this time, but can you take another look to make sure everything else with `focal-cn-file-preparation` looks as you would expect?

**Pull request merged**
