### PR TITLE
Copy panel 5C to figures/pdfs

### PR DESCRIPTION
**Pull request by sjspielman**
This PR copies figure panel 5C from its analysis module (`immune-deconv`) to the `figures/pdfs/fig5/panels/` directory. This figure was originally made as pub-ready, so we simply copy instead of reproducing the figure in `figures/scripts/`.

Note that when https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1286 is completed, `generate_figures.sh` script will be further updated to run the `immune-deconv` module before the line that copies the panel over.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
To me, it doesn't make sense to not add the `immune-deconv` step at this time. I know we expect that this script will change, but skipping that for now decreases the likelihood that it makes it in later.

**Comment by sjspielman** [comment]
@jaclyn-taroni Updated!

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻  thanks for the update!

**Comment by jaclyn-taroni** [comment]
This is not run in CI, so I'm going to go ahead and merge it w/o it!

**Pull request merged**
