### PR TITLE
Figure S1 as PNG and PDF

### PR DESCRIPTION
**Pull request by sjspielman**
This PR adds the compiled Figure S1 as both PDF and PNG. (This figure is a single panel, so there is not much actual "compilation.")

Reviewers: Please check if these files are in the expected place and have the expected name. We may also want to update `figures/README.md` to clearly state naming scheme for these panels, which can be added in this PR during review.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
Do we want to have both png and pdf, or just pdf, since we are using pdf for nearly everything else now? If both, they probably should be in the same folder?

**Comment by jaclyn-taroni** [comment]
We need PNG for things to render in the Manubot version and PDF for submission. Putting compiled figures in `figures/pngs` and `figures/pdfs` is documented in `figures/README.md`. If we're going to do a reorganization, it's probably best to do it in the end after we've finished the compiled figures.

**Comment by jharenza** [comment]
> We need PNG for things to render in the Manubot version and PDF for submission. Putting compiled figures in `figures/pngs` and `figures/pdfs` is documented in `figures/README.md`. If we're going to do a reorganization, it's probably best to do it in the end after we've finished the compiled figures.

oh gotcha, this is because it is the full figure! So then, should `Figure_S1.png` go in `figures/pngs/` with a new folder called `supp`, etc and the current PNGs in that folder be deleted and folders added per figure such as with the pdf directory? having one in a folder but one not was what threw me off.

**Comment by jaclyn-taroni** [comment]
These additions are in different places than I would expect. I would expect:

`figures/pdfs/supp/figs1/Figure_S1.png` -> `figures/pngs/figureS1.png`
`figures/pdfs/supp/figs1/panels/Figure_S1.pdf` -> `figures/pdfs/supp/figs1/figureS1.pdf`

The file name style (i.e., `Figure_S1.*` vs. `figureS1.*`) is not well-defined in the docs, but this is closer to what I have in #1305 🤷🏻

**Comment by sjspielman** [comment]
> These additions are in different places than I would expect

Ah, I see I misread something in the README! Will update.

**Comment by sjspielman** [comment]
@jaclyn-taroni this has been updated. I also made a small change to the README about convention for supplementary compiled PDFs.

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻

**Comment by jaclyn-taroni** [comment]
Addition of non-programmatically generated figure and docs, merging without CI

**Pull request merged**
