### PR TITLE
PBTA Histologies : re-run with consistent broad/short histogolies

### PR DESCRIPTION
**Pull request by kgaonkar6**
### Purpose/implementation Section

Re-run all steps as described in [run-for-subtyping.sh] https://github.com/kgaonkar6/OpenPBTA-analysis/blob/re-run-newRNA-subtyping-steps-v18/scripts/run-for-subtyping.sh with updated base histology.

#### What scientific question is your analysis addressing?
A previous release of pbta-histologies.tsv had the following inconsistencies:
2 values for broad_histology of embryonal tumors: `Embryonal Tumor` and `Embryonal tumor` 
2 values for broad_histology of ependymal tumors: `Ependymal Tumor` and `Ependymal tumor`
2 values for short_histology of ependymal tumors: `EPN` and `Ependymoma`
"Benign Tumors" and "Other" had some additional suffix like -cyst,-other etc that needed to be changed to `Benign tumor` and `Other`

which needed to be fixed for downstream plotting scripts.

#### What was your approach?

1) pbta-histologies-base.tsv was updated to always have sentence case terms such as `Embryonal tumor`  and `Ependymal tumor` as well as `Ependymoma` was updated inplace of `EPN`.

2) I had to update the broad_histology and short_histology for embryonal tumors and  ependymal tumors in molecular-subtype-pathology since they had `Tumor` but needed to be updated to `tumor`. 

3) `pathology_dx and pathology_free_text_diagnosis to broad_histology for subtyping module - rules_without_subtype_WIP.tsv` has updates to make "Other" sample broad_histology and short_histology consistent without additional suffix like - cyst/-other.

The key commands used to re-run the steps for generating `pbta-histologies.tsv` are:
```
# check out 608e905efb3a7dcdfa7b82c5497f270b8d7f8d2a commit 
# this commit incorporates all changes required for  v18 release specifically
git checkout 608e905efb3a7dcdfa7b82c5497f270b8d7f8d2a

# checkout a new branch to re-run all steps for v18
git checkout -b "re-run-newRNA-subtyping-steps-v18"

# run scritpts/run-for-subtyping.sh
docker exec -ti <container_name> bash -c "cd /home/rstudio/OpenPBTA/scripts && bash run-for-subtyping.sh"
```

#### What GitHub issue does your pull request address?
#891 
#889 

#### Which areas should receive a particularly close look?
- Checks for `OPENPBTA_BASE_SUBTYPING` term used to give global value to run modules for subtyping. I had previously used `BASE_SUBTYPING` which I saw was still in tsne module in this re-run so maybe be good to have more eyes on this. 

- Since last time these steps were run #860 has gone in to help with adding missing WGS in Ependymoma samples, it indirectly also fixes the inconsistency issue since they now match to all other Ependymoma samples being subtyped. 

#### Is there anything that you want to discuss further?
tsne results have changed but I am not 100% sure it came up because of me missing to update `BASE_SUBTYPING` to `OPENPBTA_BASE_SUBTYPING` or from #716?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
pbta-histologies.tsv
pbta-histologies-base.tsv

These files need to be updated to s3 release and CI when review OK

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Just wanted to add some other formatting updates to `pbta-histologies-base.tsv` here:

fixed capitalization standardization:
- Langerhans Cell histiocytosis to Langerhans cell histiocytosis

updated:
- Histiocytic tumors to Histiocytic tumor

**Review by jaclyn-taroni — APPROVED** [review]
Based on your description and what I see here, this LGTM! I want @jharenza to approve as well, though. I'm trying to think about what we should do to document that LGAT will be essentially out of step when this is merged because we'll need to make sure it is up to date with `master`.

**Review by jharenza — APPROVED** [review]
This looks good now, except will you change 
```
Updated by manual review of WHO diagnosis
````
to 
```
Updated by manual curation of pathology_free_text_diagnosis
```

I will approve so once that is done, we can upload to s3.

**Comment by jharenza** [comment]
> I'm trying to think about what we should do to document that LGAT will be essentially out of step when this is merged because we'll need to make sure it is up to date with `master`.

I think this should be OK (LGAT WIP) because the final subtypes file isn't in master yet - just step 1 of 3.

**Comment by kgaonkar6** [comment]
Thanks for the review @jaclyn-taroni @jharenza ! I've updated the `Notes` from your comment.

**Comment by kgaonkar6** [comment]
also just uploaded pbta-histologies.tsv and pbta-histologies-base.tsv to s3  s3://kf-openaccess-us-east-1-prd-pbta/data/release-v18-20201123/. 

#857 md5sums check all OK

**Comment by jaclyn-taroni** [comment]
@cansavvy - we're going to need to update the CI files again ☝️  (note I think that can wait until tomorrow morning).

**Comment by cansavvy** [comment]
> also just uploaded pbta-histologies.tsv and pbta-histologies-base.tsv to s3 s3://kf-openaccess-us-east-1-prd-pbta/data/release-v18-20201123/.
> 
> #857 md5sums check all OK

I've tried a few times to download using the download bash script on v18-files branch and deleting the whole v18 data folder but each time it fails on the mend-qc files: 
```
pbta-mend-qc-manifest.tsv: FAILED
pbta-mend-qc-results.tar.gz: FAILED
```

Is there something different I should be doing this time?

**Comment by kgaonkar6** [comment]
oh I think that must be because I updated the md5sum.txt file incorrectly, using an older version of the md5sum.txt file which didn't include the mendqc file update from  #890. 

Sorry, can you update the mendqc md5sums again?

**Comment by jaclyn-taroni** [comment]
> Sorry, can you update the mendqc md5sums again?

I think this was a question for @jharenza but not sure. 

Based on my understanding, we are able to obtain the files but the checksum step doesn't pass. I'm wary of generating the md5sum file on our side because the step that is failing is the main way we make sure the data download wasn't truncated, etc.

**Comment by jharenza** [comment]
@kgaonkar6 the md5sums for the new mend-qc files are:
```
1ef04eb6a6809fc4cf94fa1f06fabd23  pbta-mend-qc-manifest.tsv
25345fd22d1fb9ea71e68a7ea78166ad  pbta-mend-qc-results.tar.gz
```

will you update this on s3 please?

**Comment by kgaonkar6** [comment]
Sorry for the confusion, I've updated the md5sum.txt on s3 for the latest mendqc files. And download_script.sh checks are OK for me.

**Comment by jaclyn-taroni** [comment]
Thanks @jharenza and @kgaonkar6 - @cansavvy we should be ready to get the CI files set up!

**Comment by cansavvy** [comment]
`pbta-histologies.tsv` and `pbta-histologies-base.tsv` and `md5sum.txt`- the CI version have been updated in the S3 bucket for CI testing.

**Comment by jaclyn-taroni** [comment]
Added a comment here https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/867#issuecomment-758814057 to keep track of [my earlier concern](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/896#pullrequestreview-565755401)

> I'm trying to think about what we should do to document that LGAT will be essentially out of step when this is merged because we'll need to make sure it is up to date with `master`. 

I will now merge `master` into this branch and, when CI runs, that will be a way to confirm that all is well with the CI files.

**Pull request merged**
