### PR TITLE
update Figure 3D to separate out "Other" cancer groups

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
This panel was previously updated to use `cancer_group_display` and when I did that, I overlooked the fact that this figure had been plotting the other cancer groups individually.

#### What was your approach?
- Update the code to use `cancer_group` when `cancer_group_display == "Other"`. 
- Update palette code accordingly

#### What GitHub issue does your pull request address?
NA

#### Which areas should receive a particularly close look?
code updates

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by sjspielman — COMMENTED** [review]
Thanks for looking into this! In comparing this panel with the previous one, I'm getting different _total_ amounts for the "Other" groups. Previously, we had 9/60 for "Other". In this PR, I see 8/38 when pooling the "Other" groupings. Do you also see this discrepancy?

**Comment by jharenza** [comment]
> Thanks for looking into this! In comparing this panel with the previous one, I'm getting different _total_ amounts for the "Other" groups. Previously, we had 9/60 for "Other". In this PR, I see 8/38 when pooling the "Other" groupings. Do you also see this discrepancy?

totally missed this comment - will check!

**Comment by jharenza** [comment]
> > Thanks for looking into this! In comparing this panel with the previous one, I'm getting different _total_ amounts for the "Other" groups. Previously, we had 9/60 for "Other". In this PR, I see 8/38 when pooling the "Other" groupings. Do you also see this discrepancy?
> 
> totally missed this comment - will check!

@sjspielman I think what is going on is that because we only plot groups with N>= 3 samples, we lose some of the 60 in the plot. I will create a table which shows the new groups and Ns so we can see the diffs.

**Comment by jharenza** [comment]
@sjspielman - added some calculations in this and indeed, we had lost 22 samples due to N <3. Ready for re-review!

**Review by sjspielman — APPROVED** [review]
Great, this all makes sense!

**Comment by sjspielman** [comment]
This code does not run through CI, so can merge before checks complete.

**Pull request merged**
