### PR TITLE
add fpkm matrix; add note about ControlFreeC CN

### PR DESCRIPTION
**Pull request by jharenza**

### CODE REVIEW

**Comment by cgreene** [comment]
Is the RSEM file in the md5sums? I didn't see it there. It looks like the methods section doesn't include kallisto at all in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/25

**Comment by jharenza** [comment]
> Is the RSEM file in the md5sums? I didn't see it there. It looks like the methods section doesn't include kallisto at all in [AlexsLemonade/OpenPBTA-manuscript#25](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/25)

I did not see it either, but will ask @yuankunzhu to add it today. Kallisto should be in methods - will have to add.

**Comment by cgreene** [comment]
I am about to be traveling. Adding @jaclyn-taroni as a reviewer in my place.

**Comment by cgreene** [comment]
With the improvements in #45, we just need to get the filename included in the md5sum.txt file and the downloader will fix itself. Can you open a new PR to add the caveats on the ControlFreeC to the updated text?

**Comment by jharenza** [comment]
> With the improvements in #45, we just need to get the filename included in the md5sum.txt file and the downloader will fix itself. Can you open a new PR to add the caveats on the ControlFreeC to the updated text?

got it - I saw your edits just now, will do.

**Pull request closed without merging**
