### PR TITLE
Find breaking changes from v18 (part 2)

### PR DESCRIPTION
**Pull request by cansavvy**
### Purpose/implementation Section
This is the second attempt (#874 was the first) at finding breaking changes now with the metadata updates made and discussed on #875. 

I'm commenting out the broken modules and putting notes of what I find here. 

### Running list of errors: 
Checked off errors means they have been addressed. 
As I find the errors in Circle CI testing, I'm posting them here and will comment with more info as I investigate. 

- [ ] Molecular subtyping for Ependymoma needs to be adjusted because of new biospecimens added. See [CI run here](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4687/workflows/7d69e741-a37a-4506-8960-5450eb87751f/jobs/5259). 
Related issue #881 
Edit: This has been re-run and addressed in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/876/commits/8f33c4a20eebaf89402003b91440b68f521fa4aa

```
Traceback (most recent call last):
  File "02_ependymoma_generate_all_data.py", line 180, in <module>
    EPN_notebook = fill_df_with_fpkm_zscores(EPN_notebook, fpkm_df, gene)
```
- [ ] Interaction plot does not run. I did some investigating. Issue #880 Only 1 LGAT sample shows up and that's because there's more `NA`s  for `integrated_diagnosis` than there were in v17. See comment here: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/875#issuecomment-749705328
```
Error in combn(genes, m = 2) : n < m
Calls: coocurrence -> t -> combn
Execution halted
```

- [ ] Chromosomal instability breakpoints has a color palette issue because `Melanocytoma` is not in the color palette. Related Issue #882  Should be a straightforward fix. 
```
Quitting from lines 262-278 (02a-plot-chr-instability-heatmaps.Rmd) 
Error in col2rgb(colors, alpha = TRUE) : 
  invalid color name 'Melanocytoma'
Calls: <Anonymous> ... do.call -> <Anonymous> -> ColorMapping -> t -> col2rgb
```

- [ ] Comparative RNA-seq doesn't work. Related Issue: #883 Probably something also about samples lining up. 
```
^@^@Loading sample matrix ../../data/pbta-gene-expression-rsem-tpm.polya.rds
Traceback (most recent call last):
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 231, in <module>
    main()
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 218, in main
    verbose=args.verbose)
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 74, in filter_samples
    qc_status = get_qc_status(mend_results_path, mend_manifest_path)
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 43, in get_qc_status
    filename_map = { i.name : extract_sample_qc_status(mend_tgz.extractfile(i), i.name) for i in qc_files }
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 43, in <dictcomp>
    filename_map = { i.name : extract_sample_qc_status(mend_tgz.extractfile(i), i.name) for i in qc_files }
  File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 30, in extract_sample_qc_status
    status = qc_file_handle.readlines()[1][-5:-1].decode("utf-8")
IndexError: list index out of range
```

- [ ] Oncoprint plotting needs a color palette update as well: Related Issue #882 
```
Error in names(short_histology_col_key) <- short_histologies : 
  'names' attribute [55] must be the same length as the vector [38]
Execution halted
```

- I've preemptively commented out CN Status heatmap, assuming it will fail for color palette reasons as well. Related Issue #882 

- [ ] RNA-seq composition has this error: Related Issue #883 
```
Quitting from lines 56-80 (rna-seq-composition.Rmd) 
Error in .f(.x[[i]], ...) : object 'uniqMappedNonDupeReadCount' not found
Calls: <Anonymous> ... <Anonymous> -> vars_rename_eval -> map_if -> map -> .f
```

- D3b TMB code is not working: Related Issue: #884 
```
^@^@sys:1: DtypeWarning: Columns (85,87,88,90) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "code/01_calculate_tmb.py", line 212, in <module>
    str(0), str(bed_length),  str(0)])+"\n")
NameError: name 'bed_length' is not defined
```

### CODE REVIEW

**Comment by kgaonkar6** [comment]
I just wanted to mention here, that I did look into the CI_run error for Ependymoma subtyping and I think  we would need to rerun subsetting EPN samples.

Which is skipped in CI because we have OPENPBTA_SUBSET=0 in .circleci/config.yml

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/466c61570ffb6e72428412e7a971594707c8a256/analyses/molecular-subtyping-EPN/run-molecular-subtyping-EPN.sh#L38-L41


BS_EVCAC3NH was not Ependymoma in previous releases but is in v18.

```
# v17  pbta-histologies.tsv which I believe was used for epn_subset collapsed file
> old_hist[which(old_hist$Kids_First_Biospecimen_ID=="BS_EVCAC3NH"),"pathology_diagnosis"]
# A tibble: 1 x 1
  pathology_diagnosis                          
  <chr>                                        
1 Dysembryoplastic neuroepithelial tumor (DNET)

# v18 pbta-histologies.tsv
> new_hist[which(new_hist$Kids_First_Biospecimen_ID=="BS_EVCAC3NH"),"pathology_diagnosis"]
# A tibble: 1 x 1
  pathology_diagnosis
  <chr>              
1 Ependymoma         
```

**Comment by cansavvy** [comment]
> I think we would need to rerun subsetting EPN samples.

Okay. After I find all the breaks, I'll try this on this branch and see that resolves it.

**Comment by kgaonkar6** [comment]
For interaction plots CI error, I believe the the disease (integrated_diagnosis) term used for plotting short_histology LGAT samples was "Low-grade astrocytic tumor" in v17 since majority terms were that. But in v18 LGAT are further sub-subtyped according to BRAF alterations. Maybe that update might help pass CI ?

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/466c61570ffb6e72428412e7a971594707c8a256/analyses/interaction-plots/01-create-interaction-plots.sh#L41-L48
```
#v17 
> old_hist$integrated_diagnosis[old_hist$short_histology=="LGAT"] %>% table()
.
         Low-grade astrocytic tumor Subependymal Giant Cell Astrocytoma 
                                499                                   6 
# v18 
> new_hist$integrated_diagnosis[new_hist$short_histology=="LGAT"] %>% table()
.
                 Low-grade astrocytic tumor   Low-grade glioma/astrocytoma, BRAF fusion 
                                          2                                         242 
   Low-grade glioma/astrocytoma, BRAF V600E Low-grade glioma/astrocytoma, BRAF wildtype 
                                         50                                         197 
```

**Comment by cansavvy** [comment]
> But in v18 LGAT are further sub-subtyped according to BRAF alterations. Maybe that update might help pass CI ?
> 
> ```
> #v17 
> > old_hist$integrated_diagnosis[old_hist$short_histology=="LGAT"] %>% table()
> .
>          Low-grade astrocytic tumor Subependymal Giant Cell Astrocytoma 
>                                 499                                   6 
> # v18 
> > new_hist$integrated_diagnosis[new_hist$short_histology=="LGAT"] %>% table()
> .
>                  Low-grade astrocytic tumor   Low-grade glioma/astrocytoma, BRAF fusion 
>                                           2                                         242 
>    Low-grade glioma/astrocytoma, BRAF V600E Low-grade glioma/astrocytoma, BRAF wildtype 
>                                          50                                         197 
> ```

Yes this would do it. We'll have to adjust to make the filter do a string search that would incoporate these subdivisions. Unless we think there's a better way to collect the LGAT samples (some other variable perhaps?).

**Comment by jashapiro** [comment]
> Yes this would do it. We'll have to adjust to make the filter do a string search that would incoporate these subdivisions. Unless we think there's a better way to collect the LGAT samples (some other variable perhaps?).

I think that code will need to be updated to take advantage of the subtyping, or revert to broad histology.

**Comment by jharenza** [comment]
> For interaction plots CI error, I believe the the disease (integrated_diagnosis) term used for plotting short_histology LGAT samples was "Low-grade astrocytic tumor" in v17 since majority terms were that. But in v18 LGAT are further sub-subtyped according to BRAF alterations. Maybe that update might help pass CI ?
> 
> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/466c61570ffb6e72428412e7a971594707c8a256/analyses/interaction-plots/01-create-interaction-plots.sh#L41-L48
> 
> ```
> #v17 
> > old_hist$integrated_diagnosis[old_hist$short_histology=="LGAT"] %>% table()
> .
>          Low-grade astrocytic tumor Subependymal Giant Cell Astrocytoma 
>                                 499                                   6 
> # v18 
> > new_hist$integrated_diagnosis[new_hist$short_histology=="LGAT"] %>% table()
> .
>                  Low-grade astrocytic tumor   Low-grade glioma/astrocytoma, BRAF fusion 
>                                           2                                         242 
>    Low-grade glioma/astrocytoma, BRAF V600E Low-grade glioma/astrocytoma, BRAF wildtype 
>                                          50                                         197 
> ```

Also keep in mind that LGAT subtyping will be changing after this release, so I think I will agree with @jashapiro using broad histology until those PRs (#848, #847, #845) get merged.

**Comment by cansavvy** [comment]
> Also keep in mind that LGAT subtyping will be changing after this release, so I think I will agree with @jashapiro using broad histology until those PRs (#848, #847, #845) get merged.

Okay. Will switch interaction plots to use `broad_histology` then.

**Review by jashapiro — APPROVED** [review]
Assuming issues have been filed for each of the commented out analyses (I believe they have) this seems good to go.

**Comment by jashapiro** [comment]
I made a change to the OpenPBTA docker image that I don’t think should break anything in use but I wanted to just have somebody sign off… there was a problem with a Jupyter dependency, but it was for some of the QT/widget modules that we don’t use (they are mostly for interactive work). 

I think the `jupyter` installation, while it claims to be versioned, does not specify versions for its underlying components, and was somehow creating a conflict (new this year, as it build fine a couple weeks ago!).   To avoid the problem, I substituted a fairly current version of the `notebook` python module, which should support everything we use, but hopefully specifies its dependencies better, or at least more compatibly. 

CI passes, so I think this should be good to merge, but I would like somebody to have a look at my Docker changes just to be sure before merging.

**Review by jaclyn-taroni — APPROVED** [review]
Docker change LGTM!

**Pull request merged**
