### PR TITLE
update subset files for lgat fusions

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
Update create subset files module code to include fusions within LGAT fusion summary #830 

#### What was your approach?
Add `FGFR1--TACC1, MYB--QKI, BRAF` to putative-oncogenic.tsv selection criteria for subsetting testing files. 
- _FGFR1--TACC1_ is the only fusion in the 5' kinase in-frame dataframe which is rbound at the end
- _MYB--QKI_ comes up in the non-kinase fusion dataframes
- _BRAF_ fusions are in each of the remaining dataframes

#### What GitHub issue does your pull request address?
#834 

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes and tested

#### What types of results are included (e.g., table, figure)?
NA

#### What is your summary of the results?
NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Okay, I've uploaded a new version of the fusion file. We'll see if what's currently running on #830 works.

**Review by jaclyn-taroni — APPROVED** [review]
Code looks fine! We'll see if it sufficiently accounts for the changes in #830 before we merge this.

**Comment by jharenza** [comment]
> Code looks fine! We'll see if it sufficiently accounts for the changes in #830 before we merge this.

I just pushed rerun for the circleCI tests because I think you updated this while the last tests were running and the data download step was probably pulling the older file, so the check did not pass.

**Comment by jharenza** [comment]
@jaclyn-taroni I just downloaded the testing file and the reason this is erroring out is that the additional columns added in #821 are not present. Can you subset from [this file](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/results/pbta-fusion-putative-oncogenic.tsv)? Otherwise, it looks like the fusions I added are present with this script.

**Comment by jaclyn-taroni** [comment]
Talked about this offline, but wanted to record this here - since the notebook in #830 was using the file in `analysis/fusion_filtering`, the problem was not the file in CI but that fusion filtering came before the fusion summary module in #830. Moving the fusion summary module up in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/830/commits/9ffa3da0186d237f1da7b75181868b449df4399f resolved the issue.

**Comment by jaclyn-taroni** [comment]
This code to generate the CI files is not run in CI, so I'm going to go ahead and merge this.

**Pull request merged**
