### PR TITLE
PBTA Histologies v19 Part 3 of N: Update fusion filtering 

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`fusion_filtering`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) | BS_JXF8A2A6 is removed as per #862  | Standardizes, filters, and prioritizes fusion calls  | `results/pbta-fusion-putative-oncogenic.tsv`(included in data download) <br> `results/pbta-fusion-recurrent-fusion-byhistology.tsv` (included in data download) <br> `results/pbta-fusion-recurrent-fusion-bysample.tsv` (included in data download) 

#### What was your approach?
Just re-run as part of the scripts/run-for-subtyping.sh in kgaonkar6:v19-release in #1028
Then create a new branch for module specific review:
git checkout v19-release analyses/fusion_filtering/

#### What GitHub issue does your pull request address?
#867 

#### Which areas should receive a particularly close look?
Not fully sure why the samples are missing from `pbta-fusion-recurrent-fusion-bysample.tsv `

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jashapiro — COMMENTED** [review]
There seem to be a lot of lines removed here in the recurrent lists, more than I would have expected. I initially thought this might be due to sample changes in the independent samples analysis, but then I would have expected some additions, not just removals. 

`FilteredFusion.tsv` only seems to remove `BS_JXF8A2A6` as expected, but other files have more samples removed, which I was not expecting. 

Is it possible that there was a mismatch between the data files & sample list for some part of this module, making it so the changes in  https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1040 might not be fully reflected here?

One other note: `pbta-fusion-putative-oncogenic.tsv` has more changes than I would have expected. Spot checking it looks like most of this is ordering changes, but I didn't do a careful analysis.

**Comment by kgaonkar6** [comment]
I was not able to figure out the issue before while filing the PR but I think I figured out:

https://github.com/kgaonkar6/OpenPBTA-analysis/blob/5dba0062ae333a74ff6ee14bea6086fc21703f79/analyses/fusion_filtering/06-recurrent-fusions-per-histology.R#L40-L43

This code needs to be change cohort name from `PNOC003` to `PNOC`, That changed the 15 samples other than BS_JXF8A2A6.

**Comment by kgaonkar6** [comment]
Updating the code to use PNOC instead of PNOC003 fixed those unwanted changes.

**Review by jashapiro — APPROVED** [review]
This looks good now, but I'm still a bit confused by the large number of changes in `pbta-fusion-putative-oncogenic.tsv` As I said, I don't think it is a problem; it seems like there might be just an ordering change there.

If you want to fix it, it looks like just adding an `arrange(Sample, FusionName)` at line 211 of 
`05-QC_putative_onco_fusion_dustribution.Rmd` would do the trick to prevent this from coming up again in the future, and make it easier to distinguish any changes that do occur after this point.  (You might want to fix the typo in the file name while you are at it. 😉 )

**Comment by jashapiro** [comment]
@kgaonkar6 Thanks for the updates in efe4de5... you will want to make sure to delete the old files as well, so GH recognizes it as a move rather than new files.

**Comment by kgaonkar6** [comment]
Ah yes removed those old files!

**Pull request merged**
