### PR TITLE
HistologicalAnalysis_update

### PR DESCRIPTION
**Pull request by NNoureen**
### Purpose/implementation Section
The purpose here is to modify the visualization of telomerase activity scores across different tumor histologies.

#### What was your approach?
We used our newly developed method EXTEND (Expression based Telomerase ENzymatic activity Detection) for telomerase activities. We have visualized the scores using boxplots by adding jitter points to it.

#### What GitHub issue does your pull request address?
Issue # 148 (Quantify telomerase activity across pediatric brain tumors)

#### Which areas should receive a particularly close look?
We would like the reviewers to provide us comments on our modified visualization approach for script -04.
#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES
#### What types of results are included (e.g., table, figure)?
Plot is built using script -04 to visualize the telomerase scores.
#### What is your summary of the results?
Distribution of telomerase activities across different pediatric brain tumor histologies using boxplots.

#### Documentation Checklist

This analysis module has a `README` and it is up to date.
This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
The analytical code is documented.

### CODE REVIEW

**Comment by sjspielman** [comment]
Hi @NNoureen, 

It seems like the only code associated with this PR is adding `geom_jitter`, so the description of the PR you have entered is above-and-beyond the coding you have performed here. You may want to *edit* your filled in PR template to more precisely reflect what these specific changes entail. Or, is the goal here to solicit additional ideas for how to analyze the data that you will then incorporate into code this PR?

At a minimum, I suggest adding an `alpha` parameter to the `geom_jitter()` so that the plots are easier to see. I do generally like the idea of having jitter overlay boxplots, in particular since it helps to see the different sample sizes in each histology group.

You might also want to space out the plots a little more, since x-axis of top plot really looks like a title for the bottom plot. You can do this with the `scale` argument in `cowplot::plot_grid` (make each plot a bit smaller), and/or you can use the `labels = 'auto'` argument in `cowplot::plot_grid`  to label plots as a/b and avoid this confusion.

-Stephanie

**Comment by NNoureen** [comment]
Yeah the only change here is the addition of jitter. So I will update the plot as suggested and will update the PR and its description as suggested.

**Comment by NNoureen** [comment]
Hi Dr. Stephanie
I have done the changes in the plot and PR description of script -04 as per your suggestion.

**Comment by NNoureen** [comment]
Hi Dr. Stephanie 
The initial checks have been failed, although I haven't done any major changes in the PR. I have just updated the jitter and adjusted the plot area using cowplot library. Does the code need some other changes?

**Comment by sjspielman** [comment]
Hi @NNoureen , 

There is a broader issue we are just uncovering with the Docker build that is causing this to fail. Your code does not appear to be causing issues. Once we are able to track down and fully address the underlying cause, I will come back to this and approve - we just need to make sure builds are possible in the first place.

Best, 
Stephanie

**Comment by NNoureen** [comment]
Sure. Thanks

**Comment by NNoureen** [comment]
Hi Dr. Stephanie
Can I submit my next script (05) now or do I need to wait?

**Comment by sjspielman** [comment]
@NNoureen yes, go for it!! Please open a separate pull request with the template filled out, and we'll get right to reviewing it.

**Comment by NNoureen** [comment]
Sure. Thanks

**Pull request merged**
