### PR TITLE
PBTA Histologies v19 Part 2 of N: Update independent samples

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Rna summary modules needed for subtyping need to be updated because BS_JXF8A2A6 is removed as per #862. In this PR  I'm re-running the independent-samples module.

| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`independent-samples`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/independent-samples) | BS_JXF8A2A6 is removed as per #862 | Generates independent specimen lists for WGS/WXS samples updated in  #795 and #797 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691526896)| `results/independent-specimens.wgs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-stranded.tsv`(included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-polya.tsv` (included in data download)

#### What was your approach?
Just re-run as part of the scripts/run-for-subtyping.sh in kgaonkar6:v19-release in #1028
Then create a new branch for module specific review:
git checkout v19-release analyses/independent-samples/

#### What GitHub issue does your pull request address?
#867 

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
tables

#### What is your summary of the results?
Some rna-seq sample selections have changed I believe because of the random selection 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jashapiro — APPROVED** [review]
LGTM! I guess the html was out of date or something about the files changed to make it parse more logical columns...

**Comment by kgaonkar6** [comment]
`broad_composition` was added back , `kf_visibility` is a new field in the v19 pbta-histologies-base.tsv file. 
However, `parent_aliquot_id` might not be needed let me check with Jo Lynne.

**Comment by kgaonkar6** [comment]
Cols are updated in pbta-histologies-base.tsv to not include the new cols broad_composition and kf_visibility. The parent_aliquat_id is infact in v18 so it was accurately captured back.

**Review by jashapiro — APPROVED** [review]
LGTM

**Pull request merged**
