### PR TITLE
Data release/v16

### PR DESCRIPTION
**Pull request by yuankunzhu**
#### What scientific question is your analysis addressing?
v16 data release

#### What was your approach?
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/601#issuecomment-601798842

#### What GitHub issue does your pull request address?
#601 

#### Which areas should receive a particularly close look?
new TCGA MAF was called based on the new BED files, some of those are using the intersect_bed files, @cansavvy can check the details on the `pbta-tcga-manifest.tsv` to see if the BED files and Sample ID mapping making sense or not.

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [x] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?

### CODE REVIEW

**Comment by cansavvy** [comment]
> @cansavvy can check the details on the `pbta-tcga-manifest.tsv` to see if the BED files and Sample ID mapping making sense or not.

In the `pbta-tcga-manifest.tsv` file underneath `Capture-Kit` some files have two files listed? How was `Capture_Kit` determined?
```
"tcga_6k_genes.targetIntervals.bed|whole_exome_agilent_designed_120.targetIntervals.bed"
"tcga_6k_genes.targetIntervals.bed|whole_exome_agilent_plus_tcga_6k.targetIntervals.bed"
```
I notice `BED_In_Use` field has one file per sample and I'm assuming those are the BED files I should use? How was the `BED_In_Use` determined/distinguished from `Capture_Kit`?

**Comment by jaclyn-taroni** [comment]
Hi @yuankunzhu  - I wanted check in about getting `analyses/fusion-summary/results/fusion_summary_ewings_foi.tsv` added into this release and the timeframe for that. I was waiting to get started on #664.

**Comment by yuankunzhu** [comment]
Hi @cansavvy @jaclyn-taroni sorry for my late response. I took Monday and Tuesday off due to some personal issues. I will get the `fusion_summary_ewings_foi.tsv` into this release right now.

@cansavvy re your questions about the `BED_In_Use` vs `Capture_Kit`:
The `Capture_Kit` was the original return from GDC portal, however there're some samples has more than one capture kit values as the data provider can't figure out which one had actually been applied, therefore, you will see more than one BED files separated by `|` in the `Capture_Kit` column. While for the `BED_In_Use` is the actual BED files we are using, main difference is that 1) those were liftover'd to GRCh38 as the original one was hg19 based and 2) we made a new intersection BED for those "multiple BED" samples, and actually use it for the mutation calling. hence the name "BED in Use".

**Comment by jaclyn-taroni** [comment]
Hi @yuankunzhu - it looks like we may be missing `release-notes.md` (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/670#issue-397648626). It's possible that is because it is in the bucket but not in `md5sum.txt`.

**Comment by yuankunzhu** [comment]
Yes, I didn't include it on purpose. And it looks like we started to include it since v12? I can added it if needed. 

```
release-version	md5sum-grep-c
release-v10-20191115	0
release-v11-20191126	0
release-v12-20191217	1
release-v13-20200116	1
release-v14-20200203	1
release-v15-20200228	1
release-v16-20200320	0
release-v2-20190809	0
release-v3-20190829	0
release-v4-20190909	0
release-v5-20190924	0
release-v6-20191030	0
release-v7-20191031	0
release-v8-20191104	0
release-v9-20191105	0
```

didn't include previously for any of release that I did mainly bc 1) it's already updated in `docs/release-notes.md` and 2) i tend to put on a release notes as the last step after everything in place, QC and md5sum calculated, so it will be post md5sum process. but again can added it if the current CircleCI checks it

**Comment by jaclyn-taroni** [comment]
@yuankunzhu the issue is that once the `release-notes.md` started being included in the `md5sum.txt`, we altered the download script to accommodate that. We'll need to make changes to the download script to make sure it gets distributed. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/347/files#diff-87f5b2e6867ec2eca69de63f88344818R17

**Comment by jaclyn-taroni** [comment]
Updated with https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/657/commits/278ee54866e4afc2e64789dcf8baca73db6fa633

**Comment by yuankunzhu** [comment]
> @yuankunzhu the issue is that once the `release-notes.md` started being included in the `md5sum.txt`, we altered the download script to accommodate that. We'll need to make changes to the download script to make sure it gets distributed. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/347/files#diff-87f5b2e6867ec2eca69de63f88344818R17

I see. that makes sense. looks like you have it included already. i will make sure we have that for md5sum.txt for future release.

**Comment by jaclyn-taroni** [comment]
@yuankunzhu 

> i tend to put on a release notes as the last step after everything in place, QC and md5sum calculated, so it will be post md5sum process. but again can added it if the current CircleCI checks it

This rationale makes a lot of sense to me, so you can continue to leave it out of the `md5sum.txt`. I just wanted to make sure it got distributed and we were handling it appropriately with the testing files (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/670/commits/46feceeaccb2c4ff0a1e6c4df105ad2f51f1206b).

**Comment by jaclyn-taroni** [comment]
This is failing, but that's expected and fixed in #670.  I am going to merge.

**Pull request merged**
