### PR TITLE
Update MAF fields for v19 SNV consensus

### PR DESCRIPTION
**Pull request by jashapiro**
#### What scientific question is your analysis addressing?

In the updated MAF files for v19, some of the columns have changed (see https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-826828201). Mostly this is the removal of columns we were not using, but this broke the consensus script. 

There are also some new columns that are unique to specific callers. https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-826879406

#### What was your approach?

I modified to consensus script (specifically the building of the SNV database) to only specify column types for the fields that are universal across callers, and to only store those columns, disregarding the columns that are specific to individual callers.

The only added column is `HotspotAllele`. While the approach taken means this script will work with extra columns, it does now mean that the `HotspotAllele` column is required, so this will fail with the current CI files, until those have been updated to v19.

#### What GitHub issue does your pull request address?

#990 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

New consensus and tmb files will be uploaded to S3 soon.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jashapiro** [comment]
I have also added here now the updated consensus comparison notebook based on v19 data. It shows the radically different VarDict files as noted here: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-827638328

I am not sure whether this justifies changing the consensus algorithm... We could probably go to 3 of 4 callers now, but that would still not compare easily to the tcga data for which we don't have vardict results.

**Review by jharenza — COMMENTED** [review]
Hi @jashapiro - I think the column deletions and additions look good here, but just had a question - do you want to rerun the notebook noted belo wwith the new files added as of today?

> I have also added here now the updated consensus comparison notebook based on v19 data. It shows the radically different VarDict files as noted here: [#990 (comment)](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-827638328)

**Comment by jashapiro** [comment]
> Hi @jashapiro - I think the column deletions and additions look good here, but just had a question - do you want to rerun the notebook noted belo wwith the new files added as of today?
> 
> > I have also added here now the updated consensus comparison notebook based on v19 data. It shows the radically different VarDict files as noted here: [#990 (comment)](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-827638328)

Yes, I am rerunning it as we speak. It was during the rerun where the issue of the `experimental_strategy` change popped up.  https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1026#issuecomment-828597388. I don't think any of the consensus results should change, but I will be checking that.

**Comment by jashapiro** [comment]
> Yes, I am rerunning it as we speak. It was during the rerun where the issue of the `experimental_strategy` change popped up. [#1026 (comment)](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1026#issuecomment-828597388). I don't think any of the consensus results should change, but I will be checking that.

Just confirming that the consensus results did not change. (For some reason, the md5s of the files changed, but diff finds no changes, so it must be some subtle whitespace alterations.) The comparison results are still running though.

**Review by kgaonkar6 — APPROVED** [review]
LGTM! I re-ran and approving because it works with the new formatted mafs in v19 👍

**Pull request merged**
