### PR TITLE
Replace `integrated_diagnosis` with `harmonized_diagnosis` in sample distribution analysis module

### LINKED ISSUE #909: Updated analysis: Use `harmonized_diagnosis` in sample distribution analysis
#### What analysis module should be updated and why?

`sample-distribution-analysis` should be updated as part of #877.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As noted in the [comment on 877](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/877#issuecomment-759796037):

The main instances of `integrated_diagnosis` that need to be replaced with `harmonized_diagnosis` are linked below (noting that there are three individual scripts/notebooks that will need to be updated in this module).
Although only the main instances (instances that would affect the output) are linked below, changes should be propagated throughout each of the scripts/notebooks (including comments, file names, etc.) and the notebooks and/or module should be re-run.

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `sample-distribution-analysis/01-filter-across-types.R`     | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/01-filter-across-types.R#L32 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/01-filter-across-types.R#L58 |
| `sample-distribution-analysis/02-multilayer-plots.R` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/02-multilayer-plots.R#L46 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/02-multilayer-plots.R#L48 |
| `sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L218 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L219 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L231 |

#### What input data should be used? Which data were used in the version being updated?

It appears that this module was last re-run with v17 data in merged PR #782.
We will want to re-run this module with v18.

#### When do you expect the revised analysis will be completed?

~ 1 day (potential pitfalls are not obvious)

#### Who will complete the updated analysis?

TBD

### PR DESCRIPTION
**Pull request by cbethell**
#### What scientific question is your analysis addressing?

This PR addresses the following from issue #877
> As discussed in #870, and illustrated in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870#issuecomment-749690672, as of v18, the `integrated_diagnosis` column is not longer the most complete column from which to get diagnosis information. Analyses that relied on it should be updated to use the more complete `harmonized_diagnosis`.

#### What was your approach?

Using the [comment on 909](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/909#issue-786219688), I was able to locate the main instances where `integrated_diagnosis` needed to be replaced `harmonized_diagnosis`.

I then used search and replace to find any additional instances that needed to be replaced, and re-ran the module `run-sample-distribution.sh` script.

#### What GitHub issue does your pull request address?

This PR closes #909.

#### Which areas should receive a particularly close look?

The plots and results files have been updated in this PR, with what I believe are the expected changes with the change from using `integrated_diagnosis` to using the more complete `harmonized_diagnosis`.

These plots/results should receive another close look to ensure that these changes are indeed expected based on the upstream changes to v18.

#### Is there anything that you want to discuss further?

More specifically, as I note in the summary of results below:
> In `results/disease_expression.tsv`, the total number of samples is now 969 (using `sum(disease_expression$count)`), compared to the total number being 957 in the file last ran with v17 data.

Does this number seem expected?

Similarly,
> In `primary_sites_counts.tsv`, the total `number_of_types` are now 333 with the v18 data, compared to 243 with the v17 data (using `sum(primary_sites_counts$number_of_types)` to check).

Does this seem expected?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

The following plots have been updated:
- `plots/distribution_across_cancer_types.pdf`
- `distribution_across_cancer_types_treemap.pdf`

The following results files have been updated:
- `results/disease_expression.tsv`
- `results/plots_df.tsv`
- `results/primary_sites_counts.tsv`

#### What is your summary of the results?

As expected the `integrated_diagnosis` column has been replaced with the `harmonized_diagnosis` column in the results files.
This is accompanied with expected changes in naming (due to updates made in v18), as well as a change in the number of total samples.

In `results/disease_expression.tsv`, the total number of samples is now 969 (using `sum(disease_expression$count)` to check), compared to the total number being 957 in the file last ran with v17 data.

In `primary_sites_counts.tsv`, the total `number_of_types` are now 333 with the v18 data, compared to 243 with the v17 data (using `sum(primary_sites_counts$number_of_types)` to check).

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
I have not looked at the code. What did the total number of samples used to be? We have 8 new RNA-seq samples, but, depending on how that information is used, we may want to be summarizing on the _participant_ basis.

**Comment by jaclyn-taroni** [comment]
Ah I see - 957 + 8 does not equal 969 🤔

**Comment by cbethell** [comment]
> I have not looked at the code. What did the total number of samples used to be? We have 8 new RNA-seq samples, but, depending on how that information is used, we may want to be summarizing on the _participant_ basis.

Using [the comment tracking the additional 8 stranded RNA-seq samples](https://github.com/alexslemonade/openpbta-analysis/issues/749#issuecomment-721997172) and the [v18 release notes](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/release-notes.md#release-v18-20201123), I was able to determine that differences in numbers of samples for each category seems to indeed be due to the additional 8 samples and the more complete naming include in `harmonized_diagnosis` (which would be different from the previous values in `integrated_diagnosis`. For example, one of the added samples was classified as `Brainstem glioma- Diffuse intrinsic pontine glioma` and this category's count increased from 8 -> 9 `disease_expression.tsv`.

As for 
> In `primary_sites_counts.tsv`, the total `number_of_types` are now 333 with the v18 data, compared to 243 with the v17 data (using `sum(primary_sites_counts$number_of_types)` to check).

I was still unable to pinpoint the source of the difference in numbers here, even after taking a look at AlexsLemonade/OpenPBTA-analysis#838, but that does not rule it out!

**Review by jaclyn-taroni — APPROVED** [review]
These code changes LGTM! To respond to your questions about expected changes:

> In `results/disease_expression.tsv`, the total number of samples is now 969 (using `sum(disease_expression$count)` to check), compared to the total number being 957 in the file last ran with v17 data.

The total number of samples here refers to unique `Kids_First_Participant_ID`, `harmonized_diagnosis` pairs. So I think the question here is "Are there more participants with multiple `harmonized_diagnosis` values than we would expect?"

That's beyond the scope of what you're doing here, but I have filed #913 to track that. 

> In `primary_sites_counts.tsv`, the total `number_of_types` are now 333 with the v18 data, compared to 243 with the v17 data (using `sum(primary_sites_counts$number_of_types)` to check).

My understanding of `number_of_types` is that it counts the total number of `harmonized_diagnosis` values with at least one `Kids_First_Participant_ID` with that `primary_site` value. I think a lot of the increase is probably due to the fact that there are a lot more unique values in `harmonized_diagnosis` in v18 than in `integrated_diagnosis` in v17:

```R
> v17_df <- read_tsv("data/release-v17-20200908/pbta-histologies.tsv")
> v18_df <- read_tsv("data/release-v18-20201123/pbta-histologies.tsv")
> v17_df %>% 
+   select(integrated_diagnosis) %>% 
+   distinct() %>% 
+   count()
# A tibble: 1 x 1
      n
  <int>
1    64
> 
> v18_df %>% 
+   select(harmonized_diagnosis) %>% 
+   distinct() %>% 
+   count()
# A tibble: 1 x 1
      n
  <int>
1    92
```

But some of it may stem from the point above, too.

**Pull request merged**
