### PR TITLE
Find v18 breaking changes

### PR DESCRIPTION
**Pull request by cansavvy**
### Purpose/implementation Section

The v18 subset files have been added to S3. Now we need to know what's broken. I'm going to comment out broken modules and find things and record them here. 

### A running list of broken modules:

So far...

- `molecular-subtyping-ATRT/01-ATRT-molecular-subtyping-data-prep.Rmd` has this error (which looks label related and I'll comment more as I find out):
```
See spec(...) for full column specifications.
Error in labels_mat[, i] : subscript out of bounds
Calls: <Anonymous> ... Legend -> discrete_legend_body -> do.call -> lapply
In addition: Warning message:
In matrix(1:(nrow * ncol), nrow = nrow, ncol = ncol, byrow = by_row) :
  data length exceeds size of matrix
Execution halted
```

- `molecular-subtyping-EPN/02_ependymoma_generate_all_data.py` doesn't recognize the new biospecimen ID. See this [error here](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4711/workflows/f016e8ca-d982-4a12-9345-8e36e7913418/jobs/5243). 
```
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: ('BS_EVCAC3NH', 'occurred at index 90')
```

- `interaction-plots/01-create-interaction-plots.sh` has some troubles with this `combn` function. This is in the `scripts/coocur_functiions.R`. Line 94. See this [error here](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4712/workflows/8cf84b0a-6706-4f88-b159-cfaf3c29b74e/jobs/5244). 
```
Error in combn(genes, m = 2) : n < m
Calls: coocurrence -> t -> combn
Execution halted
```

-  None of the Comparative RNA-seq analyses are running. The first error was: `analyses/comparative-RNASeq-analysis/01-correlation-matrix.py`my suspicions is that the others are dependent on the first one completing so I'm not sure if they also have separate issues. See this [error here](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4713/workflows/77db5ed6-603f-43b0-af49-9de84a96e63f/jobs/5245).
```
File "analyses/comparative-RNASeq-analysis/01-correlation-matrix.py", line 30, in extract_sample_qc_status
    status = qc_file_handle.readlines()[1][-5:-1].decode("utf-8")
IndexError: list index out of range
```

- gistic plots are not running from an error in `analyses/cnv-chrom-plot/gistic_plot.Rmd`. See the full [error here](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/4717/workflows/0b1743e9-f22a-4048-8b47-67662dcb842a/jobs/5249). 
```
Quitting from lines 157-213 (gistic_plot.Rmd) 
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  In range 1: at least two out of 'start', 'end', and 'width', must
  be supplied.
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> solveUserSEW0 -> .Call2
```

### CODE REVIEW

**Comment by cansavvy** [comment]
I'm holding up on further investigation based on the unusually high number of NAs in `short_histology`: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/875

**Comment by kgaonkar6** [comment]
Hi @cansavvy , I'm looking into this. 
short and broad histologies were mapped from path_dx in v18 I'll check mapping and get back to you.

**Comment by kgaonkar6** [comment]
ok so the issue was at the last step `molecular-subtype-integrate` module which was added as part of v18 release to add the subtyping to base histology. 

I was only adding the subtyped broad_hist and short_hist instead of carrying over the original broad and short histology for samples that are not subtyped example ATRT. I've updated it as part of [018db25](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870/commits/018db25cd1dbdc61c7d468cef9622b2fa7f86d88) and added some additional checks.

**Comment by cansavvy** [comment]
> ok so the issue was at the last step `molecular-subtype-integrate` module which was added as part of v18 release to add the subtyping to base histology.
> 
> I was only adding the subtyped broad_hist and short_hist instead of carrying over the original broad and short histology for samples that are not subtyped example ATRT. I've updated it as part of [018db25](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870/commits/018db25cd1dbdc61c7d468cef9622b2fa7f86d88) and added some additional checks.

Can you add the updated file to the data download? We are trying to do the PRs in order so we ideally won't get to part 7 until we've been able to successfully run CI tests on parts 1 through 6 and we won't be able to do that before I redo the subsetting. 

I think if you can, it would be good if you can make [018db25](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870/commits/018db25cd1dbdc61c7d468cef9622b2fa7f86d88)  it's own PR for review.

**Comment by kgaonkar6** [comment]
@cansavvy I've just updated the file on s3 and download_script.sh passes all md5sum checks.

**Comment by cansavvy** [comment]
I'm going to close this PR and reopen a similar one now that I updated the histologies file in the S3 subsetted files testing bucket.

**Pull request closed without merging**
