### PR TITLE
Medulloblastoma_EXTENDscores_Comparison

### PR DESCRIPTION
**Pull request by NNoureen**
### Purpose/implementation Section
The purpose here is to compare EXTEND scores for Medulloblastoma molecular subtypes

#### What was your approach?
We used our newly developed method EXTEND (Expression based Telomerase ENzymatic activity Detection) for telomerase activities prediction. We have compared medulloblastoma molecular subtypes scores using student’s t-test and visualized it using boxplots.

#### What GitHub issue does your pull request address?
Issue #148 (Quantify telomerase activity across pediatric brain tumors)

#### Which areas should receive a particularly close look?
We would like the reviewers to check script 05 comparing telomerase activities for medulloblastoma molecular subtypes.
#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES
#### What types of results are included (e.g., table, figure)?
Plot is built using script -05 to compare the telomerase scores for medulloblastoma molecular subtypes.
#### What is your summary of the results?
Distribution of telomerase activities across different medulloblastoma molecular subtypes using boxplots whereas the p-values defines the differential patterns among them.

#### Documentation Checklist

This analysis module has a `README` and it is up to date.
This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
The analytical code is documented.

### CODE REVIEW

**Comment by sjspielman** [comment]
This figure seems fine, *however* the implemented use of P-values needs to be changed.

1) First, we have a statistical issue of *multiple testing* - the code is implicitly performing four t-tests, so a correction needs to be applied. In this case, the P-values are mostly not significant at $\alpha=0.05$ except for the SSH/WNT comparison, but when corrected I suspect the significance will go away. The simplest approach in terms of correcting P-values is to use the Bonferroni correction (divide each P-value by the number of tests done). I gather this plotting aspect is performed by `ggpubr::stat_compare_means()`, but there does not appear to be an argument to deal with multiple comparisons for that function. This will take some more digging into.

2) Is there a specific reason only 4 comparisons were performed rather than all-to-all? This selection of comparisons is not clearly documented.

**Comment by NNoureen** [comment]
Thanks. I will update the plot for all comparisons and multiple testing as well.

**Comment by NNoureen** [comment]
Hi Dr. Stephanie
I have updated the code for all comparisons and have used the adjusted p-values for labeling, though they are no more significant

**Comment by sjspielman** [comment]
Hi @NNoureen, looks good to me! I am not very concerned that significance has disappeared; the goal is more to apply robust statistics rather than to chase down significance. The data we have is the data we have, and if it's not significant that's just something else to conclude - certainly not a failed analysis!!

**Comment by NNoureen** [comment]
Thanks for your help.

**Pull request merged**
