### PR TITLE
v22-release (1/N release)

### LINKED ISSUE #1207: V22 data release
From the below conversation, we will push one more release to include the missed _to be classified_ MB subtypes into the histology file. This will require rerunning the molecular subtyping to create the new histology file.

I don't think we want to be in a situation where the release and the supplemental data are out of sync, but perhaps the new release can be the very last thing we do before we cut a release of the codebase.

__Originally posted by @jaclyn-taroni in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1206#issuecomment-982880365__

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
Closes #1207 

#### What GitHub issue does your pull request address?
#1207 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
no

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [x] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?
- [x] Was download-data.sh tested and did it complete without error?

### CODE REVIEW

**Comment by jharenza** [comment]
Just noting that all files from #1412 are in the v22 S3 folder, and `pbta-histologies-base.tsv` has been added. 
To do: update release notes, run subtyping (next), generate `pbta-histologies.tsv`

**Comment by jharenza** [comment]
Some changes I would like to document for this release:
- 19 patients have lower OS_days than previously. The clinical data is undergoing cleaning, and these may be investigated in the future. 

sample_id | OS_days_latest | OS_days_previous | change_ok | diff_days
-- | -- | -- | -- | --
7316-370 | 772 | 776 | CHECK | -4
7316-2213 | 4960 | 4962 | CHECK | -2
7316-198 | 575 | 592 | CHECK | -17
7316-224 | 402 | 403 | CHECK | -1
7316-482 | 1453 | 1473 | CHECK | -20
7316-355 | 1579 | 1966 | CHECK | -387
7316-178 | 1434 | 1840 | CHECK | -406
7316-3208 | 179 | 181 | CHECK | -2
7316-490 | 575 | 592 | CHECK | -17
7316-1462 | 1579 | 1966 | CHECK | -387
7316-2162 | 1247 | 1625 | CHECK | -378
7316-1808 | 176 | 2157 | CHECK | -1981
7316-2237 | 4960 | 4962 | CHECK | -2
7316-456 | 85 | 105 | CHECK | -20
7316-741 | 1247 | 1625 | CHECK | -378
7316-2605 | 176 | 2157 | CHECK | -1981
7316-2124 | 355 | 2119 | CHECK | -1764
7316-1794 | 355 | 2119 | CHECK | -1764
7316-2781 | 179 | 181 | CHECK | -2

- 24 samples' `tumor_descriptor` changed:

Kids_First_Biospecimen_ID | sample_id | tumor_descriptor_latest | tumor_descriptor_previous
-- | -- | -- | --
BS_23ZE42Q3 | 7316-3206 | Initial CNS Tumor | Progressive
BS_25T139TX | 7316-2130 | Progressive | Initial CNS Tumor
BS_4NPEMNAD | 7316-224 | Initial CNS Tumor | Progressive
BS_69V8P8A0 | 7316-209 | Progressive | Second Malignancy
BS_97M1E2DW | 7316-3208 | Initial CNS Tumor | Progressive
BS_B9V8RGTA | 7316-956 | Progressive | Second Malignancy
BS_C7N3J4NW | 7316-2237 | Recurrence | Progressive
BS_DH86PF5A | 7316-3208 | Initial CNS Tumor | Progressive
BS_DY88N5ZT | 7316-224 | Initial CNS Tumor | Progressive
BS_EJ1H9PZY | 7316-4035 | Recurrence | Progressive
BS_GS9JCK55 | 7316-2680 | Recurrence | Progressive
BS_J52D4XQY | 7316-128 | Progressive | Second Malignancy
BS_KK0JWATQ | 7316-1456 | Unavailable | Second Malignancy
BS_KV3XF9WV | 7316-209 | Progressive | Second Malignancy
BS_MCM78YPC | 7316-1456 | Unavailable | Second Malignancy
BS_MWZCP1XW | 7316-956 | Progressive | Second Malignancy
BS_P277RYX5 | 7316-2680 | Recurrence | Progressive
BS_PSNBFWQV | 7316-128 | Progressive | Second Malignancy
BS_QE7WAAKC | 7316-2237 | Recurrence | Progressive
BS_W4DB5RP1 | 7316-550 | Progressive | Initial CNS Tumor
BS_WGK8ZMVA | 7316-4035 | Recurrence | Progressive
BS_WH8G4VFB | 7316-3206 | Initial CNS Tumor | Progressive
BS_X9PJ715R | 7316-1794 | Progressive | Recurrence
BS_ZV9Z3SY6 | 7316-1794 | Progressive | Recurrence

- `sample_id` 7316-3214 was updated to: 7316-3214-A07081, 7316-3214-A07083, and 7316-3214-A07082 for different BS_ids.

- In addition, a handful of `pathology_diagnosis` and `pathology_free_text_diagnosis` changed.

**Comment by jharenza** [comment]
@jaclyn-taroni I am going to mark this as ready for review since I have updated the release notes here. Note: this is not yet on S3 - waiting for review here/if you would like me to include anything else.

**Comment by jharenza** [comment]
Ready for full review @jaclyn-taroni

**Comment by jaclyn-taroni** [comment]
Most recent commit is a docs only change. It passed early, so I am merging without waiting for CI to finish.

**Pull request merged**
