### PR TITLE
Install MATLAB Compiler Runtime on project Docker container

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
### Purpose/implementation Section

I am opening this draft pull request to take advantage of the Docker layer cache in Circle to test Docker builds. 

#### What GitHub issue does your pull request address?

#529

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
@jashapiro any ideas as to why the copy number consensus is failing: https://circleci.com/gh/AlexsLemonade/OpenPBTA-analysis/3144

**Comment by jashapiro** [comment]
RElevant: https://github.com/cbm755/octsympy/issues/63

**Comment by jashapiro** [comment]
This is always a fun kind of comment:
> Making the library coming with matlab invisible/unloadable solved the
problem, but maybe i will encounter some side effects ...
https://github.com/cbm755/octsympy/issues/905#issuecomment-410087076

**Comment by jaclyn-taroni** [comment]
@cgreene - I expect this to fail on the last step with something like:

```
Setting Matlab MCR root to /rocker-build/gistic_install/MATLAB_Compiler_Runtime
./gp_gistic2_from_seg: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
```

Except it will also complain about version -- we can set the version in the `gistic2` executable that's included in the root directory of the GISTIC download. But notably ☝️ is the error I got when installing 2014a which matches the version in the GISTIC instructions.

**Comment by jaclyn-taroni** [comment]
Additional context -- contents of `gistic2` are: 
```
#!/bin/sh
## set MCR environment and launch GISTIC executable

## NOTE: change the line below if you have installed the Matlab MCR in an alternative location
MCR_ROOT=`pwd`/MATLAB_Compiler_Runtime
MCR_VER=v83

echo Setting Matlab MCR root to $MCR_ROOT

## set up environment variables
LD_LIBRARY_PATH=$MCR_ROOT/$MCR_VER/runtime/glnxa64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$MCR_ROOT/$MCR_VER/bin/glnxa64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$MCR_ROOT/$MCR_VER/sys/os/glnxa64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
XAPPLRESDIR=$MCR_ROOT/$MCR_VER/MATLAB_Component_Runtime/v83/X11/app-defaults
export XAPPLRESDIR

## launch GISTIC executable
./gp_gistic2_from_seg $@
```

**Comment by jaclyn-taroni** [comment]
FWIW, I got the same error building locally that shows up in CI right now.

**Comment by jaclyn-taroni** [comment]
@cgreene I think the move ™️  is going to be dealing with the MCR environmental variables at the time that we run GISTIC

**Pull request merged**
