### PR TITLE
V19 ci files

### PR DESCRIPTION
**Pull request by kgaonkar6**
⚠️  staggered PR merge subtyping #1028 before this PR

#### What scientific question is your analysis addressing?
Create subset files for CI for v19 release

#### What was your approach?
Referring to some of the instructions from the previous release #871 and #670 created the testing files by:

1. Start AWS instance with >=128 GB RAM
2. Clone OpenPBTA-analysis
3. Create a new branch off of kgaonkar6:v19-release to create v19-ci-files
- Update the release to release-v19-20210423 in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1038/commits/916a346df02ed2bc69d36aa58a51e98f08a01268
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/35384c7430b428f5017496ed11e0b2ce30969239/analyses/create-subset-files/create_subset_files.sh#L10
 4. Run bash analyses/create-subset-files/create_subset_files.sh
 5. Commit the biospecimen RDS file to v19-ci-files branch. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1038/commits/769ecc902fd6bdddb92445b83a2b0bf4c0cf3461
 6. Zip up the subset files in data/testing/release-v19-20210423/ to testing_v19.zip 
 7. Download testing_v19.zip
 8. File a pull request from v19-ci-files

#### What GitHub issue does your pull request address?
#1029 

#### Which areas should receive a particularly close look?
Can I have access to the s3 bucket to upload the testing files? Or should I upload  the testing files to s3://kf-openaccess-us-east-1-prd-pbta/data/ where we also have the release folders?

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jashapiro — COMMENTED** [review]
I can copy the files to the S3 bucket if you give me URL where I can download them.

This PR contains a large number of extra file changes; it will need to be cleaned up before merging.

**Comment by kgaonkar6** [comment]
Thanks! I've uploaded the current testing file in a zip file here: https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip.

In #1028 I'm re-running all modules required for sutyping https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/scripts/run-for-subtyping.sh. I  believe that #1028 should go in before this PR since the `pbta-hisologies.tsv` file is re-generated for v19 in that PR. 

Would you like me to make a PR in my forked repo comparing changes in this `kgaonkar6:v19-ci-files` and `kgaonkar6:v19-release` which is #1028 instead?

**Comment by jashapiro** [comment]
Thanks for the link... It looks like this does not use updated the consensus files from https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/990#issuecomment-827638328 which I think we will want to do? We are also expecting new VarDict files (later in that thread), so you should probably wait to rerun it until those come in too. (The consensus files won't change, because they don't use VarDict.)

I can review again when the other changes have been merged, so I know which files to look at. (I think I looked at the ones that are relevant, and they look fine, but we will want to be sure that other changes or reversions don't sneak in.)

**Comment by kgaonkar6** [comment]
Ah yes I'll keep an eye on that #990 for that update and re-run!

**Comment by kgaonkar6** [comment]
@jashapiro I've updated the testing files https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip with updated vardict and consensus maf & tmb files

**Comment by jashapiro** [comment]
> @jashapiro I've updated the testing files https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip with updated vardict and consensus maf & tmb files

Just to clarify: will these files get further updates with the subtyping that is in progress? If so, which files do we expect to change? Should we separate this PR and get it in with some interim data, or wait for #1028 & the final files?

**Comment by kgaonkar6** [comment]
I actually did update all files from #1028  (processed rnaseq files and pbta-histologies.tsv) to the testing files and release-v19-20210423 on s3. I was thinking if anything changes in the open PRs I can update the files on s3.

**Comment by kgaonkar6** [comment]
I will be updating the testing and release-v19-20210423 file with: 
- [ ] pbta-histologies-base.tsv ( adding parent_aliquot_id values and dropping kf_visibility and broad_composition)
- [ ] pbta-histologies.tsv (propogating the changes above)
- [ ] pbta-fusion-recurrent-fusion-bysample.tsv ( update with this fix https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1041#issuecomment-828584737)

**Comment by kgaonkar6** [comment]
@jashapiro I've updated the testing files https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip with updated histologies file and the recurrent fusion file that needed an update.

**Comment by jashapiro** [comment]
> @jashapiro I've updated the testing files https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip with updated histologies file and the recurrent fusion file that needed an update.

Thanks! I think I am going to hold off on uploading these to staging for now, unless somebody has an objection... The reason is that I think the v19 files will break a number of modules which will lead to all of the histology update PRs failing CI. Once we have all the histology updates in, we will be able to identify the broken modules and comment them out as part of this PR, creating issues to fix them as we go.

**Comment by kgaonkar6** [comment]
@jashapiro the CI files are in https://kf-openaccess-us-east-1-prd-pbta.s3.amazonaws.com/data/testing_v19.zip with the following updates:

- histology file update form #1047 
- raw snv reruns https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1028#issuecomment-829752928
- consensus maf rerun https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1033#issuecomment-830286625

**Comment by jashapiro** [comment]
I have uploaded the CI files, so merging in master will start to show us what has broken.

**Comment by jharenza** [comment]
> I have uploaded the CI files, so merging in master will start to show us what has broken.

🤞

**Comment by kgaonkar6** [comment]
The CI is breaking at:

- High level histology grouping for plot labels ( fixed by @jashapiro in this PR )
- TCGA SNV Caller Analysis 
- SNV Caller Analysis
- Tumor mutation burden with TCGA
- Exploration of nonsynonymous filter
- Compare TMB calculations

Seems to me all the modules that break are dependent on snv-callers which is already updated in #1033.

**Review by jashapiro — APPROVED** [review]
> The CI is breaking at:
> 
> * High level histology grouping for plot labels ( fixed by @jashapiro in this PR )
> * TCGA SNV Caller Analysis
> * SNV Caller Analysis
> * Tumor mutation burden with TCGA
> * Exploration of nonsynonymous filter
> * Compare TMB calculations
> 
> Seems to me all the modules that break are dependent on snv-callers which is already updated in #1033.

I think that is probably correct... After this is merged, we can see how much #1033 fixes (hopefully all!).

**Pull request merged**
