### PR TITLE
(2 of 2) add H3 K28 subtype for 7316-2557 (redo)

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
This PR addresses #905 - updating pathology subtyping for 7316-2557.

#### What was your approach?
Update the H3 subtype for 7316-2557

#### What GitHub issue does your pull request address?
#905.

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
added the following to `compiled_molecular_subtypes_with_clinical_pathology_feedback.tsv`:

Kids_First_Participant_ID<chr> | sample_id<chr> | Kids_First_Biospecimen_ID<chr> | molecular_subtype<chr> | integrated_diagnosis<chr> | short_histology<chr> |  
-- | -- | -- | -- | -- | -- | --
PT_A325EYR2 | 7316-2557 | BS_5965SFPZ | DMG, H3 K28 | Diffuse midline glioma, H3 K28-mutant | HGAT |  
PT_A325EYR2 | 7316-2557 | BS_YB99Q6TN | DMG, H3 K28 | Diffuse midline glioma, H3 K28-mutant | HGAT |  

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@kgaonkar6 @jaclyn-taroni - sorry about that - just filed a new PR for this

**Review by kgaonkar6 — COMMENTED** [review]
Looks good to me! I just had a process question, will we need a 3rd PR to rerun molecular-subtype-integrate module OR would that module only be re-run per release?

**Review by kgaonkar6 — APPROVED** [review]

**Review by jaclyn-taroni — APPROVED** [review]

**Comment by jaclyn-taroni** [comment]
I'm going to merge this since the changes mentioned in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/935#pullrequestreview-586000957 are in the context of another PR.

**Comment by jharenza** [comment]
> Looks good to me! I just had a process question, will we need a 3rd PR to rerun molecular-subtype-integrate module OR would that module only be re-run per release?

I think we can plan to run that per release

**Pull request merged**
