### PR TITLE
Compare_Medulloblastoma_Subtypes

### PR DESCRIPTION
**Pull request by NNoureen**
Comparison of telomerase activities for medulloblastoma molecular subtypes

### CODE REVIEW

**Comment by sjspielman** [comment]
Hi @NNoureen, 

I've been assigned to review this PR. In order to to do, it will be extremely helpful for you to fill out the formal PR template that delineates the goals, particular areas for reviewers to look at, etc. of this analysis. Please add this back in, thanks! Template is here: [https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/PULL_REQUEST_TEMPLATE.md](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

In addition, doing a quick overview of the changed files, I noticed you changed the `-04` script and created `-05` script for this PR. Depending on the overall goals, it may be helpful to split these up, but we'll see after the PR template is filled out. 

Thanks!
-Stephanie

**Comment by NNoureen** [comment]
Sure. I will fill out the template for this PR. Thanks

**Comment by NNoureen** [comment]
Hi Dr. Stephanie, I have done the first pull request for first change in script -04. I will do the second PR for -05 script after that. As you said we need to do it separately

**Comment by sjspielman** [comment]
>Hi Dr. Stephanie, I have done the first pull request for first change in script -04. I will do the second PR for -05 script after that. As you said we need to do it separately 
Ok, I will close this PR then. We'll deal with the new #681 first, and then make another PR for the 05 script!

**Comment by NNoureen** [comment]
Sure. Thanks

**Pull request closed without merging**
