### PR TITLE
WIP: Update R to 3.6.2

### PR DESCRIPTION
**Pull request by jashapiro**
#### What scientific question is your analysis addressing?

Since we seem to have run into some new dependency troubles, we might take the opportunity to update to a more current base image, including R 3.6.2. 

#### What was your approach?

I changed the base image in the Dockerfile, and while I was at it, moved a number of the more commonly used R packages to earlier layers.

#### What GitHub issue does your pull request address?

#400 

#### Which areas should receive a particularly close look?

Does everything run? I am assuming there will not be major changes in results, but that might be worth checking.

#### Is there anything that you want to discuss further?

More reorganization might be warranted, but at this stage, the question is mostly about how much this will break. If this is successful, it might be worth a bigger reorg before merging.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Nope. Also No. Certainly not.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by sjspielman** [comment]
Let's see how the current build for PR #683 goes, and then perhaps worth closing it to centralize efforts here to fix the surprising mystery version conflicts? @jashapiro , any preference?

**Comment by jashapiro** [comment]
> Let's see how the current build for PR #683 goes, and then perhaps worth closing it to centralize efforts here to fix the surprising mystery version conflicts? @jashapiro , any preference?

I think we want to get #683 done if we can figure it out quickly, as properly merging this will require rerunning _everything_. So I would vote to maintain these in parallel at least for now.

**Comment by sjspielman** [comment]
If the issue turns out to be `r-cran`, #683 is moot anyways and should be deleted, with this one taking precedent.

**Comment by jashapiro** [comment]
Closing for now. May return in the future.

**Pull request closed without merging**
