### PR TITLE
#1144 part3 update telomerase activities figure

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Update Telomerase activity with cancer_groups.

#### What was your approach?
Updated code to only plot cancer_groups for main figure

#### What GitHub issue does your pull request address?
#1144

#### Which areas should receive a particularly close look?
Do we want the Medulloblastoma or other molecular subtype plots in this figure? 

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
figure

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jaclyn-taroni — APPROVED** [review]
Looks good to me 👍🏻

**Review by jharenza — APPROVED** [review]
Thanks @kgaonkar6 - I just see an `NA` group at the end of the boxplot, so if you can remove that, I will pre-approve and @jaclyn-taroni can merge afterwards :)

**Comment by jaclyn-taroni** [comment]
I'm going to label this with `don't merge` until the `NA` gets removed.

**Comment by kgaonkar6** [comment]
@jaclyn-taroni I've removed the NA now. Thanks for the review @jharenza @jaclyn-taroni !

**Pull request merged**
