### PR TITLE
Updated immune-deconv module README's xCell method description

### PR DESCRIPTION
**Pull request by sjspielman**
This PR addresses issue #1233 and updates the `immune-deconv` analysis README.md description xCell score interpretation. These scores can be compared across samples, but _not_ across cell types, so the README now reflects this information.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
This looks good to me - just added @komalsrathi for review as well since she worked on the module, to make sure this is her understanding also.

**Review by komalsrathi — APPROVED** [review]
@jharenza yes this is correct, my bad. And if you are wondering - I did make this change in the OT repo but forgot to update here.

**Comment by sjspielman** [comment]
Thanks for having a look @jharenza @komalsrathi !

**Comment by jaclyn-taroni** [comment]
Docs only change, merging without CI.

**Pull request merged**
