### PR TITLE
Check that files in data are unchanged in CI

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
### Purpose/implementation Section

Here I'm making a change to our download script such that the `data` directory will no longer have write permissions once it's done running in CI. This helps us ensure that all modules are being tested on the same set of files.

#### What GitHub issue does your pull request address?

N/A

#### Which areas should receive a particularly close look?

Is this the best way to implement this?

### CODE REVIEW

**Comment by cgreene** [comment]
Removing execute on directories makes them invisible but traversable. I think you just want the -w. Let's see what this does on CI :)

**Comment by jaclyn-taroni** [comment]
Hopefully it fails!

**Comment by cgreene** [comment]
But on the writing step and not the cd step 😁

**Comment by jaclyn-taroni** [comment]
Same exit status @cgreene

**Comment by cgreene** [comment]
> ^@^@cd: usage: cd path prog...
😕

**Comment by jashapiro** [comment]
Nope. ???

**Comment by jashapiro** [comment]
Since this seems to be failing in mysterious ways, maybe we should change approach? How about checking that the files in data are unchanged as a final step? I would think checking modification times could be sufficient... Thoughts?

**Comment by jaclyn-taroni** [comment]
> How about checking that the files in data are unchanged as a final step? 

To clarify - The last step in CI _not_ the last step in the download step, correct?

**Comment by jaclyn-taroni** [comment]
#317 is the preferred approach, so I am closing this.

**Pull request closed without merging**
