### PR TITLE
Remove immune-deconv module heatmaps

### PR DESCRIPTION
**Pull request by sjspielman**
This PR addresses issue #1240. Figures and associated code for heatmaps made from `xCell` immune deconvolution are removed. Updated figures will be added in future PRs. 
 
#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
I'd expect to see some heatmap-related stuff come out of `util`, too. Thoughts?

**Comment by sjspielman** [comment]
> I'd expect to see some heatmap-related stuff come out of util, too. Thoughts?
Yes good point!

**Comment by sjspielman** [comment]
`util` directory only contains plotting code so it has now also been removed.

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻

**Pull request merged**
