### PR TITLE
add molecular subtype to wgs-only samples

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

WGS only samples are missing medulloblastoma molecular subtype info. They need to be annotated as "To be Classified"

#### What was your approach?

Added a separate script to append wgs-only samples to the output tsv files

#### What GitHub issue does your pull request address?

https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1183

#### Which areas should receive a particularly close look?

04-no-RNA-samples.R and output tsv files

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

tsv files

#### What is your summary of the results?

N/A

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
Thanks @komalsrathi - this looks good!

**Comment by jaclyn-taroni** [comment]
Just to note, these changes won't take effect unless we cut another release, correct?

**Comment by jharenza** [comment]
> Just to note, these changes won't take effect unless we cut another release, correct?

I wasn't thinking of another release, but just adding them to our histologies file in the supplement. Do you want us to rerun subtyping and do another release for that to happen?

**Comment by jaclyn-taroni** [comment]
I don't think we want to be in a situation where the release and the supplemental data are out of sync, but perhaps the new release can be the very last thing we do before we cut a release of the codebase.

**Comment by jharenza** [comment]
> I don't think we want to be in a situation where the release and the supplemental data are out of sync, but perhaps the new release can be the very last thing we do before we cut a release of the codebase.

Ok, sounds good - put in #1207 for this

**Pull request merged**
