### PR TITLE
Immunedeconv molsubtype

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

Add one heatmap figure per broad histology with rows being molecular subtype.

#### What was your approach?

Use data version v19 and associated files. 

#### What GitHub issue does your pull request address?

https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/965

#### Which areas should receive a particularly close look?

N/A

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

Heatmap of immune scores stratified by molecular subtype

#### What is your summary of the results?

N/A

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
@jharenza please review and let me know. Thanks!

**Comment by jharenza** [comment]
Hi @komalsrathi. I think this looks almost ready. Will you remove subtypes which == NA and any which are To be classified?

**Comment by komalsrathi** [comment]
@jharenza let me know if this looks good to merge.

**Comment by jharenza** [comment]
Great, thanks!

**Pull request merged**
