### PR TITLE
04 project specific filtering

### PR DESCRIPTION
**Pull request by kgaonkar6**
### Purpose/implementation Section
project specific filtering to capture recurrent fusion and oncogene annotated gene fusions. 
UPDATE: the genereference list was updated 11/25 to remove curated and predicted TF gene list.

#### Putative Driver:
Filtering for general cancer specific genes
Fusions with genes in either onco from 02 script in columns Gene1A_anno,Gene1B_anno,Gene2A_anno,Gene2B_anno

#### Scavenge back filtered fusions to add to putative oncogenic fusions:
1. In-frame/frameshift fusions is called in atleast 2 samples per histology OR
2. In-frame/frameshift fusions is called in atleast 2 callers 
AND
Remove filtered-fusions found in more than 1 histology OR
Remove filtered-fusion with genes that have multi-fused gene (more than 5 times in sample)

#### What scientific question is your analysis addressing?
Filtering for recurrent fusions and oncogenic fusion in all histologies

#### What was your approach?
Mostly summarizing data to identify 
 * if annotated as oncogenic (from genereferencelist and fusionreferencelist in reference folder)
 * if inframe/frameshift found in both callers/called in more than 2 samples per histology ;these fusions should also be uniquely found in a histology and not multifused ( We call a gene multifused if we identify more than 5 different partner genes for a gene in a sample )

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
We want to  retain unique calls for oncoprint so I've only kept columns that I think that don't duplicate the fusion calls. 

For example each FusionName may have duplicate rows because of different so I've removed the following columns.
-Caller,-annots,-JunctionReadCount,-SpanningFragCount,-Confidence,-LeftBreakpoint,-RightBreakpoint in the final fusion calls

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes this table is ready for oncoprint:
results/PutativeDriverFusion.tsv 

### Results
results/PutativeDriverFusion.tsv 

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
3213 Fusions are identified as putative oncogenic fusions for PBTA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 is this just a matter of updating the reference lists and rerunning without changes to `04-project-specific-filtering.Rmd`?  `04-project-specific-filtering.Rmd` is showing up as entirely new in the `Files Changed` tab and this branch has conflicts that are too complex to be handled via the web interface. I think this may have come about as a result of adding these changes to the same branch `kgaonkar6:04_project_specific_filtering` as the changes that went in as part of #277. 

I would recommend syncing your master branch with the upstream AlexsLemonade master, creating a new branch (e.g., `update_fusion_references`), adding and committing the changes to the reference list, rerunning the pipeline, and then adding a committing the changes to the output (e.g., `results/FilteredFusion.tsv`, `results/PutativeDriverFusion.tsv`).

Side note -- are these the results that are part of the v11 release (#293 / #287), i.e., those use the updated references?

**Comment by jharenza** [comment]
Hi @jaclyn-taroni - I can answer the last question. Yes, this update was already performed for the table in the V11 release (only two fusions were removed `KAT2B--LINC02008` and `SF1--MTA2` and I looked into them - no evidence in the literature. `SF1` had previously been reported in a leukemia, but with an oncogenic partner, `PDGFRA`. In our pipeline, if we saw this, it would come out because it has an oncogenic partner, so this made me comfortable removing these not so validated lists of TFs).

To explain further, as I was writing the [methods](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#fusion-prioritization), I actually did not realize @kgaonkar6 was collecting all TFs from TRANSFAC lists (N = 158 from predicted TFs, 201 from curated TFs) plus the Cell paper cited with a more validated list. I thought it was just the latter, so that was some miscommunication on our end. I inspected the differences and many of the added "TF" from TRANSFAC are really cofactors (eg: LMO2, RB1, NF1 and not TFs; though, as they are oncogenes, they would be retained via that list), so we opted for just the list from the Cell paper, which were deemed YES TFs (N = 1639). So, we updated this to only use the validated list and in an effort to not do multiple releases of this, we updated the V11 file already. 

Hope this helps. Happy Thanksgiving! :)

**Comment by jaclyn-taroni** [comment]
Thank you @jharenza, that's helpful in thinking about documentation around v11. Happy Thanksgiving!

**Comment by kgaonkar6** [comment]
Thanks @jaclyn-taroni @jharenza , I was trying to checkout master after the fetch upstream command but it would ask me to commit the changes I already had made to the reference and results folder so I thought of committing it to this branch itself would fix that. I'll try to sync the master to upstream again and follow your suggestions to create a new branch.

**Pull request closed without merging**
