### PR TITLE
Compiled figure 5

### PR DESCRIPTION
**Pull request by sjspielman**
Partially addresses issues #1321 and #1322 by updating **Figure 5** panels and adding the compiled PDF and PNG.

This PR copies the updated Figure 5 panels into figures, adds a line in `generate_figures.sh` to perform the copying, and adds compiled Figure 5.

One question: should we retain the `broad_histology` label on the GSVA heatmap?

### CODE REVIEW

**Comment by jharenza** [comment]
> One question: should we retain the broad_histology label on the GSVA heatmap?

We did this to match UMAP, but I did find it harder to write about in the manuscript. However, the analysis is also done on broad histology. I think we can either retain broad histology labels and analysis, and add another annotation row for cancer group OR retain broad labels, run another analysis on cancer group and add the annotation for cancer group. I'll just have to update the text for the latter making sure the cancer groups' scores are significant, but it may be useful/easier to write to have the latter results and both labels (that'll require another legend).

**Comment by sjspielman** [comment]
This PR is now out of date given #1336. I'm going to convert this to a draft and block with the 5D panel.

**Comment by sjspielman** [comment]
@jharenza at long last this is ready again!

Note that as part of this I had to update the overall sizing for the quantiseq panel.

**Review by jharenza — APPROVED** [review]

**Comment by sjspielman** [comment]
The `immune-deconv` module of interest has passed CI so this can be merged in now.

**Pull request merged**
