### PR TITLE
CI calculation added for odds ratio

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Add confidence interval calculation for odds ratio in `interaction-plots` module

#### What was your approach?
Three columns - `standard_error_or`, `or_ci_lower_bound` and `or_ci_upper_bound` were added to the results column with the following calculation - 
```
      standard_error_or = sqrt(1/mut11 + 1/mut00 + 1/mut10 + 1/mut01),
      or_ci_lower_bound = exp(log(odds_ratio) - 1.96 * standard_error_or),
      or_ci_upper_bound = exp(log(odds_ratio) + 1.96 * standard_error_or)
```

#### What GitHub issue does your pull request address?
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1203

#### Which areas should receive a particularly close look?
Please check and see the addition of CI related columns are as wanted. 

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
All the *.tsv files in the results folder are updated with addition of CI related columns. 

#### What is your summary of the results?
Spot checked a couple entries and the numbers make sense. 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jashapiro — COMMENTED** [review]
Hi @runjin326-
Thank you for implementing this! 

Unfortunately, the simple OR CI calculation that you implemented here is probably not quite what we will want, as it results in Inf/NA any time we have a `0` count. There are two potential solutions that I can think of:

One is to implement Haldane's Correction when there are zero counts: This would mean adding `0.5` to _all_ counts in the table if _any_ counts are zero, then performing the same standard error calculation as before. This is probably the easiest to implement, but as it starts to get a bit messier, I would pull it out as a separate function, similar to the `row_fisher()` function. One note here is that the CI calculated this way starts from the "corrected" OR, which means that we often end up with an OR that does not include 0, so I would probably set the lower bound value to `min(or_uncorrected, or_lowerbound)`

Another option is to use the `PropCIs::orscoreci()` function, which is probably more accurate (it uses a method from Agretsi), but would involve a more backend work, as it requires adding a new package to the docker image.

**Comment by runjin326** [comment]
@jashapiro, thanks so much for your prompt review -  I would probably take the first approach and ping you for another review when completed.

**Comment by runjin326** [comment]
@jashapiro, I pulled out function for CI and now the results only have one `ci` column with the calculation that you specified. Could you please check to see whether this is what you expect? Thanks!

**Review by jashapiro — COMMENTED** [review]
Hi @runjin326  I saw that some of the intervals were still not making sense, which I think has to do with when the function is being applied. I also modified the code to more accurately reflect the full adjustment as it has to be applied (if `odd_ratio` is zero, you can't take the log, which is part of the reason for this procedure).

I have not tested the code I wrote, but hopefully it works, or does so mostly!

**Comment by runjin326** [comment]
@jashapiro , thanks so much for the detailed review and instructions. I fixed the scripts based on your suggestion - please check to see whether this now looks good.

**Review by jashapiro — APPROVED** [review]
LGTM! I spot checked some of the confidence intervals, and they seem correct to me.

**Pull request merged**
