### PR TITLE
Reuse previously downloaded files in download-data.sh

### LINKED ISSUE #233: Update download script to skip unchanged files in new releases
#### File(s)

download-data.sh

#### Release

v8

#### Question/issue

As we seem to be in a mode of many incremental updates (a good thing!), some of the process (time and disk space) of redownloading data can start to be a bit of a burden for contributors. To increase download efficiency, it might be nice to modify the `download-data.sh` script to check the previous version's folder for unchanged files (by md5sum)' before downloading. If the files are unchanged from a previous version, they could be hard linked (or copied, at the expense of disk space) to the new release folder rather than downloading from S3.

### PR DESCRIPTION
**Pull request by jashapiro**
#### What scientific question is your analysis addressing?

None. But downloads of new releases can be slow, so lets make that quicker when the underlying data hasn't changed.

#### What was your approach?

After downloading the new file list/md5 hashes, check those against the previous release files (if the immediately previous release exists). If the files are found and are unchanged as determined by md5, then *hard* link them into the new release folder. Then continue to download any missing files.

#### What GitHub issue does your pull request address?

Closes #233

#### Which areas should receive a particularly close look?

This is a significant change to the download script, so it should be tested pretty extensively. It seems to work for me on macOS, but it would be good to test other systems as well, as well as combinations of present and absent files that I might not have seen.

Note that I removed `-z` time checks in favor of simple presence checks, as I couldn't think of an instance where a file might exist and be incorrect if the md5 had just been checked. If there is a reason to keep the `-z` check, I  suppose an option would be to `touch` all the hard linked files to set their modification dates as if they had just been downloaded, rather than skipping them outright.

I also added skipping redownload of reference files. These are currently unchecked by md5, but downloading them repeatedly seemed wasteful, as they should never change.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Thanks for doing this @jashapiro! I ran this on Ubuntu just now, both with and without the previous release present, and it behaved as expected/described.

**Comment by cgreene** [comment]
I've got this:
```
Caseys-MacBook-Pro-2:release-v10-20191115 cgreene$ md5sum -c ../$RELEASE/md5sum.txt --ignore-missing
Error: --check <filename> cannot be used with additional files
Caseys-MacBook-Pro-2:release-v10-20191115 cgreene$ echo $PREVIOUS
release-v10-20191115
Caseys-MacBook-Pro-2:release-v10-20191115 cgreene$ echo $RELEASE
release-v11-20191126
Caseys-MacBook-Pro-2:release-v10-20191115 cgreene$
```

For what it's worth, the only downside here is that it does download every file again, which is already the current behavior.

**Comment by jharenza** [comment]
@jashapiro testing on my macbook now and will let you know

**Comment by cgreene** [comment]
The md5sum that I have installed does not support `--ignore-missing`, so that's what the error is referring to.

**Comment by cgreene** [comment]
@jharenza : I suspect you'll need to do the steps from #302 to get things working if you used our previous brew instructions to get md5sum

**Comment by jashapiro** [comment]
> @jharenza : I suspect you'll need to do the steps from #302 to get things working if you used our previous brew instructions to get md5sum

I may actually remove the --ignore-missing flag, as I have to catch the non-zero return code anyway. I think it will work the same without it.

**Comment by jharenza** [comment]
I am on the vardict MAF hump right now (I last had v8 data)... still going.

**Comment by jharenza** [comment]
I updated the download script using your latest edits, @jashapiro but still have mismatches. Should I perform the steps @cgreene recommends? 

`Checking MD5 hashes...
pbta-histologies.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
WXS.hg38.100bp_padded.bed: OK
StrexomeLite_hg38_liftover_100bp_padded.bed: OK
StrexomeLite_Targets_CrossMap_hg38_filtered_chr_prefixed.bed: OK
pbta-snv-mutect2.vep.maf.gz: OK
pbta-snv-strelka2.vep.maf.gz: FAILED
pbta-snv-lancet.vep.maf.gz: OK
pbta-snv-vardict.vep.maf.gz: OK
pbta-cnv-cnvkit.seg.gz: OK
pbta-cnv-controlfreec.tsv.gz: OK
pbta-sv-manta.tsv.gz: OK
pbta-gene-expression-kallisto.polya.rds: OK
pbta-gene-expression-kallisto.stranded.rds: OK
pbta-gene-counts-rsem-expected_count.polya.rds: OK
pbta-gene-counts-rsem-expected_count.stranded.rds: OK
pbta-gene-expression-rsem-fpkm.polya.rds: OK
pbta-gene-expression-rsem-fpkm.stranded.rds: OK
pbta-isoform-counts-rsem-expected_count.polya.rds: OK
pbta-isoform-counts-rsem-expected_count.stranded.rds: OK
pbta-fusion-arriba.tsv.gz: OK
pbta-fusion-starfusion.tsv.gz: OK
independent-specimens.wgs.primary-plus.tsv: OK
independent-specimens.wgs.primary.tsv: OK
independent-specimens.wgswxs.primary-plus.tsv: OK
independent-specimens.wgswxs.primary.tsv: OK
pbta-gene-expression-rsem-tpm.polya.rds: OK
pbta-gene-expression-rsem-tpm.stranded.rds: OK
pbta-isoform-expression-rsem-tpm.polya.rds: OK
pbta-isoform-expression-rsem-tpm.stranded.rds: OK
pbta-fusion-putative-oncogenic.tsv: OK
pbta-gene-expression-rsem-fpkm-collapsed.polya.rds: OK
pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds: FAILED
pbta-snv-consensus-mutation-tmb.tsv: OK
pbta-snv-consensus-mutation.maf.tsv.gz: OK
md5sum: WARNING: 2 of 39 computed checksums did NOT match`

MAC OSX MOJAVE

**Comment by jashapiro** [comment]
> I updated the download script using your latest edits, @jashapiro but still have mismatches

Those seem like they are likely download failures unrelated to the changes in the script. Delete those files and try running it again?

**Comment by jharenza** [comment]
that worked, all good now!

**Pull request merged**
