### PR TITLE
readme on how coverage was calculated using gencode and TCGA agilent BED

### PR DESCRIPTION
**Pull request by tkoganti**
**Purpose -** 

**What scientific question is your analysis addressing?**
Got a new BED file for TCGA BAMs and created coverage comparison between old(gencode) and new BED 
Also, counted #of SNVs with new and old BED intersection

**What was your approach?**
When you calculate #of bases higher than 20x in old and new, if there is lower coverage in old BED, then we can suggest that `gencode` might not be the correct BED (that we used previously)

What GitHub issue does your pull request address?
TCGA TMB values 

**Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Which areas should receive a particularly close look?**

1)How I got the new BED file for TCGA BAM files (this is covered in readme_overallsummary.txt)
Calculate the coverage in two samples(as an example, this will be expanded to 160 samples) 
2) Two BED files that were used were - 
   i) gencode.v19.basic.exome_withchr_Gh38_sorted_merged.bed
     (This was generated by using online liftover tool and sorted and merged using bedtools)
   ii) whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals.liftover_Gh38.bed
     (This was generated from querying TCGA site with the TCGA BAM file case ID. Then using online liftover tool, I converted hg19 to Gh38)
The process for this is covered in (readme_howsamples_were_matched_to_UUID_and_BEDfile.txt. and readme_coverage.txt)
         Coverage was calculated for BAM using each of the above BED files(using samtools depth) and any total number of bases with more than 20x were calculated for final numbers 

3) Number of SNV's for each sample were calculated for TCGA and PBTA (using three SNV callers - mutect2, strelka2 and lancet)
(Look at python notebook counting_var.ipynb)

**Results**
Look at this file for coverage - coverage_results_comparingBEDs_twosamples.txt
And file ending with *counting_SNV_numpersamples.txt for # of SNVs under each variant caller category for PBTA and TCGA

### CODE REVIEW

**Comment by yuankunzhu** [comment]
@tkoganti for `gencode.v19.basic.exome_withchr_Gh38_sorted_merged.bed`, this file, is it still padded or not?

**Comment by yuankunzhu** [comment]
@tkoganti for this file `gencode.v19.basic.exome_withchr_Gh38_sorted_merged.bed`
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/570/files#diff-40696224a82788c5ae755260a61d73b4, did we add the padding or not?

**Comment by tkoganti** [comment]
> @tkoganti for `gencode.v19.basic.exome_withchr_Gh38_sorted_merged.bed`, this file, is it still padded or not?

This is not padded. I wanted to compare non-padded for both for consistency

**Comment by tkoganti** [comment]
We are tracking this issue here (https://github.com/d3b-center/D3b-codes/blob/feat/openpbta-tmb-analysis/OpenPBTA_TMB_analysis/README.ipynb) and when we have organized all the files that need to be pushed to OpenPBTA, we will create a new PR for TMB

**Pull request closed without merging**
