### PR TITLE
#953 Part1: Gather TP53 SV breakpoints with gene loss

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Are there SV breakpoints in/overlapping TP53 gene locus that might support the TP53 loss phenotype?

#### What was your approach?
I gathered SV breakpoints that overlap or are within TP53 gene locus by searching for TP53 in the `Gene.name` column in the annotSV formatted manta calls in `pbta-sv-manta.tsv.gz`. Then as a secondary support for TP53 loss status I looked for loss of copy_number in `loss_overlap_domains_tp53.tsv` from a previous step and also if the SV breakpoint is associated with a `1<FPKM` expression 

#### What GitHub issue does your pull request address?
#953 

#### Which areas should receive a particularly close look?
- I used INV,DEL and BND mainly because I wanted to check if any breakpoint within/overlapping TP53 will also associate with loss in CNV or low expression. Seems like it's not the case, so I can update it to DEL only if that seems like a more clear filtering for this analysis.

#### Is there anything that you want to discuss further?
BS_3NX3RBCX and BS_EJV0N3BX have a CNV loss and multiple SV breakpoints overlapping TP53 locus, and most of them are quite long 4034301 to 15772588 bp. DO we need a SV.length filter and since we already capture it in CNV do we want to add to these to the classifier evaluation which is the next step ?
The longest ovelaps a large chunk of chr17p arm
Screen Shot 2021-03-18 at 6 44 12 PM

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
sample_id 7316-114 and 7316-2217 have multiple breakpoints associated CNV loss

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@kgaonkar6 Thank you for this analysis! 

>I used INV,DEL and BND mainly because I wanted to check if any breakpoint within/overlapping TP53 will also associate with loss in CNV or low expression. Seems like it's not the case, so I can update it to DEL only if that seems like a more clear filtering for this analysis.

I think this is the correct thing to do, especially if a breakpoint were to result in a translocation that removes most of the TP53 gene after the start site such that a functional protein is not translated, so I think we can keep this as is. 

>BS_3NX3RBCX and BS_EJV0N3BX have a CNV loss and multiple SV breakpoints overlapping TP53 locus, and most of them are quite long 4034301 to 15772588 bp. DO we need a SV.length filter and since we already capture it in CNV do we want to add to these to the classifier evaluation which is the next step ?

I think that SV length will vary too much to use a filter at this moment in time and that it is not necessary to implement right now.

>sample_id 7316-114 and 7316-2217 have multiple breakpoints associated CNV loss

At first I thought, GREAT! But, then I was thinking about how we derived consensus CNV calls in the first place, and one of the tools used is MantaSV, so I think this result makes total sense. That being said, I do not think we can necessarily call the SV and CNV events as unique, as I may have originally planned. The SV breakpoint is more likely resulting in CN loss of the same copy of the gene, rather than the SV breakpoint occurring on one copy and the CNV on another copy. So, it seems that for `BS_3NX3RBCX`, we only have evidence of one hit thus far (SV/CNV being considered one hit), which aligns with the lower _TP53_ score of `0.3218202`. For `BS_EJV0N3BX`, that sample was already annotated as `TP53_altered == loss` since it contains a hotspot SNV and a CNV, and its _TP53_ score is high.

I think since we have the information, we could create a new column to the `tp53_altered_status.tsv` file annotating the presence of an SV, but we will need to be sure that if `CNV_loss_counts == 1` & `SV_counts` == 1, that we do not count them as unique events when determining `tp53_altered` status. Once you add this column and account for the calculation, then we can merge this!

**Review by jharenza — CHANGES_REQUESTED** [review]
See my comments!

**Comment by kgaonkar6** [comment]
Should I add another PR for adding the `SV_counts` column  since the code to create tp53_altered_status.tsv is a different script?

**Comment by jharenza** [comment]
I would say it's within the scope of this one, so you can add here.

**Review by jharenza — APPROVED** [review]
Great - logic looks good and the expected results occur.

**Pull request merged**
