### PR TITLE
SV analysis

### PR DESCRIPTION
**Pull request by yangyangclover**
#### What scientific question is your analysis addressing?
1. structural variations analysis
2. chromothripsis analysis
3. decipher signatures of structural variations
4. to understand the potential mechanism behind tumors through structural variations analysis

#### What was your approach?
Files: 
SV file and CNV file

Tools:
Shatterseek: to find out the chromothripsis in tumorigenesis.
NMF algorithm: to extract SV signature

#### What GitHub issue does your pull request address?
issue 27

#### Which areas should receive a particularly close look?
1. chromothripsis analysis
2. signatures of structural variations
3. mechanism interpretation
4. further study
5. any advice is welcome

#### Is there anything that you want to discuss further?
CNV file is needed for chromothripsis classification, however, the CNV files generated from cnvkit and freecontrolc are little different, we hope there will be a consistent CNV file.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Not yet. 

#### What types of results are included (e.g., table, figure)?
figures

#### What is your summary of the results?
1. Figure  "SV proportion" is about the different SV (TRA,  INV, DEL, TRA)  proportion in samples, samples are sorted by tumor type and total SV  number. Tumors that sample number is <10 are classified as "others".  
2. Figure "SV number across tumors"  shows the total number of SV, including chromothripsis.
3. Figure “SV chromothripsis percentage”  is about the proportion of chromothripsis sample. Chromothripsis sample is the sample with one or more Chromothripsis event.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover, I will mark this pull request with our `work in progress` label until you include the code. Once you have uploaded the code and say that this is ready for review, I can mark it as such and request a reviewer. 

The copy number consensus calls are tracked here on this issue: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/128  Please feel free to post any questions about the consensus CNV file format on that issue. 

I am happy to answer any questions about the pull request here. Thank you!

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni , I have uploaded the codes just now. They are ready for review. Thank you very much.

**Comment by cgreene** [comment]
@yangyangclover - you removed these two checkboxes:

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

Please do those to get your code ready for review. They will help to catch issues that are otherwise difficult to spot. There are instructions in the README: https://github.com/alexslemonade/openpbta-analysis#docker-image

Thanks!

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover, thank you for adding the code to this pull request. Now that I've seen the size and scope of the code required to produce the plots from the data included in the download, I think it would be best to split this up into multiple pull requests, where each pull request is composed of a single script per the [**Size and composition of pull requests** section](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#size-and-composition-of-pull-requests) of the contributing guidelines.

This is needed to ensure that each script is reviewed properly and all dependencies are included in the project Docker container. The other benefit is that allows you to document what scientific or architecture decisions were made around each step in the pull request template.

Here is how I would recommend splitting this up into multiple pull requests:

1. Adds `analyses/structural-variation-signature/01-process-sv-file.R`. No changes to the `Dockerfile` are likely required because `stringr` is already on the project Docker image.

2. Adds `analyses/structural-variation-signature/02-shatterseek.R`. This pull request will also need to add installation of the `ShatterSeek` package to the Docker image by altering the `Dockerfile`.

3. Adds `analyses/structural-variation-signature/03-plot-chromthripsis-and-cnv-figure.R`. All packages loaded with `library` in that script are already on the Docker container.

4. Adds `analyses/structural-variation-signature/04-plot-sv-distribution-and-chromothripsis-percentage.R`. This pull request will also need to include installation of `Rmisc` and `randomcoloR`. I think everything else explicitly loaded is already on the Docker image. Plots will also get added in this pull request because they are output from this script.

Each of this pull requests will require you or a project organizer to add the script being added to continuous integration ([documentation](https://github.com/AlexsLemonade/OpenPBTA-analysis#continuous-integration-ci)). Instructions for the Docker steps were linked above by @cgreene.

I wanted to note that it is possible to file each of these at the same time from different branches in your fork of the repository. I noticed that this pull request is coming from your master branch. When you close this pull request to split things up, I would recommend either deleting your fork of the repository and starting a new one or resetting your master branch to the upstream AlexsLemonade version (see [this StackOverflow post](https://stackoverflow.com/questions/42332769/how-do-i-reset-the-git-master-branch-to-the-upstream-branch-in-a-forked-reposito)). 

You can then create a new branch from your master branch, add the relevant changes, and file a pull request. You can repeat that process 4x, one time for each script. See [**Filing a pull request from your own branch** in the contributing guidelines](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#filing-a-pull-request-from-your-own-branch) for some more information around this procedure.

If you have questions about any part of this process, please feel free to post them here on this pull request, to [file a new issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/new), or to [join the project Slack channel](https://github.com/AlexsLemonade/OpenPBTA-analysis#join-the-cancer-data-science-slack) and ask there. Thank you!

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni , thank you for your information. I will learn how to do these as you advised. I appreciated your help.

**Comment by yangyangclover** [comment]
@jaclyn-taroni I started a new pull request, I think we can close this one.

**Comment by jaclyn-taroni** [comment]
Great, thank you @yangyangclover! I agree that we can close this. I will do that now. Looking forward to having a discussion over on #283

**Pull request closed without merging**
