### PR TITLE
Beginning updates to ssGSEA hallmark analysis

### PR DESCRIPTION
**Pull request by sjspielman**
### Purpose/implementation Section

This analysis aims to be an updated version of the current analysis module `ssgsea-hallmark`. It has two primary goals:

1. Address Issue #235 by using the more up-to-date gene expression data
2. Re-factor and debug the code more generally for style and reproducibility.

#### What scientific question is your analysis addressing?

Analysis seeks to perform ssGSEA analysis on RNA-seq expression data to score hallmark pathways. This will both provide ssGSEA data for other downstream analyses. The ssGSEA data itself will also be analyzed in forthcoming PRs.

#### What was your approach?

Incorporate `tidy` data principles and re-factor existing code.

#### What GitHub issue does your pull request address?

Issue #235, at least

#### Which areas should receive a particularly close look?

Review from @jharenza , @komalsrathi , and @jaclyn-taroni requested:

+ Is the code in `01-conduct-ssGSEA-analysis.Rmd` reasonable? Several changes were made from the original script in `ssgsea-hallmark/01-run-ssgsea.R` including:
     + We now load the `msigdbr` package to obtain hallmark pathways and associated genes
     + Code abides by tidy principles and improved structure, including paths in the repository
     + The actual analysis performed is now actually ssGSEA instead of GSAV.
     + **NOTE** this Rmd files takes 5-10 minutes to knit due to the computations performed for ssGSEA. Maybe it should be an R script and not Rmd?

+ Does the code in `02-model-ssGSEA-results.Rmd` feel like a reasonable starting point for modeling and other analyses to do on ssGSEA results?
    + Need someone to weigh in regarding multiple testing corrections. This script performs a series of Tukey Tests but there is currently no correction for the fact that *50 Tukey tests were run on the same data*

#### Is there anything that you want to discuss further?

What exactly did I do wrong here to have all my commits in my repo as part of this PR? I tried very hard to start my branch off of the ALSF master but alas, you now get to see _all my changed files_. @jaclyn-taroni please send help :/

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Nope.

#### What types of results are included (e.g., table, figure)?

A single file of results is produced: `results/ssGSEA_scores.tsv`, which contains the scores across all biospecimen IDs.

#### What is your summary of the results?

They are mostly forthcoming.

#### Reproducibility Checklist

*Reproducibility items have NOT been performed at this time* - I'm seeking further clarification on at which point in an analysis life this should be done? Is now the time? 

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.
- [ ] This analysis is recorded in the table in `analyses/README.md`.

### CODE REVIEW

**Comment by sjspielman** [comment]
Thanks @komalsrathi for your reply in Issue #235   - 
If it's indeed the case that we are planning to use gvsa, the analysis directory and any associated documentation should be changed. @cgreene and @jaclyn-taroni, do you have any objections to this or further thoughts?

I'm also thinking there should be a command line argument for `parallel.sz` for individual users to set to their computer specs, but keep a default at 1.

**Comment by jaclyn-taroni** [comment]
@sjspielman your master branch appears to be ahead of the AlexsLemonade master branch: https://github.com/sjspielman/OpenPBTA-analysis/tree/master Generally speaking, you only want to update your master branch by merging the upstream AlexsLemonade master branch into yourself and then your feature (e.g., pull request) branches should come off of your master branch. 

As far as what to do here, I might reset your master to be in sync with the AlexsLemonade master (see: https://github.community/t5/How-to-use-Git-and-GitHub/Syncing-a-fork-leaves-me-one-commit-ahead-of-upstream-master/td-p/13555), create a new branch off of master, and cherry pick (https://www.devroom.io/2010/06/10/cherry-picking-specific-commits-from-another-branch/) the relevant commit for this pull request (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/368/commits/75e2f6c6e2d72b25dc6570561cdc9740da815ac0). Then you can close this PR and open a new one with just the relevant changes. 

I would copy the updated files somewhere safe outside of the repository before attempting this myself 🙂

**Comment by jaclyn-taroni** [comment]
GSVA sounds good to me and I agree that the module name and documentation should be changed (it could perhaps be _more general_, i.e., something like gene set analysis). Outside of the folder name and the README you're adding, here's what else I know should change:

* The `ssgsea-hallmark` entry for https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses#modules-at-a-glance
* This subsetting step in `molecular-subtyping-ATRT`: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/066378fa32b6f0f509599bf7ac6480c267865b55/analyses/molecular-subtyping-ATRT/00-subset-files-for-ATRT.R#L43
* The `molecular-subtyping-ATRT` entry in the modules at a glance table

**Comment by cgreene** [comment]
I also do not have strong feelings on ssGSEA vs another approach so what you've done sounds good. Whatever we do here will be complemented by MultiPLIER's #4 so that will be a good opportunity to examine consistency.

**Comment by sjspielman** [comment]
Closing and opening new PR with a better branch.

**Pull request closed without merging**
