### PR TITLE
Third comparison script

### PR DESCRIPTION
**Pull request by NNoureen**
### Purpose/implementation Section
The analysis is focused on identifying telomerase activities using gene expression data sets processed in different ways, to identify platform differences and compare the telomerase activities across different tumor histologies.

#### What was your approach?
We used our newly developed method EXTEND (Expression based Telomerase ENzymatic activity Detection).

#### What GitHub issue does your pull request address?
Issue # 148 (Quantify telomerase activity across pediatric brain tumors)

#### Which areas should receive a particularly close look?
We would like the reviewers to provide us directions for further comparisons regarding telomerase activities if required.
#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES
#### What types of results are included (e.g., table, figure)?
Predicted Telomerase activity scores as tables and comparisons as figures.
#### What is your summary of the results?
Results include text files containing telomerase activities across different expression data formats. The comparison of telomerase activities has been carried out with different parameters as:
1.	Variations in telomerase activities across different expression data formats.
2.	Comparison of telomerase activities with TERT and TERC genes expression for different data sets.
3.	Distribution of telomerase activities across different pediatric brain tumor histologies.

#### Documentation Checklist

This analysis module has a `README` and it is up to date.
This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
The analytical code is documented.

### CODE REVIEW

**Comment by NNoureen** [comment]
Sure. I will update the READ.md for figures information. Thanks

**Comment by sjspielman** [comment]
Hi @NNoureen, great thanks for filling in the README. I went ahead and make a couple changes: first I reformatted your file names to be in markdown format linking to the files themselves, and I removed the reference to the script `Analysis-telomerase-activity.sh` which does not exist - if you believe this script _should_ exist let me know. Then, we can go ahead and head towards merging this in.

**Comment by NNoureen** [comment]
Yeah that's perfect. Sorry I forgot to remove Analysis-telomerase-activity.sh from READ.md. Obviously there is no need for it. We can proceed for merging then. Thanks a lot for your great help.

**Comment by sjspielman** [comment]
No worries, this one's all set!

**Comment by NNoureen** [comment]
Thanks

**Pull request merged**
