### PR TITLE
V20 PBTA histologies: Add cancer group

### PR DESCRIPTION
**Pull request by kgaonkar6**
Merge after #1127 

#### What scientific question is your analysis addressing?
Add cancer_group which can be used in generating plots

#### What was your approach?
We use harmonized_diagnosis and generate a cancer group by removing the subtypes and providing a broader name to the diagnosis.

#### What GitHub issue does your pull request address?
#917
#1048 

#### Which areas should receive a particularly close look?
Do the matching of harm_dx to cancer_group look good? Related discussion https://github.com/PediatricOpenTargets/ticket-tracker/issues/48

#### Is there anything that you want to discuss further?
Na

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
tables

#### What is your summary of the results?
Added cancer_group to histologies table.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
`cancer_group` looks as expected

**Comment by jaclyn-taroni** [comment]
@jharenza can you take another look at `analyses/molecular-subtyping-integrate/results/pbta-histologies.tsv` locally now that I've resolved the conflicts? I think it's all good with https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1128/commits/99f82ccb0eaeb906c6f6b54c638eb5e09f0588c6 but just to double-check before merging. If it looks good, please feel free to merge this and update #1118, thanks!

**Comment by jharenza** [comment]
> @jharenza can you take another look at `analyses/molecular-subtyping-integrate/results/pbta-histologies.tsv` locally now that I've resolved the conflicts? I think it's all good with [99f82cc](https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/99f82ccb0eaeb906c6f6b54c638eb5e09f0588c6) but just to double-check before merging. If it looks good, please feel free to merge this and update #1118, thanks!

on it

**Comment by jharenza** [comment]
This looks good to me and @kgaonkar6 has already updated s3. So I will merge this.

**Pull request merged**
