### PR TITLE
Update 1B and recompile Figure 1

### LINKED ISSUE #1482: Re-compile Figure 1
With the merge of #1456, Figure 1 needs to be re-compiled to use the updated panel.

### LINKED ISSUE #1517: Update Figure 1B with new abbreviations
Cancer group abbreviations need to be updated for HGG and LGG (see #1516), which means Figure 1B will need to be re-run.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #1517 and closes #1482

This PR updates Figure 1B to use correct abbreviations _and_ re-compiles Figure 1. Additional code changes were included to re-size 1B for ease of compilation in 3rd party app. I also took this opportunity to update the `figures/README.md` file to indicate the Graphic for Mac app is used for compiling, not Illustrator. Internally, Illustrator is sometimes used for re-sizing individual panels, but the final compiled figures are all in Graphic format (extension `.idraw`). These files can be opened with Illustrator too!

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
@sjspielman I am not sure why, but it looks like ATRT is cut off in the compiled figure. It is there in the original panel, so may need an update here.

**Comment by jharenza** [comment]
Oh, shoot - I think that "ET" also needs a rename to "Other ET" as well, in the palette. :(

**Comment by sjspielman** [comment]
Ah, my bad with ATRT, angled text behaves poorly in third party apps. Will fix that! I'll have a look at "Other ET" as well. If we have a separate issue for it I think it's fine to fix here.

**Comment by sjspielman** [comment]
This PR now closes #1522.

**Review by jharenza — APPROVED** [review]
👍

**Pull request merged**
