### PR TITLE
shatterseek

### PR DESCRIPTION
**Pull request by yangyangclover**
### Purpose/implementation Section
analyze chromothripsis, using modified shatterseek code

#### What scientific question is your analysis addressing?
Chromothripsis events in PBTA data

#### What was your approach?
modified shatterseek code

#### What GitHub issue does your pull request address?
[393](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/393)

#### Which areas should receive a particularly close look?
Test and Filter The Combined Results
Call Linking Groups

#### Is there anything that you want to discuss further?
we will describe the Chromothripsis Distribution across samples and different tumor types；
we will perform simple SV (SVs that are not in Chromothripsis regions) signatures analysis

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
A table called "PBTA_chromothripsis_newlink_region.csv" will be saved in "analyses\sv-analysis\tables\sv-shatterseek" folder, which is about the chromothripsis regions were founded in our dataset.

#### What types of results are included (e.g., table, figure)?
A table called "PBTA_chromothripsis_newlink_region.csv" will be saved in "analyses\sv-analysis\tables\sv-shatterseek" folder, which is about the chromothripsis regions were founded in our dataset.
We will use it in the following study.

#### What is your summary of the results?
the chromothripsis regions were founded in our dataset

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni, this RP is about the chromothripsis analysis using a modified shatterseek package.
Due to the reason that our related article hasn't been published yet, I ignored the R code "02-shatterseek.R" for the moment. I don't know if reviewers can see it. But I can keep it open for review if needed.

**Comment by jaclyn-taroni** [comment]
Hi @yangyangclover,

Reviewers are unable to see and review `02-shatterseek.R` because, as you stated, it has been added to the `.gitignore` file. One of the goals of the project is to have the analysis results be fully reproducible. If we are unable to include the analytical code downstream of the OpenPBTA files in this repository, we can not include the results from that code.

As an aside - the ShatterSeek step of continuous integration would always fail because the machine running the continuous integration would not be able to find the `analyses/sv-analysis/02-shatterseek.R` file.

If you are uncomfortable including the modified ShatterSeek code in this repository before the modified method is published, I might suggest submitting results and code that uses the _unmodified_ ShatterSeek package for now. If that's done very soon, those results can be included in the initial draft of the [OpenPBTA manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/). You then can update your analysis to use the modified package when it becomes available for public release and those results could potentially be included in a revision or update of the manuscript. Taking the unmodified now, modified later approach will essentially mean that this repository will have a record of the results with and without your modifications and that could be a very valuable example for people who would like to use your method.

I am happy to chat more privately via the [Cancer Data Science Slack](http://ccdatalab.org/slack) or email if you'd like. Thanks!

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni, thank you for your reply.
I wonder if we can release the code for review and continuous integration temporarily, after that, keep the output open (eg. put the output file in a folder for subsequent analysis) but ignore the code.

**Comment by cgreene** [comment]
@yangyangclover : we can't do that. A major point of this project is to produce reusable workflows for these analyses. There are some options:
1. Use standard, unmodified shatterseek as @jaclyn-taroni suggests.
2. Submit a shatterseek preprint to something like bioRxiv and use the code here.
3. Drop the analysis from the planned work.

Any of these seem like they could work. I'm not sure which path forward is most compatible with what you'd like to see though.

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni  and @cgreene，thank you for your suggestions.
After a discussion, we think we can make it open, I am going to resubmit the RP tomorrow, thank you for your patient.

**Comment by jaclyn-taroni** [comment]
@yangyangclover sounds good! I'm going to close this pull request so you can submit a new one. I'm going to provide some pointers for opening that new pull request below.

The branch that you have filed this pull request from is called [`process-sv-file`](https://github.com/yangyangclover/OpenPBTA-analysis/tree/process-sv-file). This is the same branch name as the earlier pull request you filed and merged (#283). In my experience, not creating a new branch with a different name when I implement something new (here you are adding a new script) can cause some unintentional things to happen. The other thing I notice about [your branch](https://github.com/yangyangclover/OpenPBTA-analysis/tree/process-sv-file) is that `This branch is 75 commits ahead, 5 commits behind AlexsLemonade:master.`

When you go to file your new pull request, here are the steps I recommend.

#### Updating your master branch to be in sync with the AlexsLemonade master branch.

You can do that by first checking that you have set the AlexsLemonade repository as an upstream repository by running the following command in the root directory of this repository: `git remote -v`. If you have set this up, it will look like:

```sh
$ git remote -v
origin	https://github.com/yangyangclover/OpenPBTA-analysis.git (fetch)
origin	https://github.com/yangyangclover/OpenPBTA-analysis.git (push)
upstream	https://github.com/AlexsLemonade/OpenPBTA-analysis.git (fetch)
upstream	https://github.com/AlexsLemonade/OpenPBTA-analysis.git (push)
```
If this is not what is returned, you'll need to set this up by following the directions at: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork -- `git remote add upstream https://github.com/AlexsLemonade/OpenPBTA-analysis.git` is the command that you want.

Then you're ready to sync your master branch with:

```
# fetch the changes from the AlexsLemonade repository
git fetch upstream

# checkout your own master branch
git checkout master

# merge the upstream/master branch into your own master branch
git merge upstream/master

# push the changes to your master branch to the remote repository
git push
```

([These instructions are from the contributing guidelines](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#filing-a-pull-request-from-your-own-branch)).

#### Create a new branch that is named to reflect what you are adding.

Now that your master branch is up-to-date, I'd recommend creating a new branch via the GitHub interface. Here's what the GitHub interface looks like when my master branch is up to date with the upstream master branch:

master-uptodate

If you click the branch dropdown menu that's above where it says that your branch is even with AlexsLemonade master in that screenshot, you can start typing the new branch's name (I'd recommend something like `add-shatterseek`) and then click where the dropdown menu says `Create-branch: <new branch name> from 'master'` to create the new branch off of master.

#### Add your changes to the new branch.

I'm going to assume you called the new branch `add-shatterseek` for simplicity below. 

Check out the new branch locally via the command line by using the following commands in the root directory of the repository:

```
git fetch
git checkout add-shatterseek
```

You're ready to add and commit changes - here are instructions for adding a file to a repository using the command line for your reference: https://help.github.com/en/github/managing-files-in-a-repository/adding-a-file-to-a-repository-using-the-command-line - then push your changes and file a pull request via the GitHub interface like you have in the past.

If you encounter problems with these any of these steps, don't hesitate to reach out! Thanks!

**Comment by jaclyn-taroni** [comment]
One thing I forgot to add - please be sure to Allow edits from maintainers. That will let organizers sync the branch with the AlexsLemonade master branch which is a requirement for merging.




([Image from GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).)

**Comment by yangyangclover** [comment]
Hi @jaclyn-taroni 
I tried 
```
yangy@DESKTOP-B42A76E MINGW64 /d/Yang/Documents/GitHub/OpenPBTA-analysis (master)
$ git fetch upstream

yangy@DESKTOP-B42A76E MINGW64 /d/Yang/Documents/GitHub/OpenPBTA-analysis (master)
$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

yangy@DESKTOP-B42A76E MINGW64 /d/Yang/Documents/GitHub/OpenPBTA-analysis (master)
$ git merge upstream/master
Already up to date.

yangy@DESKTOP-B42A76E MINGW64 /d/Yang/Documents/GitHub/OpenPBTA-analysis (master)
$ git push
Everything up-to-date


```
but my page still shows as below,
image

I don't know how can I remove those commits, which makes me confused. Can you please give me some suggestions? Thank you so much!

**Comment by jaclyn-taroni** [comment]
So it looks like your master branch is ahead of AlexsLemonade. I would copy any files you've recently changed to somewhere outside your repository for safe keeping at the moment because what I am about to suggest will likely overwrite those changes. You want to follow the accepted answer from https://stackoverflow.com/questions/42332769/how-do-i-reset-the-git-master-branch-to-the-upstream-branch-in-a-forked-reposito Using the `--hard` flag means that local changes will get overwritten. Following these steps will make it such that your branch is synced with and not ahead of the AlexsLemonade master. As a rule, you generally do not want to commit anything to your master branch.

**Comment by yangyangclover** [comment]
I see! It works! Thank you @jaclyn-taroni

**Pull request closed without merging**
