### PR TITLE
Update S7 

### LINKED ISSUE #1733: Figure S7 re-compile
I just noticed Figure S7A has the word "Lo" in the bar of the SEGA cancer group. Probably a compilation thing.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #1733 

Removes the weird "Lo" from the sega bar!

### CODE REVIEW

**Comment by jharenza** [comment]
ooop - now the bar is missing its outline 😬

**Comment by sjspielman** [comment]
Ah good catch!! 2 min..

**Review by jharenza — APPROVED** [review]
👍

**Comment by sjspielman** [comment]
No code in this PR; merging before checks complete.

**Pull request merged**
