### PR TITLE
PR 6 of n - Molecular Subtyping - HGG (Cleaning CNV data) 

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
### Purpose/implementation Section

Per https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/420#issuecomment-573257980, this pull request is adding a notebook that cleans the relevant copy number data for the purposes of subtyping HGG samples.

Here I've elected to use a notebook in the interest of documenting the decisions made here and in the file preparation that happens upstream of this notebook itself.

*View the rendered notebook here: https://jaclyn-taroni.github.io/openpbta-notebook-concept/03-HGG-molecular-subtyping-cnv.nb.html*

#### What GitHub issue does your pull request address?

#249 

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

Because this depends on #426, you will see those changes in this branch. For the moment, here is where I would like you to direct your attention:

| File | Description | Relevant Commit(s) |
|-----|-------------|---------------------|
| `analyses/molecular-subtyping-HGG/03-HGG-molecular-subtyping-cnv.Rmd` | Notebook for cleaning CNV data | https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/f846d20d0289b47904dd5f16f0ea5de2f537f8b3, https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/427/commits/c3005bfeab3e263dae809f9de09716997418d9bc, https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/427/commits/1408905bba5bf4eaa8dd5c50ceafc7539240ef51 |
| `analyses/molecular-subtyping-HGG/run-molecular-subtyping-HGG.sh` | Shell script for running analysis module | https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/9f7efde72abe531b025f265963d57771ff69f71f |
| `analyses/molecular-subtyping-HGG/results/HGG_cleaned_cnv.tsv` | Output table | https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/f846d20d0289b47904dd5f16f0ea5de2f537f8b3, https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/427/commits/d2784aa9ecf1eb1965da6be25f8e50a9d62b3a69, https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/427/commits/614ca962dbad079d721d070f590c1527302bd188 |

#### Which areas should receive a particularly close look?

Is there a more elegant solution for the focal copy number (annotated CNVkit data) steps? Tagging @sjspielman to weigh in because she is in the trenches of #251.

#### Is there anything that you want to discuss further?

I'm summarizing the GISTIC `broad_values_by_arm.txt` into `loss`, `gain`, and `neutral` rather than retaining the integer values -- are we getting too far away from the data with that choice?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

No, but please look at the intermediate product.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date. (See: #426) 
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Marking as ready for review -- the `Jump to` feature + the table of which files to look at will hopefully make this more manageable.

**Comment by sjspielman** [comment]
@jaclyn-taroni, are you specifically looking increase code efficiency to reach the final `genes_cn_df` tibble?

**Comment by jaclyn-taroni** [comment]
> are you specifically looking increase code efficiency to reach the final `genes_cn_df` tibble?

@sjspielman Yes, exactly that!

**Comment by sjspielman** [comment]
Q2: Is there a good reason to keep _multiple_ statuses as strings in a single row, e.g. things like "amplification, gain"? In my mind, it's cleaner to have this as two (or more as needed) rows, but as needed I can keep as two.

**Comment by jaclyn-taroni** [comment]
> Q2: Is there a good reason to keep multiple statuses as strings in a single row, e.g. things like "amplification, gain"? In my mind, it's cleaner to have this as two (or more as needed) rows, but as needed I can keep as two.

Though I agree that it may cleaner, we are ultimately going to present someone with a lot of information in a table where each sample (likely `sample_id` in the _final_ table) is its own row.

**Comment by sjspielman** [comment]
> Though I agree that it may cleaner, we are ultimately going to present someone with a lot of information in a table where each sample (likely sample_id in the final table) is its own row.

Ok, cleaner isn't always better! Depends on the goal. One row it is!

**Comment by jaclyn-taroni** [comment]
@sjspielman I noticed that we were not including samples that had no alterations in any of the three genes of interest (that was my fault). So I reordered when you generate the IDs `data.frame` and used a right join in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/427/commits/97356fc5ead71de57d809cb09ca279ac6074421c. Also a handful of samples failed GISTIC QC, so wanted to indicate that here! Let me know what you think.

**Comment by sjspielman** [comment]
Looks right to me!

**Comment by jaclyn-taroni** [comment]
teamwork

**Pull request merged**
