### PR TITLE
Tp53 loss status update: bug fix

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
TP53 loss status was incorrectly coded in the previous PR where we converted some columns to binary but I didn't propogate the changes in the code correctly. I've now updated lines which caused the bug.

#### What was your approach?
Updating #922 to
 - replace NA with 0 only when merging the hotspot/activating status with the full histology 
 - correctly summarizing and coding the conditions in TP53 status assignment chunk.

#### What GitHub issue does your pull request address?
#837 

#### Which areas should receive a particularly close look?
The summarizing binary status of hotspot/activating from SNV/indels is currently set as 1 if any SNV/indel is in hotspot and 0 if non of the multiple SNV/indels are in hotspots to keep it binary. 
Or should it be comma separated as 1,0 is `HGVSp_Short=X,Y` and X overlaps a hotspot and Y doesn't? 

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?

```r
tp53_alterations_score_wide$tp53_altered %>% table()
activated      loss     Other 
       23       136       971 
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
Thank you @kgaonkar6 ! The fix looks good. I just have one comment - For `Check if other cancer predisposition have high TP53 inactivation scores` display in the HTML file looks very smushed - is it rendering that way on your end as well? Maybe a rerun and save of the HTML would fix?

**Comment by kgaonkar6** [comment]
> Thank you @kgaonkar6 ! The fix looks good. I just have one comment - For `Check if other cancer predisposition have high TP53 inactivation scores` display in the HTML file looks very smushed - is it rendering that way on your end as well? Maybe a rerun and save of the HTML would fix?

Thanks for the review @jharenza! I added larger size param in each of the chunks to enlarge the plots.

**Review by jharenza — APPROVED** [review]
looks good now, thank you!

**Comment by jharenza** [comment]
I am going to merge this quick bug fix.

**Pull request merged**
