### PR TITLE
Draft PR: SNV Caller Comparison Notebook

### PR DESCRIPTION
**Pull request by cansavvy**
### Purpose/implementation

After my initial series of PRs with scripts to assess snv callers individually, this PR adds the notebook which takes that initial analysis and compares the snv callers to each other. 

The eventual goal is to decide on a set of mutations from these callers that we can move forward with. 

*Two things to keep in mind about the current notebook/PR:*
1) This is only the subset of the data being shown currently, so it will have a lot more data later. This will affect aesthetics of the plots as well as memory requirements to run it. 
2) I haven't written up results/conclusion yet since we are still missing data and I have only run this on a subset of the data. 

### Issue

For SNV caller comparison #161, #103 and Tumor Mutation Burden #3 and sort of #11

### Directions for reviewers

_I'm looking for an initial "broad strokes feedback" about the plots and analyses:_
You can see the output notebook here to evaluate my initial questions: https://cansavvy.github.io/openpbta-notebook-concept/snv-callers/compare_snv_callers.nb.html

**Some questions for this PR:** 
Which plots are useful? Which are not? 
What do you think of the current analyses? 
Are there other analyses you would like to see added? 
How do you feel about the plots' aesthetics? 

### Results

See the rough draft of this notebook output from this notebook here: https://cansavvy.github.io/openpbta-notebook-concept/snv-callers/compare_snv_callers.nb.html

**Preliminary conclusion:**
From just the subset data it looks like VarDict should be dropped and we could move forward with mutations that are found in Mutect2, Strelka2, and Lancet. 

But, we should see how this looks after the v6 data come out and the rest of the samples are added. As of now, we do not have WXS samples for Lancet or VarDict.

#### Docker and continuous integration

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
Main _RPackages added to the Dockerfile:_
- UpSetR
- GGally 
- ggupset
- [x] This analysis has been added to continuous integration.

* [x] Run a linter
* [ ] Set the seed- I didn't, but let me know if I should.
* [ ] Comments and/or documentation up to date *- I will add more comments but after we figure out which plots we are keeping*
* [x] Double check your paths
* [x] Spell check any Rmd file or md file
* [x] Restart R and run all notebooks fresh and save

### CODE REVIEW

**Comment by cansavvy** [comment]
I’m thinking that the memory intensive-ness of the genomic regional analysis is not paying off for the results and maybe its a thing better for after we have the consensus set? What do you think, @jashapiro? When we have the full dataset that analysis will the one needing the biggest boat.

**Comment by cansavvy** [comment]
From in person talk with @jashapiro, plan is to: 

1) Turn distribution sina plots into density plots 
2) Do experiment with increasing VAF cutoffs -> recalculate TMB and determine if this improves TMB correlations across callers. Can we recover VarDict by increasing VAF cutoff? 
3) Turn TMB distribution into facet wrapped plot so it is more easily readable.

**Comment by jashapiro** [comment]
> From in person talk with @jashapiro, plan is to:
> 
> 1. Turn distribution sina plots into density plots
> 2. Do experiment with increasing VAF cutoffs -> recalculate TMB and determine if this improves TMB correlations across callers. Can we recover VarDict by increasing VAF cutoff?
> 3. Turn TMB distribution into facet wrapped plot so it is more easily readable.

**Comment by jashapiro** [comment]
> 2\. Do experiment with increasing VAF cutoffs -> recalculate TMB and determine if this improves TMB correlations across callers. Can we recover VarDict by increasing VAF cutoff?

*Saving Private VarDict*

**Comment by cansavvy** [comment]
Here's a rough draft of the VAF cutoff experiment. Let me know what other plots I should include. I think for it's full-fledged review I will make it its own PR. 
https://cansavvy.github.io/openpbta-notebook-concept/snv-callers/vaf_cutoff_experiment.nb.html

**Comment by jaclyn-taroni** [comment]
This looks like it might be at the stage where it's good to split this up into multiple pull requests to make it easier to review. The VAF filter experiment and comparison of callers seem like natural parts to break up and perhaps the small changes here and there can be split up in some logical way. What do you say @cansavvy and @jashapiro ?

**Comment by cansavvy** [comment]
> This looks like it might be at the stage where it's good to split this up into multiple pull requests to make it easier to review. The VAF filter experiment and comparison of callers seem like natural parts to break up and perhaps the small changes here and there can be split up in some logical way. What do you say @cansavvy and @jashapiro ?

Yes this is what my plan for today has been. This PR grew a bit out of control.

**Comment by cansavvy** [comment]
I think I will go ahead and close this PR because its served its purpose but should be replaced by subsequent PRs, which I will link on here as I make them.

**Pull request closed without merging**
