### PR TITLE
Update manta FILTER=='PASS' Part3 : oncoprint rerun 

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Rerun with FILTER==PASS for manta calls used in `copy_number_consensus_call`

#### What was your approach?
Rerun

#### What GitHub issue does your pull request address?
Add deep deletion status in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1099
Update with manta FILTER==PASS https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1113

#### Which areas should receive a particularly close look?
I have`deep deletion` and `amplification` in the oncoprint.
There seems to have been an issue with Varian_Classification [update](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1088/commits/e864fe290ca50dedb6cbb5787b292c96a10a727d) not going into master from #1088 so I've added back in this PR.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
figures

#### What is your summary of the results?
Previous primary_only_hgat_goi_oncoprint.png with status=="loss" as Del and "amplification" as Amp
image

Current file primary_only_hgat_goi_oncoprint.png with status=="loss" as Del and "amplification" as Amp along with manta `FILTER==PASS`
image

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Thanks @kgaonkar6 - can you show the GOI plots? I don't think the top N gene plots are as useful here.

Also, I will say no to a stepwise review - we shouldn't call any non-pass variants.

**Comment by kgaonkar6** [comment]
Is deep deletion filter ok? I reverted back to use "loss" as Del in the last commit to make it comparable to master

**Review by jharenza — APPROVED** [review]
This 100% looks much better. I checked the LGAT plots as well and those unexpected amplifications across the fusion genes are also gone (which they should be).

For plotting `Del` - we tend to use deep deletions in these plots, so that is what we should do here and can specify in the manuscript.

**Comment by jaclyn-taroni** [comment]
> For plotting `Del` - we tend to use deep deletions in these plots, so that is what we should do here and can specify in the manuscript.

My interpretation of this comment is that `analyses/oncoprint-landscape/01-map-to-sample_id.R` needs to be revised before this goes in - is that correct?

**Comment by jharenza** [comment]
> My interpretation of this comment is that `analyses/oncoprint-landscape/01-map-to-sample_id.R` needs to be revised before this goes in - is that correct?

yes, I misunderstood some offline discussion with @kgaonkar6 thinking this current version already had that update.

**Review by jaclyn-taroni — CHANGES_REQUESTED** [review]
Okay no problem, I am going to hit this with request changes so I don't accidentally merge this before that happens!

**Review by jaclyn-taroni — APPROVED** [review]

**Comment by kgaonkar6** [comment]
Sorry about the confusion! 

In the last commit status `deep deletion` is labeled as `Del`.

@jharenza also pointed out TTYH1 amplifications that needed to be verified. I've spot checked the TTYH1 in the 2 EMTR samples and they are supported by both cnvkit and freec so we consider these as high confidence calls :

```
# A tibble: 2 x 4
  biospecimen_id gene_symbol copy_number_cnvkit status       
  <chr>          <chr>                    <dbl> <chr>        
1 BS_TE8QFF7T    TTYH1                        7 amplification
2 BS_69VS8PS1    TTYH1                        7 amplification
> check_freec %>%  filter(gene_symbol=="TTYH1",status=="amplification") 
# A tibble: 2 x 4
  biospecimen_id gene_symbol copy_number_freec status       
  <chr>          <chr>                   <dbl> <chr>        
1 BS_K07KNTFY    TTYH1                      12 amplification
2 BS_TE8QFF7T    TTYH1                       8 amplification
```

**Pull request merged**
