### PR TITLE
In Progress: Draft of the analyses and plots associated with issue #5

### PR DESCRIPTION
**Pull request by cbethell**
### Purpose:
This PR addresses [issue #5](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/5).
This is a draft PR, I will chunk sections out of this PR as I progress in order to make the files easier to review. 
That being said, the purpose of this draft PR is for collaborators to view the general workflow and results produced thus far and give their feedback. 
 
### Format of the PR:
There are separate scripts (one for cleaning and filtering data, one for creating the multilayer pie chart, one for installing packages, and one for a shiny app pertaining to the pie chart).

The R markdown file provides a summary of the plots and results produced, along with the relevant and necessary chunks of code used to produce them. (I would start here when reviewing this PR). 

### Notes
The main ideas I would like input on include:
1. Does the multilayer sunburst pie chart meet expectations? (In terms of the presentation and the data representation)
2. Are there any additional data filtering steps that may need to be included for this particular dataset?
3. Are the results/plots suffice for this particular issue? If not, what other forms of tables or plots would you like to see included?

### Pull Request Check List:
* [x] Run a linter
* [x] Set the seed (if applicable).
* [x] Comments and/or documentation up to date.
* [x] Double check your paths.
* [x] Check headline numbering.
* [x] Spell check any Rmd file or md file.
* [x] Restart R and run all notebooks fresh and save.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Thanks for filing a WIP PR @cbethell! A few things jump out at me with this draft outside of your three questions above:
- Analysis scripts, currently in `sample-distribution-analyses/scripts`, are expected to be in the top directory for a given analysis (e.g., `sample-distribution-analyses`) per [these instructions](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/e49017e340a356fbe5241ab43c9f4c58011ff506#folder-structure). They should also be numbered to reflect the order in which you expect them to be run.
- What is the rationale for the inclusion of the code for the dependencies in `sample-distribution-analyses/plots/histology-pie_files/`? Do those folders need to be there and committed to this repository? I'm thinking it might be preferable to add them to `sample-distribution-analyses/.gitignore` + some instructions on a `sample-distribution-analyses/README.md` _or_ have them installed on the Docker image. (I have not looked into the license for each of these dependencies, but compatibility is a concern I have.) I don't have enough information to understand which of these options would be better yet.
- I would not include PDFs of tabular data unless there is a strong justification for doing so, as they are not easily machine readable. 
- We should assume that [this file](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/857fd810e1af16fa20f51df39e579a65de208615/sample-distribution-analyses/data/2019-07-26-pbta-histologies%20-%202019-07-26-including-germline.tsv) will live in the main data directory (`../data` relative to your analysis directory `sample-distribution-analyses`), as @jharenza notes that it will be included in the data download in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/19#issuecomment-519168704.

**Comment by cbethell** [comment]
>- Analysis scripts, currently in `sample-distribution-analyses/scripts`, are expected to be in the top directory for a given analysis (e.g., `sample-distribution-analyses`) per [these instructions](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/e49017e340a356fbe5241ab43c9f4c58011ff506#folder-structure). They should also be numbered to reflect the order in which you expect them to be run.
>- What is the rationale for the inclusion of the code for the dependencies in `sample-distribution-analyses/plots/histology-pie_files/`? Do those folders need to be there and committed to this repository? I'm thinking it might be preferable to add them to `sample-distribution-analyses/.gitignore` + some instructions on a `sample-distribution-analyses/README.md` _or_ have them installed on the Docker image. (I have not looked into the license for each of these dependencies, but compatibility is a concern I have.) I don't have enough information to understand which of these options would be better yet.
>- I would not include PDFs of tabular data unless there is a strong justification for doing so, as they are not easily machine readable. 
>- We should assume that [this file](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/857fd810e1af16fa20f51df39e579a65de208615/sample-distribution-analyses/data/2019-07-26-pbta-histologies%20-%202019-07-26-including-germline.tsv) will live in the main data directory (`../data` relative to your analysis directory `sample-distribution-analyses`), as @jharenza notes that it will be included in the data download in https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/19#issuecomment-519168704.

@jaclyn-taroni 
- I will modify the structure of the folder to be in line with the project's instructions. 
- The `sample-distribution-analyses/plots/histology-pie_files/` were produced via `mapview::mapshot` which is the function required to create the HTML for the pie chart. However, I do believe that I can add them to `sample-distribution-analyses/.gitignore` without consequence. I will look into this for verification. I will also add a README.md containing instructions for the contents of the folder. As for the compatibility concern, is there a specified version of R or a compatibility guideline that we would want to use? I figured that all the necessary packages and dependencies would be installed on the Docker image at some point, but until then I can ensure that the packages I use will not pose an issue when installation time comes. 
- I can remove the PDFs of tabular data, however one of them are intended for easy access of the data required for production of the brain graphic. This file can indeed be removed after we have the completed brain graphic. 
- Ah, noted. I will move this file to the main directory.

**Comment by jaclyn-taroni** [comment]
> As for the compatibility concern, is there a specified version of R or a compatibility guideline that we would want to use?

With 
> (I have not looked into the license for each of these dependencies, but compatibility is a concern I have.) 

I was referring to the [license compatibility](https://en.wikipedia.org/wiki/License_compatibility) of the software. I would consider myself only _vaguely aware_ of this issue and wanted to steer clear of wading into it where possible.

As for 
> I figured that all the necessary packages and dependencies would be installed on the Docker image at some point, but until then I can ensure that the packages I use will not pose an issue when installation time comes.

I believe the plan is to use `rocker/tidyverse:3.6.0` for the base image (cc @cgreene). I would recommend that you do your development using that image for the moment.

**Comment by cbethell** [comment]
> I was referring to the license compatibility of the software. I would consider myself only vaguely aware of this issue and wanted to steer clear of wading into it where possible.

Understood, I will have to familiarize myself with this license compatibility issue and be sure to steer clear of it where possible as well. I will keep this in mind going forward. 

> I believe the plan is to use rocker/tidyverse:3.6.0 for the base image (cc @cgreene). I would recommend that you do your development using that image for the moment.

I will also start using that image and make changes to code where necessary.

**Comment by jaclyn-taroni** [comment]
I'm going to close this since it has become several other pull requests.

**Pull request closed without merging**
