### PR TITLE
Ewings fuse summary

### PR DESCRIPTION
**Pull request by kgaonkar6**
### Purpose/implementation Section
Add binary present/absent status for EWSR1‐FLI1, EWSR1‐ERG, EWSR1‐PATZ1, or FUS‐ERG for all RNAseq samples  

#### What scientific question is your analysis addressing?
Which biospecimens have ewings sarcoma hallmark fusions

#### What was your approach?
I used v15 putative_oncogenic_fusions.tsv to look for EWSR1‐FLI1, EWSR1‐ERG, EWSR1‐PATZ1, or FUS‐ERG per biospecimen. 

Also I believe this bit needs to be added https://github.com/kgaonkar6/OpenPBTA-analysis/blob/999388f7634566e95e855c23e3d22d82b45b6c06/analyses/fusion-summary/01-fusion-summary.Rmd#L55 to get 1/0 values instead of 2 (if a biospecimen has the same fusion as inframe and framshift BS_1N9XZXGE: EWSR1--FLI1) or 3 ( inframe,frameshift and other like in BS_ZVZDDW2G:MN1--PATZ1 I checked this since this edit seems to affect the previous results files as well)

#### What GitHub issue does your pull request address?
#623 

#### Which areas should receive a particularly close look?
Does this look ok to be added here https://github.com/kgaonkar6/OpenPBTA-analysis/blob/999388f7634566e95e855c23e3d22d82b45b6c06/analyses/fusion-summary/01-fusion-summary.Rmd#L55? Or I can remove that to be equivalent to previous results.

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
results/fusion_summary_ewings_foi.tsv 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
EWSR1‐FLI1, EWSR1‐ERG, EWSR1‐PATZ1 and FUS‐ERG seems to be missing from the testing data pbta-fusion-putative-oncogenic.tsv which causes the error on CI

**Comment by jaclyn-taroni** [comment]
I _think_ changing this line to also include _EWSR1_ would do the trick: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5f2468daf2756a62c7d4615a7660b0a52e5ad135/analyses/create-subset-files/02-subset_files.R#L112

We would do that in a separate pull request -> generate new CI files -> put them in S3.

**Comment by kgaonkar6** [comment]
ok I can try to do that and file a new PR

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 I filed that small change at #638 and was able to successfully run this notebook locally. I wanted to get that open so we can get the S3, etc. taken care of first thing tomorrow.

**Comment by kgaonkar6** [comment]
Thanks for getting the EWSR1 in there! I did try to run the create-subset-files/02-subset_files.R locally but kept getting 
`Error: vector memory exhausted (limit reached?)`
`Execution halted`
even when R_MAX_VSIZE=100Gb

**Comment by jaclyn-taroni** [comment]
I am not surprised to hear that, I think it takes right about 128GB of RAM to read in the VarDict MAF file. That's why there's an option for local development in that module: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/create-subset-files#local-development which I used for #638. I'll work on getting the S3 part sorted shortly!

**Comment by jaclyn-taroni** [comment]
Okay - uploaded the new files and hit rerun on CircleCI: https://circleci.com/gh/AlexsLemonade/OpenPBTA-analysis/3866. This module passes now.

**Comment by kgaonkar6** [comment]
ok thank you!

**Pull request merged**
