### PR TITLE
Update tp53 module to add figures for manuscript

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

Create and update plots for manuscript

#### What was your approach?

1. Create violin plots of TP53 scores across molecular subtype per broad histology. For these plots, I filtered `molecular_subtype == NA | molecular_subtype == To be classified`, `sample count >= 3` and `molecular subtype count > 1`
2. Create violin plots of TP53 scores per cancer predisposition. For these plots, I removed `cancer_predispositions == NA` and `tp53_score == NA`.
3. Update ROC curves using a unified theme `theme_pubr`

#### What GitHub issue does your pull request address?

https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1146

#### Which areas should receive a particularly close look?

* Plots of TP53 scores across molecular subtypes per broad histology

```
plots
├── TP53scores_Diffuse_astrocytic_and_oligodendroglial_tumor.png
├── TP53scores_Embryonal_tumor.png
├── TP53scores_Ependymal_tumor.png
├── TP53scores_Low-grade_astrocytic_tumor.png
```

*  P-value files for TP53 comparison with molecular subtypes per broad histology
```
results
├── TP53scores_Diffuse_astrocytic_and_oligodendroglial_tumor.tsv 
├── TP53scores_Embryonal_tumor.tsv
├── TP53scores_Ependymal_tumor.tsv
├── TP53scores_Low-grade_astrocytic_tumor.tsv
```

* Output of 06-evaluate-classifier.py to be used for creating ROC curves in R

```
results
├── polya_TP53.tsv 
├── stranded_TP53.tsv 
```

* Updated ROC curves using 07-plot-roc.R

```
plots
├── polya_TP53_roc.png
├── stranded_TP53_roc.png
```

* Plots of TP53 altered status for each of the cancer predispositions

```
plots
├── Li-Fraumeni\ syndrome_tp53_scores.png
├── NF-1,Other\ inherited\ conditions\ NOS_tp53_scores.png
├── NF-1_tp53_scores.png
├── NF-2,Schwannomatosis_tp53_scores.png
├── NF-2_tp53_scores.png
├── None\ documented_tp53_scores.png
├── Other\ inherited\ conditions\ NOS,Schwannomatosis_tp53_scores.png
├── Other\ inherited\ conditions\ NOS_tp53_scores.png
├── Schwannomatosis_tp53_scores.png
├── Tuberous\ Sclerosis_tp53_scores.png
```

#### Is there anything that you want to discuss further?

Should we remove:

1) Old version of `Li-Fraumeni syndrome_tp53_scores.png`

```
plots
├── lfs_tp53_scores.png
``` 

2) Old version of ROC plots that are now under `plots/`:

```
results
├── polya_TP53.png
├── stranded_TP53.png
```

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

Tables, figures as specified above

#### What is your summary of the results?

N/A

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
@jharenza can you review this when you get a chance? I wasn't sure if you got notified about it.

**Comment by jharenza** [comment]
Yes, on my list for today!

**Review by jharenza — CHANGES_REQUESTED** [review]
Hi @komalsrathi ! thanks for updating these plots. To answer your questions:

>Should we remove:
>1. Old version of Li-Fraumeni syndrome_tp53_scores.png
plots
>2. Old version of ROC plots that are now under plots/

Yes, sounds good. 

> As an alternative to the above plot, create heatmap figure of all scores with annotations for display_group, cancer_group, and label by molecular_subtype - possibly mirroring the immune deconv scores heatmaps
For this, if we make the molecular subtype as the y-axis, what would be the x-axis?

I've been thinking about this one, but I am not sure as of yet, so I need to think a bit more - we can handle that in a different PR. 

I noticed that the ROC curves do not have the shuffle scores being plotted - can you update those? Otherwise, the rest looks good.

**Comment by komalsrathi** [comment]
@jharenza I have made the following changes:  
1) updated some output file names to be consistent and more meaningful
2) updated ROC with shuffled/non-shuffled data + using `simpsons` theme
3) updated README

**Review by jharenza — COMMENTED** [review]
Thanks @komalsrathi - sorry I also forgot to mention that in some plots (eg: `None documented_tp53_scores.png`), the wilcoxon p values are written on the plot twice and are different - can you check into this?

**Comment by komalsrathi** [comment]
Ok, just fixed it. It was using wilcox by default but had 3 levels which weren't showing up. Now I am using a condition to use kruskal test for > 2 levels [here](https://github.com/komalsrathi/OpenPBTA-analysis/blob/tp53-nf1-score/analyses/tp53_nf1_score/util/plot_by_cancer_predisposition.R#L6-L11)

**Review by jharenza — APPROVED** [review]
thanks @komalsrathi - looks fine to me for now!

**Comment by komalsrathi** [comment]
I am not sure why the checks are failing, because it is running successfully on my local machine.

**Comment by jharenza** [comment]
sorry @jaclyn-taroni - missed tagging you in this for the CI failure

**Comment by jaclyn-taroni** [comment]
> I am not sure why the checks are failing, because it is running successfully on my local machine.

To narrow things down – running locally using the Docker image and [the CI data](https://github.com/AlexsLemonade/OpenPBTA-analysis#working-with-the-subset-files-used-in-ci-locally)?

**Comment by komalsrathi** [comment]
> > I am not sure why the checks are failing, because it is running successfully on my local machine.
> 
> To narrow things down – running locally using the Docker image and [the CI data](https://github.com/AlexsLemonade/OpenPBTA-analysis#working-with-the-subset-files-used-in-ci-locally)?

No, I usually just run the bash script as is: `cd OpenPBTA-analysis/analyses/tp53_nf1_score && bash run_classifier.sh`

**Comment by jaclyn-taroni** [comment]
Based on [the error](https://app.circleci.com/pipelines/github/AlexsLemonade/OpenPBTA-analysis/5997/workflows/690858dc-c692-4f2b-bb6c-4ce46bd1b28a/jobs/6729?invite=true#step-125-817):

```
Error: Column `shuffled` can't be modified because it's a grouping variable
```

I suspect the problem is this part of the code using the version of `dplyr` on the project image:

https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1166/files#diff-493f7948a2d11d25184544297119530038ef44dfe0f2692706ea079a9cc04e19R12-R17

**Comment by komalsrathi** [comment]
@jaclyn-taroni ok I removed the unnecessary grouping I had in my code, all good now. Thanks!

**Pull request merged**
