### PR TITLE
PR 2 of 5 Genereal filtering for fusion calls

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### Purpose/implementation

_What scientific question is your analysis addressing? 
What was your approach? 
General filtering for fusion as discussed with @jharenza and @jaclyn-taroni 
https://docs.google.com/spreadsheets/d/1fKvDkkGddyeQ-_BHlE06XfMz82SC_nAPo7zwximxJRo/edit#gid=0
Steps 1:7,9

If this is not adding an analysis, describe your changes in this section._

#### Issue

_What GitHub issue does your pull request address?_
Planned Analysis: Filter and Annotate Fusions #39

#### Directions for reviewers

_Tell potential reviewers what kind of feedback you are soliciting. 
Are there particular areas that need a closer look?
Are there particular areas that need a closer look? Code optimization, filtering strategy

Is there something you want to discuss further?
I haven't merged the callers for this step yet I wonder if the general filtering can be done per caller and then use the project based filtering to merge the putDriver and filtFusion calls? Step 8 of general QC was not performed becuase the calls are not merged at this step.

Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?_

#### Results

_If your pull request includes code that produces scientific results, please summarize the results here.
This can help facilitate discussion around interpretation.
The 02-fusion-filtering.R provides a general strategy to filter fusion calls to perform QC filters and gene list based fusion filtering

Please state what kinds of results are included (e.g., table, figure)._
#filtered fusion calls with general QC and putDriver gene list filter
scratch/starfusionQCGenelistFiltered_putDriver.RDS
#filtered fusion calls with general QC and filtFusion gene list filter
scratch/starfusionQCGenelistFiltered_filtFusion.RDS

#### Docker and continuous integration

_Check all those that apply or remove this section if it is not applicable._

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

Parts to this analysis
- [x] Fusion standardization
- [x] Fusion filtering (general)
- [x] Putative driver fusion expression filtering 
- [x] Filtering fusion expression filtering
- [ ] Project specific filtering
- [ ] Annotation of final calls
- [ ] Plot recurrent fusion calls

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Hi @kgaonkar6 - it looks like you have some old commits showing up. You may want to make sure the master branch of your fork is synced with the AlexsLemonade master and then create a new branch from master on your fork where you commit `02-fusion-filtering.R`. 

You may find this section of `CONTRIBUTING.md` helpful: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#filing-a-pull-request-from-your-own-branch

Let me know if you have questions, we'll get this sorted!

**Comment by kgaonkar6** [comment]
Hi @jaclyn-taroni! Thanks, I did follow the instructions (properly this time) and I think I fixed those old commit issues now.

Now my confusion is if 02-fusion-filtering.R should be a commit by itself? From the documentation it looks like it should pass CI individually before I create a run_analysis.sh with 01 and 02 scripts. But since I'm trying to use the output from 01-fusion-standardization.R it looks like I should have both of them run using run_analysis.sh in this PR..?

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 was typing this as you posted 😃 

Your filtering script is expecting a standardized Arriba file in `scratch`:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/e276dfaa75a11f6043ab9a4c7c03ec784d98bc04/.circleci/config.yml#L29

But there will not be anything in `scratch` on the computer running CI unless you first run a `01-fusion-standardization.R` step in CI. To accomplish this, I would expect there to be two fusion steps in the CI file that gets added with this pull request where these two steps act on the same set of files, such as:

```
 - run:
          name: fusion filtering
          command: ./scripts/run_in_ci.sh Rscript analyses/fusion_filtering/01-fusion-standardization.R -f "data/pbta-fusion-arriba.tsv.gz" -c "Arriba" -o "scratch/arriba.tsv"

 - run:
          name: fusion filtering
          command: ./scripts/run_in_ci.sh Rscript analyses/fusion_filtering/02-fusion-filtering.R -S scratch/arriba.tsv -e data/pbta-gene-expression-rsem.fpkm.rds -r FALSE -a "NEIGHBORS|GTEx|HGNC_GENEFAM|DGD_PARALOGS|Normal|BodyMap|ConjoinG" -j 1 -s 10 -i "inframe|frameshift|other" -p "allOnco_Feb2017.tsv,tsgs.txt,pancanfus.txt,Census_allTue Sep 17 18_59_30 2019.tsv"  -f "predictedTF_attribute_list_entries.txt,curatedTF_attribute_list_entries.txt,Kincat_Hsap.08.02.txt"  -R analyses/fusion_filtering/references -o scratch/arriba_QC_filter.rds -t 1 
``` 

Once all of the steps in your fusion pipeline go in through review, then you would file a new pull request where you add a shell script and you replace _x_ sequential fusion pipeline steps in the CI config file with a single step that runs the shell script.

**Comment by kgaonkar6** [comment]
Ah haha..  that makes sense, thanks for all the help!! I'll update the CI file.

**Comment by jaclyn-taroni** [comment]
Looks like the CI stuff is worked out 👍  - still seeing old commits show up. 

Can you walk me through how you set up this branch so I can better understand the situation and how to revise the instructions? If I look at your master branch, it is behind AlexsLemonade master: https://github.com/kgaonkar6/OpenPBTA-analysis/tree/041373597322e9415eb30a4223453b541733ea98

Thank you!

**Comment by kgaonkar6** [comment]
Yeah so the instructions are quite clear I think the old commits came from when I first started by trying to push to my fusion_filtering branch where I had 01-fusion-standardization.R by doing 
git push origin fusion_filtering
To which I got the error error: 
To https://github.com/kgaonkar6/OpenPBTA-analysis.git
 ! [rejected]        fusion_filtering -> fusion_filtering (fetch first)
failed to push some refs to
 'https://github.com/kgaonkar6/OpenPBTA-analysis.git' so I ran 
git fetch origin #where the old commits got added and broke the my first CI run because of the incorrect package installation name

So then I tried to do set up the branch correctly as in the instructions
git checkout -b general_filtering
git stash pop
git add analyses/fusion_filtering/02-fusion-filtering.R 
git commit -m "Add second script for fusion filtering"
git push origin general_filtering

**Comment by jaclyn-taroni** [comment]
I _believe_ the issue stems from the master branch of your fork being out of sync. Here's how I would fix this:

* Copy what you are adding here some place safe (`.circleci/config.yml` and `02-fusion-filtering.R`) 
* Make sure the master branch of your fork is up to date with the AlexsLemonade master branch. When I look [here](https://github.com/kgaonkar6/OpenPBTA-analysis/tree/master) at your master branch it says `This branch is 1 commit ahead, 29 commits behind AlexsLemonade:master.` So you may need to reset to before the `1 commit ahead` before merging the upstream master branch (AlexsLemonade) into your master. Here's a GitHub Community Forum post on this: https://github.community/t5/How-to-use-Git-and-GitHub/Syncing-a-fork-leaves-me-one-commit-ahead-of-upstream-master/td-p/13555
* Once you have a master branch that is up to date with the AlexsLemonade master branch, create a new branch from your master branch and add + commit the files you stuck some place safe (`.circleci/config.yml` and `02-fusion-filtering.R`). Then you're ready to file a PR with those changes.

**Comment by kgaonkar6** [comment]
Okay looks like the master is even with AlexsLemonade now? I added the files to a new branch "general_filtering" branch as well. Should I delete this PR and add a new one?

**Comment by jaclyn-taroni** [comment]
> I added the files to a new branch "general_filtering" branch as well. Should I delete this PR and add a new one?

Yes, please close this PR and open a new one, thanks!

**Pull request closed without merging**
