### PR TITLE
V11 Release

### PR DESCRIPTION
**Pull request by yuankunzhu**
#### Purpose/implementation

data release updates for v10
- changes:
  - Add putative oncogenic fusions from [fusion filtering and prioritization analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering)
  - Update consensus SNV/indels to contain [consensus MNVs](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/275)
  - Add RNA-Seq [collapsed matrices](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/287) - wrong files (tables of transcripts removed) were included with [V10](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/273)
#### Directions for reviewers
changed on release notes and download script. 

- release file added:
  - pbta-fusion-putative-oncogenic.tsv
  - pbta-snv-consensus-20191125.zip
  - pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
  - pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
  - pbta-snv-consensus-mutation.maf.tsv.gz
  - pbta-snv-consensus-mutation-tmb.tsv

- release file removed:
  - pbta-gene-expression-rsem-fpkm-collapsed_table.polya.rds
  - pbta-gene-expression-rsem-fpkm-collapsed_table.stranded.rds
  - pbta-snv-consensus_11122019.zip

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
@yuankunzhu it looks like this includes a zip file of the consensus information:
```
pbta-snv-consensus-20191125.zip: OK
Archive:  data/pbta-snv-consensus-20191125.zip
   creating: data/snv-consensus-20191125/
  inflating: data/snv-consensus-20191125/consensus_mutation_tmb.tsv  
  inflating: data/snv-consensus-20191125/README.md  
  inflating: data/snv-consensus-20191125/consensus_mutation.maf.tsv 
```

Can we rename these files and include them in the top directory alongside the other files per this comment https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/287#issuecomment-558653481? Copying the relevant part below for your reference:

> Regarding the new consensus mutation files, I think since we will probably put the `pbta-fusion-putative-oncogenic.tsv` directly in the release folder, we should make some changes to how the consensus mutation files are distributed.
>
> The file structure of `snv-consensus-20191125.zip` is as follows:
>
> ```
>  .
> ├── README.md
> ├── consensus_mutation.maf.tsv
>└── consensus_mutation_tmb.tsv
> ```
>
> Could we rename the contents to:
> `consensus_mutation.maf.tsv` -> `pbta-snv-consensus-mutation.maf.tsv` (+ possibly compress this file)
> `consensus_mutation_tmb.tsv` -> `pbta-snv-consensus-mutation-tmb.tsv`
> 
> And then include these in the "top directory" of the release folder?

**Comment by yuankunzhu** [comment]
sure thing @jaclyn-taroni. made the change, please review.

**Comment by jaclyn-taroni** [comment]
My apologies, my comment about compressing the MAF file was ambiguous. I would expect that file to be gzipped to be consistent with the other files and then for the unzip steps at lines 51-52 to come out of `download-data.sh`.

**Comment by yuankunzhu** [comment]
ah no worries. i was thinking about that too. will update the MAF to gzip

**Comment by jaclyn-taroni** [comment]
Yes that’s what I was thinking, thanks.

**Comment by jaclyn-taroni** [comment]
With https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/293/commits/112019eb01065459d47ef7ba615adef4cf58cd6c I was mostly checking if edits by maintainers was allowed because I would like the folks that generated the consensus mutation files (@cansavvy, @jashapiro) to include documentation in the README as part of this pull request per https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/287#issuecomment-558653481 and https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/287#issuecomment-558761876.

**Comment by jaclyn-taroni** [comment]
I got the 👍 over on https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/299, so I will merge those changes into this branch.

**Pull request merged**
