### PR TITLE
V22 run MB subtyping (3/N)

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
Run MB subtyping

#### What GitHub issue does your pull request address?
#1207 #1426 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What is your summary of the results?
No change in subtypes, only clinical data

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Are all the changes in `analyses/molecular-subtyping-MB/input/subset-mb-clinical.tsv` expected?

**Comment by jharenza** [comment]
> Are all the changes in `analyses/molecular-subtyping-MB/input/subset-mb-clinical.tsv` expected?

It looks like these are because of column order changes. I didn't think that would have a major effect, but let me go back and match the order of the new base to previous so it is easier to detect changes. Also, `parental_aliquot_id` will no longer exist in base since it was removed from our database.

**Comment by jharenza** [comment]
@jaclyn-taroni looks a bit cleaner in [0e6f745](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1435/commits/0e6f745218411a186685fa5f0259085b3cc7a810). Expected changes due to base file.

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻

**Pull request merged**
