### PR TITLE
Add fusion within TP53 loss annotation 

### PR DESCRIPTION
**Pull request by kgaonkar6**
⚠️ merge #1073 before this PR

#### What scientific question is your analysis addressing?
Add fusions in TP53 as a gene loss annotation.

#### What was your approach?
 - Added a code chunk to read in fusion calls and generate granges
```
putative_onco_tp53_fusion_gr <- putative_onco_fusion %>%
  filter(str_detect(FusionName,"^TP53--|--TP53$")) %>%
  left_join(histology,
            by = c("Sample" = "Kids_First_Biospecimen_ID")
  ) %>%
  dplyr::select("Sample",
                "sample_id",
                "FusionName",
                "RightBreakpoint",
                "LeftBreakpoint") %>%
  reshape2::melt(c("Sample","sample_id","FusionName")) %>%
  mutate(
    BreakpointChr = paste0("chr",gsub(":.*$", "", value)),
    Breakpoint = gsub("^.*:", "", value)) %>%
  GenomicRanges::makeGRangesFromDataFrame(seqnames.field = "BreakpointChr",
                                          start.field = "Breakpoint",
                                          end.field = "Breakpoint",
                                          
                                          keep.extra.columns = TRUE,
                                          starts.in.df.are.0based = FALSE)
```

 - And then checked if fusion breakpoint is in exon 1 which would result in loss of functional domain of TP53 gene

#### What GitHub issue does your pull request address?
#1094 

#### Which areas should receive a particularly close look?
I checked for intron overlaps but I didn't see any ranking on introns so can't figure out a filter for intron1  so I was wondering if it would be easier to just check for domain loss of TP53?

#### Is there anything that you want to discuss further?
In `05-tp53-altered-annotation.Rmd` we aggregate the calls which needs a logic to add the fusion update as a loss , I added fusion to the CNV|SV logic we have already
-  if sample_id has SNV+(CNV|SV|Fusion) mutation suggesting both alleles are mutated
-  if CNV|SV mutant|Fusion  and has Li-Fraumeni syndrome suggesting germline TP53 mutant as cancer predisposition
-  if tp53 inactivating score for RNA_Seq is greater that 0.5 and has 1 or more SNV| (CNV|SV|Fusion) loss in TP53

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
7316-349 ( DNA:BS_YETTZ1NC, RNA:BS_NJ4WPQVK) is now annotated as TP53 loss since the classifier score is greater than 0.5 and also has a fusion.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
Thanks for adding this @kgaonkar6 ! As we were talking about intron 1, I got that from the canonical _TP53_ fusions, especially in osteosarcoma, which result in non-functional TP53. It does look like, from a quick lit search, that these have been found in other [metastatic cancers](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0218618), consistent with this finding. Theoretically, we might be able to extend the breakpoint region between the start site and prior to the first domain, but I think sticking to intron 1 for now works.

**Comment by kgaonkar6** [comment]
I wasn't able to find any ranking information for introns so could not select for intron1 specifically (if we select a canonical TP53 transcript we could select by start and stop) and more importantly the fusion  TP53--PSMG4 overlaps the 1st exon in BS_NJ4WPQVK. Does that sound ok ? 
It would be easiest to just check if breakpoint is anywhere between the start and first domain, should I implement that?

It seems we are missing BS_NJ4WPQVK with the TP53--PSMG4 fusion which is failing the CI checks, should I update the test files ?

**Comment by jharenza** [comment]
No, I think your parameters now are fine- just noting.

@jaclyn-taroni is it worth updating CI files for this one sample?

**Comment by jaclyn-taroni** [comment]
I'll let you all decide if you'd like to file a PR to `create-subset-files` to include that sample, but some considerations:

* There is a precedent for such things (see: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/c0744576ee80914636443b01012168efc2da22a9/analyses/create-subset-files#special-considerations)
* At this stage in the project, I do not anticipate updating the CI files in this matter to break things but it is a possibility. 
* What would we not be testing if we didn't add that sample and how critical is it?

**Comment by jharenza** [comment]
I don't think it's critical if you are ok merging without the pass since it's just one sample.

**Comment by jaclyn-taroni** [comment]
If this goes in and does not pass, that means all PRs will have to be merged with it failing which I don't want to do because it 1. means modules that come after it will not be tested 2. everything needs to be merged with administrative power. 

We can skip this step in CI if it's not critical (and this may be what you meant above!) or what might be a better/more robust approach would be to add logic to the code to handle if the sample is missing.

**Comment by jharenza** [comment]
Ah, i see- let's add logic to the code to handle if a sample is missing @kgaonkar6

**Comment by kgaonkar6** [comment]
Sounds good, I'll update the code. Thanks for the input @jaclyn-taroni @jharenza !

**Pull request merged**
