### PR TITLE
Rerun changes added

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Ran generate analysis for data release bash script and these are the changes after the re-run.

#### What was your approach?
Started an EC2 instance with 1T storage and 256G memory, pull the scripts, run the generate files script, and then push the generated files to S3 bucket.
*Note: I am not so sure about the memory requirement to run everything but the overall storage is ~60G so next time an instance with 100G should be enough.

#### What GitHub issue does your pull request address?
NA

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Only gistic results were changed (expected) - and everything else remained the same.

#### What is your summary of the results?
NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Posting here the md5sums of the files that went to the v22 folder on S3 from this analysis:
```
fa0adcd26f408d840f25339d2a1ea09f  consensus_seg_annotated_cn_autosomes.tsv.gz
9589cd18d0e6c1f7c2d939126c63ec6c  consensus_seg_annotated_cn_x_and_y.tsv.gz
0536b77bb401cca767831ef58f0ccacc  fusion_summary_embryonal_foi.tsv
345545272e1d568871130a98e50f4f2b  fusion_summary_ependymoma_foi.tsv
f6f177fd2ee8eddcd6a5c5a0eebea16e  fusion_summary_ewings_foi.tsv
3f65eece4cfc16dcca356ca46742c50a  fusion_summary_lgat_foi.tsv
112d31c63833afcd30584b6cf20486c3  independent-specimens.rnaseq.primary-plus-polya.tsv
a3fe5599fe205c5745052f3e3185a0e4  independent-specimens.rnaseq.primary-plus-stranded.tsv
24871dd0c2c1962eaf076ebc8e35a55b  independent-specimens.wgs.primary-plus.tsv
799b88792022596dd654ade3cadebca7  independent-specimens.wgs.primary.tsv
2b02d0b273c1445919aae4926661c710  independent-specimens.wgswxs.primary-plus.tsv
05b31fcc9ff75b0fe9dcc50801b59510  independent-specimens.wgswxs.primary.tsv
c0239148a039150f08390a4a560986df  pbta-cnv-consensus-gistic.zip
b9284650be04df3538e6c6dba29b8eb0  pbta-cnv-consensus.seg.gz
88bcefa4b9a63a02f8548b345ad4ed7c  pbta-fusion-putative-oncogenic.tsv
1c2092fb5b26c7d8bc98cf5db081902d  pbta-fusion-recurrently-fused-genes-byhistology.tsv
6ab59378091fb35d9d71ef89b21aa457  pbta-fusion-recurrently-fused-genes-bysample.tsv
54c48dc8b9d8d6f2c80194bbaa59e417  pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
f15e89051d216d8668057dfa291a72ea  pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
22673111fe24382b7d2fdf18ac56454c  pbta-snv-consensus-mutation.maf.tsv.gz
25fec33dece960f2a10accda6b5249b1  pbta-snv-mutation-tmb-all.tsv
77fd1bce671e471c550d323478654ade  pbta-snv-mutation-tmb-coding.tsv
e1945546e713122d926c300d7b0df46d  pbta-snv-scavenged-hotspots.maf.tsv.gz
819e0e89e248e0e5604c00ce541508f7  tcga-snv-consensus-snv.maf.tsv.gz
e5fd2e720cd629d4cf67c5b3db8afa62  tcga-snv-mutation-tmb-all.tsv
90b14e59ccc846e44ee60b5e473eac52  tcga-snv-mutation-tmb-coding.tsv
```

Files which changed from v21:
```
fa0adcd26f408d840f25339d2a1ea09f  consensus_seg_annotated_cn_autosomes.tsv.gz
9589cd18d0e6c1f7c2d939126c63ec6c  consensus_seg_annotated_cn_x_and_y.tsv.gz
c0239148a039150f08390a4a560986df  pbta-cnv-consensus-gistic.zip
b9284650be04df3538e6c6dba29b8eb0  pbta-cnv-consensus.seg.gz
88bcefa4b9a63a02f8548b345ad4ed7c  pbta-fusion-putative-oncogenic.tsv
22673111fe24382b7d2fdf18ac56454c  pbta-snv-consensus-mutation.maf.tsv.gz
25fec33dece960f2a10accda6b5249b1  pbta-snv-mutation-tmb-all.tsv
77fd1bce671e471c550d323478654ade  pbta-snv-mutation-tmb-coding.tsv
```

**Comment by jaclyn-taroni** [comment]
@runjin326 - this is ready to be rerun now that #1421 is in and I've resolved conflicts, thanks!

**Comment by jaclyn-taroni** [comment]
Yes, but to be specific: I've already merged the changes from `upstream/master` to this branch in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1412/commits/00d18339b3be4dcfaa17551202ae5ed3a67ced87. So you will need to pull the changes into your local branch, upload to S3, and add additional changes to this branch.

**Comment by runjin326** [comment]
@jaclyn-taroni - quick question, for the re-run, do we download data from v22 folder or v21 folder? If from v22, then we are missing `pbta-histologies.tsv` and the md5sum for `tcga-snv-consensus-snv.maf.tsv.gz` did not match.

**Comment by runjin326** [comment]
@jaclyn-taroni and @jharenza - I have now reran the module. Changes are pushed to this PR and all the results are in the s3 bucket. Let me know whether there is anything else you need.

**Review by jaclyn-taroni — APPROVED** [review]
👍🏻  LGTM, thanks!

**Pull request merged**
