### PR TITLE
Figure S2 panels

### PR DESCRIPTION
**Pull request by sjspielman**
This PR addresses Issue #1254 and creates several panels for Figure S2:

| Panel | File | Generating script |
|------|-----|-------------------|
| A | `figures/pdfs/supp/figs2/panels/pbta_vaf_cor_matrix.tiff` | supp-snv-callers-panels.R |
| B | `figures/pdfs/supp/figs2/panels/pbta_vaf_distribution_plot.pdf` | supp-snv-callers-panels.R |
| C | `figures/pdfs/supp/figs2/panels/pbta_upset_plot.pdf` | supp-snv-callers-panels.R |
| D | `figures/pdfs/supp/figs2/panels/tcga_vaf_cor_matrix.pdf` | supp-snv-callers-panels.R |
| E | `figures/pdfs/supp/figs2/panels/tcga_vaf_distribution_plot.pdf` | supp-snv-callers-panels.R |
| F | `figures/pdfs/supp/figs2/panels/tcga_upset_plot.pdf` | supp-snv-callers-panels.R |
| G | `figures/pdfs/supp/figs2/panels/lancet_wxs_wgs_plot.pdf` | supp-snv-callers-panels.R |
| H | `figures/pdfs/supp/figs2/panels/pbta_tmb_cdf_plot.pdf` | supp-tmb-compare-panels.R |
| I | `figures/pdfs/supp/figs2/panels/tcga_tmb_cdf_plot.pdf` | supp-tmb-compare-panels.R |

Places for reviewers to look:
+ The panel `figures/pdfs/supp/figs2/panels/tcga_tmb_cdf_plot.pdf` uses Okabe Ito colors. Look ok? 
+ The panel `figures/pdfs/supp/figs2/panels/pbta_vaf_cor_matrix.tiff` is a TIFF and not a PDF due to file size. The PDF is 857 MB!

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
@sjspielman something is wrong with the upset plots here

**Comment by jaclyn-taroni** [comment]
> The panel `figures/pdfs/supp/figs2/panels/tcga_tmb_cdf_plot.pdf` uses Okabe Ito colors. Look ok?

The colors here are a little bit into chartjunk territory IMO. As far as I know, these diagnoses don't come up anywhere else in the manuscript and they're already a grouped plot.

**Comment by sjspielman** [comment]
> The colors here are a little bit into chartjunk territory IMO. As far as I know, these diagnoses don't come up anywhere else in the manuscript and they're already a grouped plot.

I added them to be "consistent" with the PBTA panel next door which does have colors. Can make these all gray in TGCA; also PBTA though?

**Comment by sjspielman** [comment]
> something is wrong with the upset plots here
This is super odd, they open on my computer. I'll try re-adding them..?

**Comment by jaclyn-taroni** [comment]
> I added them to be "consistent" with the PBTA panel next door which does have colors. Can make these all gray in TGCA; also PBTA though?

Right, but the PBTA panel has colors for a very specific reason: a reader should be able to identify a cancer group (display) across figures.

**Review by jaclyn-taroni — COMMENTED** [review]
Code looks fine with the exception of a couple very minor comments. I think I'm less likely request changes to the panels themselves than @jharenza, so we should wait for her to take a look before approval.

**Comment by sjspielman** [comment]
Upset plots have been recovered, and TCGA cdf plot points are now all gray

**Review by jharenza — APPROVED** [review]
Thanks @sjspielman - these look really nice! The only thing that I think we may change (and I can go either way, so I will leave up to you!) is adding an alpha level to make the CDF plot points somewhat transparent because generally other plots we have with points are done that way. (In that case, perhaps TCGA grey would darken to match the recent TP53 boxplot grey you used). Otherwise, I will approve!

**Comment by jharenza** [comment]
@sjspielman I went ahead and dropped the figures in the google slideshow and it looks like `lancet_wxs_wgs_plot.pdf` and `tcga_tmb_cdf_plot.pdf` could benefit from a smaller width to fit. If it helps, you can add the CDF panels together like before, so the x-axis widths are similar sizing, and we can add the panel letters later.

**Comment by sjspielman** [comment]
@jharenza thanks! I updated plot dimensions so hopefully they'll fit better now. Do these sizes work?

**Comment by sjspielman** [comment]
@jharenza I'm going to merge this in so we can more towards solidifying the overall `generate_figures.sh` script, and as needed should be quick to change figure sizes for paneling in another PR!

**Pull request merged**
