### PR TITLE
fix DNA-RNA mapping using parent_aliquot_id

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

Multiple MB subtypes assigned to `BS_5BMNK8SY`

#### What was your approach?

Use `parent_aliquot_id` to map DNA to RNA. This will map `BS_5BMNK8SY` to just `BS_QEYPFYHD`. The other RNA `BS_Z7PKVY9J` will be mapped to `NA`.

#### What GitHub issue does your pull request address?

https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1085

#### Which areas should receive a particularly close look?

Output tsv files

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
@kgaonkar6 can you check if this makes sense now? This should not affect any results but only the mapping of DNA samples to RNA samples in the output tsv file.

**Review by kgaonkar6 — APPROVED** [review]
This looks right to me, thanks!

**Review by jharenza — COMMENTED** [review]
Hi @komalsrathi - thanks for adding this. @kgaonkar6 I don't think that it is this simple, but checking with @baileyckelly now. Some samples have matching IDs, and some don't, but the format is not the same across the board and I don't think we can use it globally as a match. TBD.

**Review by jharenza — CHANGES_REQUESTED** [review]
ok after talking with @allisonheath and @baileyckelly, it seems like this field is going to be changing a bit, in the past has not been fully completed and DNA/RNA ids don't always align. For now, I would suggest for only samples which have two RNA-Seq samples for the same event that we assess the classifications. I think we can use the parental ID matching for this sample _only_, but also use a 3/4 consensus here, which is 3 for Group 4 and 1 for SHH. MM2S had a discrepancy between the two, which should not happen for the same tumor and time point, so we could flag this mismatch as being wrong. I probably prefer the latter since these samples are from the same event and should be annotated the same.

**Comment by komalsrathi** [comment]
For obtaining the consensus subtype, we can have the 3/4 cutoff for all duplicated samples (not sure if there are others too) or do you want me to hardcode for this sample only? Also, I think I will have to revert back to what we had before i.e. only use KF Participant ID and sample_id to map DNA and RNA because if I use the parental aliquot ID, `BS_Z7PKVY9J` (RNA) sample won't get mapped to `BS_5BMNK8SY` (DNA) and then we cannot apply the 3/4 rule. 

Is that all or am I missing anything?

**Comment by jharenza** [comment]
> For obtaining the consensus subtype, we can have the 3/4 cutoff for all duplicated samples (not sure if there are others too) or do you want me to hardcode for this sample only? Also, I think I will have to revert back to what we had before i.e. only use KF Participant ID and sample_id to map DNA and RNA because if I use the parental aliquot ID, `BS_Z7PKVY9J` (RNA) sample won't get mapped to `BS_5BMNK8SY` (DNA) and then we cannot apply the 3/4 rule.
> 
> Is that all or am I missing anything?

That's right - for 3/4, it would only be where samples for the same patient have the same `sample_id` and thus same `tumor_descriptor`. In addition, it sounds like the `parental_aliquot_id` will be changing in future releases, so using that will be unstable.

**Comment by komalsrathi** [comment]
@kgaonkar6 okay, I think this should fix the issue.

**Comment by kgaonkar6** [comment]
Perfect! This is ready to merge

**Comment by jaclyn-taroni** [comment]
We need a re-review from @jharenza because there are changes requested (or for me to dismiss the previous review) before this can be merged.

**Review by jharenza — APPROVED** [review]
This looks good, thank you @komalsrathi

**Pull request merged**
