### PR TITLE
Removing BRAF subtyping for HGG

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Step 1a from [this issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/807) (Remove BRAF from subtyping) should be done before we merge #784  

#### What was your approach?
Removed BRAF V600E subtyping steps from 04-HGG-molecular-subtyping-mutation.Rmd and BRAF V600E mutant checks from 07-HGG-molecular-subtyping-combine-table.Rmd where subtypes are combined and assigned to sample_ids

#### What GitHub issue does your pull request address?
#853

#### Which areas should receive a particularly close look?
In 07-HGG-molecular-subtyping-combine-table.Rmd where subtypes are combined and assigned to sample_ids I removed the checks for BRAF V600E do we still want to check if BRAF V600E does exist for mutual exclusivity checks just not assign the molecular subtype as "BRAF V600E"? 

#### Is there anything that you want to discuss further?
 The plot in 09-HGG-with-braf-clustering.Rmd will have broad_histology/molecular_subtype from v17 I believe for  LGAT, HGAT so it still has the molecular_subtype of BRAF V600E that is being plot in the tsne. 

Should we specifically mention the release data use in this script OR this script needs to be re-run once the histology file is update with v17 molecular_subtyping.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?

tables

#### What is your summary of the results?
PT_3AWKWXEV,PT_63F63QY0, PT_HGM20MW7,PT_P5HHJJPH,PT_T8V9ES93 and PT_Y8RNS9JE were coded as HGG, H3 wildtype instead of BRAF V600E

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
> The plot in 09-HGG-with-braf-clustering.Rmd will have broad_histology/molecular_subtype from v17 I believe for LGAT, HGAT so it still has the molecular_subtype of BRAF V600E that is being plot in the tsne.

I reviewed this PR and it looks good for removal, but I do think we want to keep the plot labels, since this led to re-classification of a tumor from HGG to LGG. This means we would need to keep the annotation. I wonder if the best way to do this is to break this up into two different modules - one which handles subtyping and one which handles the clustering and BRAF annotation? Thoughts @jaclyn-taroni ?

**Comment by jaclyn-taroni** [comment]
For the scatter plot produced in `09-HGG-with-braf-clustering.Rmd`, I understand that we need the following:

- Histone mutation status for HGAT
- BRAF V600E status for HGAT
- Pathology diagnosis information
- Relevant scores from `analyses/transcriptomic-dimension-reduction/`

I don't think we need to piece together this information in the same manner as what is currently in that notebook, though! Here's a general idea about how we could accomplish the same plot using different information and files:

- Retain the step where we look at BRAF V600E in `04-HGG-molecular-subtyping-mutation.Rmd`, but don't use it at all in `07-HGG-molecular-subtyping-combine-table.Rmd`
- Get the histone mutation status and BRAF V600E information from the `"HGG_cleaned_mutation.tsv"` file from `04`
- Get the pathology dx information from `pbta-histologies.tsv`
- Use the scores from `analyses/transcriptomic-dimension-reduction/` (they may be joined with metadata in there IIRC, we don't want to use that metadata).

If that sounds good/reasonable, we could revert the changes to `04` from this PR but continue not to use the BRAF V600E info in `07-HGG-molecular-subtyping-combine-table.Rmd`.

Thoughts @jharenza and @kgaonkar6 ?

**Comment by kgaonkar6** [comment]
> I don't think we need to piece together this information in the same manner as what is currently in that notebook, though! Here's a general idea about how we could accomplish the same plot using different information and files:
> 
> * Retain the step where we look at BRAF V600E in `04-HGG-molecular-subtyping-mutation.Rmd`, but don't use it at all in `07-HGG-molecular-subtyping-combine-table.Rmd`
> * Get the histone mutation status and BRAF V600E information from the `"HGG_cleaned_mutation.tsv"` file from `04`
> * Get the pathology dx information from `pbta-histologies.tsv`
> * Use the scores from `analyses/transcriptomic-dimension-reduction/` (they may be joined with metadata in there IIRC, we don't want to use that metadata).
> 
> If that sounds good/reasonable, we could revert the changes to `04` from this PR but continue not to use the BRAF V600E info in `07-HGG-molecular-subtyping-combine-table.Rmd`.

This sounds good to me, only thing in addition to the above would be to use DNA BS ids from HGG_cleaned_mutation.tsv to capture potential broad_histology updates in base histology because of H3 mutant detection like for 7316-158 [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/609#issuecomment-602821376) which goes from PNET to HGAT because of h3f3A mutation. Match DNA to RNA to filter scores from analyses/transcriptomic-dimension-reduction/

**Comment by jharenza** [comment]
sounds good, thanks @jaclyn-taroni

**Comment by kgaonkar6** [comment]
In the latest commit, as per @jaclyn-taroni's suggestion I have :

- Reverted 04-HGG-molecular-subtyping-mutation.Rmd to file in master to retain BRAF mutation status
- Get the histone mutation status and BRAF V600E information from the "HGG_cleaned_mutation.tsv" file from 04
- Get the pathology dx to extract LGAT sample_ids information from pbta-histologies.tsv
- Use the scores from analyses/transcriptomic-dimension-reduction/

**Review by jharenza — APPROVED** [review]
@kgaonkar6 thanks for these changes. I think this looks great. I also checked out the two additional HGAT BRAF-mutated samples which are showing up in the tSNE and UMAP which we previously did not observe (`BS_QYPHA40N` and `BS_59ZJWJTF`). These have `composition == Derived Cell Line` and were not previously captured in the molecular subtyping module, so this change is now expected since #796 has gone in and wanted to note that here.

**Comment by jaclyn-taroni** [comment]
@kgaonkar6 can you update this branch please? I think you are in a better position to (correctly) resolve these merge conflicts than I am, thanks! Requesting myself for review!

**Comment by kgaonkar6** [comment]
Ah yes, I'll fix these!

**Review by jaclyn-taroni — APPROVED** [review]
Looks great!

**Pull request merged**
