### PR TITLE
Generate V23 figures

### LINKED ISSUE #1674: Revision: V23 figure panels
After #1672 is completed, we'll want to run `figures/generate-figures.sh` through and handle any updated panels. At that point we can assess what figures definitely need to be re-compiled.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #1674 

This PR re-generates figure panels at `V23`. At this time, all panels are regenerated except `snv-callers` and `tmb-compare` panels for Figure S2 (because SQLite db's are still being regenerated). But, no diffs are expected in those figures either way. We can still circle back and re-generate them either in this PR or a subsequent one.

There is only one code change here, replacing plot title with `Ependymoma`, as related to #1652.
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/2c27261bcfe8fe9924b59c6112487a33c89806c6/figures/scripts/fig5_figS6-immune-deconv-panels.R#L259-L261

Again, I've made a spreadsheet cataloging all visible diffs, comparing these new PDFs to `master`: https://docs.google.com/spreadsheets/d/1Y3moe-xnLJ_o4Jhb-klcGeq-f6aPr28VzBUiWF_oD-8/edit?usp=sharing

Based on this, the following figures will need to be recompiled (I'm noting this in #1676 also). The relevant panels and/or figure aspect that necessitate the recompilation are in parentheses.

- Figure 1 (B)
- Figure 2 (all panels except maybe LGG, but let's say all panels)
- Figure 3 (A-D)
- Figure 4 (G and H)
- Figure 5 (legend for panel A, and _maybe_ the heatmap in B but it really does seem ok to me)
- Figure S3 (A, C-D)
- Figure S5 (B-C; note there are no diffs in this PR, but these panels are different from V22 versions since we highlight TERTp now)
- Figure S6 (EPN panel _title_ only; this involves only a quick text edit in Illustrator, no new panels)

### CODE REVIEW

**Review by jaclyn-taroni — APPROVED** [review]
I went through all the panels and agree with what's in the sheet 👍🏻 

Noting a few issues I identified while stepping through the panels themselves:

* Need to reorder the embryonal oncoprint legend to match the oncoprint: medulloblastoma, other embryonal tumor, ATRT (requires a code change I believe)
* Remove (outdated?) figure 5 from the wrong spot `figures/pdfs/fig5/panels/figure5.pdf`
* Compiled S5 is in the wrong spot `figures/pdfs/supp/figs5/panels/figureS5.pdf` -> `figures/pdfs/supp/figs5/figureS5.pdf`

You can accomplish these here or track them and do them later. Up to you.

**Comment by sjspielman** [comment]
- The extra `figure<S>5.pdf` files were removed in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1677/commits/6a6ad53181a0f008732e487239da7ab930f2a9ff
- Embryonal oncoprint legend re-ordered to match plot in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1677/commits/7a95473c8554c0d149cf63cc0f9d679741f79849

**Comment by sjspielman** [comment]
No changes in this PR run through CI, so we can merge before checks are complete.

**Comment by sjspielman** [comment]
Noting for #1652 that I have confirmed here that there are no more "Ependymal tumor" phrasings in figure panels.

**Pull request merged**
