### PR TITLE
PBTA histologies v21: PR2 Update GNG, GNT and SEGA sample integrated_diagnosis

### PR DESCRIPTION
**Pull request by kgaonkar6**
🚨 Merge after #1156 🚨

#### What scientific question is your analysis addressing?
Ganglioma (GNG) and Glial-neuronal tumors (GNT) integrated_diagnosis was not updated so the `harmonized_diagnosis` as well as cancer_groups were not being categorized accurately.

#### What was your approach?
**GNG and GNT integrated_diagnosis update**
- updated the code that compiles LGAT,GNG and GNT molecular_subtypes to add the corresponding integrated_diagnosis, broad_histology and short_histology
- removed pathology_free_text_diagnosis based subtyping in [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-pathology/results/glialneuronal_tumor_subtypes.tsv)

**Additional clean up of cancer_group terms:**
- cancer_groups which currently have "/" will be updated to space so that while using the term for plots the "/" does not denote the subfolder.
- And cancer_group with ";" will be updated "-"

#### What GitHub issue does your pull request address?
#1052 

#### Which areas should receive a particularly close look?
The short_histology for pathology_diagnosis== "Glial-neuronal tumor NOS" in the base histology file is "Glial-neuronal tumor NOS" so for the GNT files subtyped I've added the short_histology as "Glial-neuronal tumor NOS". 
If we need to change the short_histology for Glial-neuronal tumor NOS to "GNT"  we will need to rerun generating the base histology and rerunning the modules since some modules like (tsne retain the metadata as well) 

#### Is there anything that you want to discuss further?
It seems to me that GNT and GNG were the only updates to the "molecular_subtype" that needed to be propogated to "integrated_diagnosis" after v19. Am I missing any other updates?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
tables

#### What is your summary of the results?
Distribution of Ganglioglioma, SEGA and Glial-neuronal tumor NOS integrated_diagnosis :

-- | broad_histology | short_histology | integrated_diagnosis | Freq
 -- | -- | -- | -- | --
1 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, BRAF V600E | 25
2 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, BRAF V600E, CDKN2A/B | 2
3 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, FGFR | 2
4 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, H3 | 2
5 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, IDH | 4
6 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, KIAA1549-BRAF | 10
7 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, MYB/MYBL1 | 2
8 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, NF1-germline | 2
9 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, NF1-somatic, BRAF V600E | 1
10 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, other MAPK | 7
11 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, other MAPK, IDH | 2
12 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, RTK | 6
13 | Low-grade astrocytic tumor | Ganglioglioma | Ganglioglioma, wildtype | 28
14 | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, BRAF V600E | 2
15 | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, KIAA1549-BRAF | 4
16 | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, other MAPK | 2
17 | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, other MAPK, FGFR | 2
18 | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, RTK | 2
19 | Low-grade astrocytic tumor | LGAT | Subependymal Giant Cell Astrocytoma, RTK | 2
20 | Low-grade astrocytic tumor | LGAT | Subependymal Giant Cell Astrocytoma, wildtype | 22

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
>If we need to change the short_histology for Glial-neuronal tumor NOS to "GNT" we will need to rerun generating the base histology and rerunning the modules since some modules like (tsne retain the metadata as well)

We should update to `GNT` to be consistent, but the tsne module uses `broad_histology` and I think many plots had been converted over to `broad_histology`..

**Review by jharenza — CHANGES_REQUESTED** [review]
Hi @kgaonkar6 - sorry for more change requests, but in looking over some of these cancergroups, I think we should change the below:

- Dysplasia Gliosis-Glial-neuronal tumor NOS (7316-2856) --> remove this from cancer group (this sample per `pathology_free_text_diagnosis` is really a dysplasia/gliosis) 

Otherwise, just check on whether making `short_histology` == GNT needs other modules rerun - not sure it will.

**Comment by kgaonkar6** [comment]
> Hi @kgaonkar6 - sorry for more change requests, but in looking over some of these cancergroups, I think we should change the below:
> 
> * Dysplasia Gliosis-Glial-neuronal tumor NOS (7316-2856) --> remove this from cancer group (this sample per `pathology_free_text_diagnosis` is really a dysplasia/gliosis)
> 
> Otherwise, just check on whether making `short_histology` == GNT needs other modules rerun - not sure it will.

I think only tsne will need a rerun, I see that the output files in tsne have the base metadata added to it. 
Example : In this umap result, 7316-334 is already assigned the short_histology==Gliosis-Glial-neuronal tumor NOS because we gather the broad/short histology in base histologies file [here](https://github.com/d3b-center/D3b-codes/blob/e0afb6185db549899f9eced5929abbb7e1841ecd/OpenPBTA_v19_release_QC/QC_histology_20210126.Rmd#L305-L328)

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/transcriptomic-dimension-reduction/results/kallisto_stranded_none_umap_scores_aligned.tsv

**Review by jharenza — CHANGES_REQUESTED** [review]
Thanks for this update.

I think a few `pathology_free_text_diagnosis` were missed in the molecular subtype integrate code:
per this [issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/996#issue-856325010), we should have Desmoplastic infantile astrocytoma and ganglioglioma,  Diffuse leptomeningeal glioneuronal tumor, and Rosette-forming glioneuronal tumor as part of the final `harmonized_diagnosis` for those relevant samples, but I don't see them. I think it stems from removing `glialnueronal_recode_file`. 

On top of that, it looks like either we have more free text terms of some may have been missed for desmoplastic infantile. Could you make the following updates:

In:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0f5a7263af2b02f80c6949f9d33730fe006eaab2/analyses/molecular-subtyping-LGAT/lgat-subset/lgat_subtyping_path_dx_strings.json#L9-L11

line 10, change to and add:
```
"desmoplastic infantile",
"desmoplastic ganglioma",
```

and

In: 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0f5a7263af2b02f80c6949f9d33730fe006eaab2/analyses/molecular-subtyping-pathology/pathology-harmonized-diagnosis-glialneuronal-tumors.Rmd#L95-L101

update line 101 to:    
```
mutate(harmonized_diagnosis = "Desmoplastic infantile astrocytoma and ganglioglioma") 
```

**Comment by kgaonkar6** [comment]
Thanks for the review @jharenza! I added the following to `recode_path_free_text` terms in LGAT https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1150/commits/72d870cbf01ace65da788d2931311c31a05623e4

```
"desmoplastic infantile",
"desmoplastic ganglioma"
```
The change is adds 7316-502 is added as GNT. 

I had removed  code that updates path_free_text_dx based subtyping from  `glialnueronal_recode_file` in this PR because we are now adding GNT to the molecular_subtyping_LGAT int_dx [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/72d870cbf01ace65da788d2931311c31a05623e4/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L227-L249 ) 

For reference I did update the code that adds `glialnueronal_recode_file` path_free_text_dx based subtyping https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1150/commits/00e0f9e07f2709e7a6d1f8629e3335bafe3ddd52 and we see that the molecular_subtypes are replaced to NA ( except for the change in 7316-502 which is the result of adding new terms to  recode_path_free_text.

Just wanted to confirm that removing the code that adds `glialnueronal_recode_file` is what is expected? If yes, I can remove the code to generate and add updates from glialnueronal_recode_file. Thanks!

**Comment by kgaonkar6** [comment]
After discussing with @jharenza on slack, I've updated the code to do the following:

- Carry over Glial neuronal tumor (GNT) subtypes to `compiled_molecular_subtypes.tsv` 
- Add integrated diagnosis if GNT samples are molecularly subtyped by  using `harmonized_diagnosis, <subtype>` as per  path_free_text_dx rules
pathology_diagnosis | subtyping module | pathology_free_text_diagnosis | broad_histology | short_histology | integrated_diagnosis | harmonized_diagnosis 
-- | -- | -- | -- | -- | -- | -- 
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | contains "desmoplastic infantile astrocytoma" | Neuronal and mixed neuronal-glial tumor | GNT | Desmoplastic infantile astrocytoma, <subtype> | Desmoplastic infantile astrocytoma 
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | diffuse leptomeningeal glioneuronal tumor | Neuronal and mixed neuronal-glial tumor | GNT | Diffuse leptomeningeal glioneuronal tumor, <subtype> | Diffuse leptomeningeal glioneuronal tumor
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | contains "glioneuronal" | Neuronal and mixed neuronal-glial tumor | GNT | Glial-neuronal tumor NOS, <subtype> | Glial-neuronal tumor NOS
Low-grade glioma/astrocytoma (WHO grade I/II) | NA, remove from LGAT module | rosette forming glioneuronal tumor | Neuronal and mixed neuronal-glial tumor | GNT | Rosette-forming glioneuronal tumor, <subtype> | Rosette-forming glioneuronal tumor
- Retained harmonized diagnosis terms subtyped as per  pathology_free_text_diagnosis `glialnueronal_recode_file` as above

**Review by jharenza — CHANGES_REQUESTED** [review]
Looks like the changes from `glialneuronal_tumor_subtypes.tsv` are not carried over to `compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` (eg broad hist) and `7316-502` was missed in `glialneuronal_tumor_subtypes.tsv`, but in `compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` but `integrated_diagnosis` is `GNT, RTK ` instead of `Desmoplastic infantile astrocytoma and ganglioglioma, RTK`

**Comment by kgaonkar6** [comment]
Thank for pointing that out @jharenza !

It seems 7316-502 has path_free_text_dx == "desmoplastic infantile ganglioglioma / astrocytoma, who grade 1 " which was not being captured in with the code in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1150/commits/c680153f7dd97f44894dc2a7f9b64b62cda02c40 because it was only using "desmoplastic infantile astrocytoma" from the recode_path_free_text terms.

I've updated the code to search for all three terms  now so 7316-502 is added to 
```
       "desmoplastic infantile",
        "desmoplastic infantile ganglioglioma",
        "desmoplastic infantile astrocytoma"
```
Now 7316-502 has the broad_histology and integrated_diagnosis as "Neuronal and mixed neuronal-glial tumor" and "Desmoplastic infantile astrocytoma and ganglioglioma, RTK" respectively.

The path_free_text_dx with "desmoplastic" are the following:
```
clinical %>% filter(pathology_diagnosis=="Low-grade glioma/astrocytoma (WHO grade I/II)", grepl("desmoplastic",pathology_free_text_diagnosis)) %>% select(pathology_free_text_diagnosis) %>% unique()
# A tibble: 3 × 1
  pathology_free_text_diagnosis                                                      
  <chr>                                                                              
1 desmoplastic infantile ganglioglioma / astrocytoma, who grade 1                    
2 dig/a desmoplastic infantile astrocytoma / ganglioglioma (who grade 1)             
3 recurrent/persistent desmoplastic infantile astrocytoma/ganglioglioma (who grade 1)
```

**Comment by jharenza** [comment]
I thought it would have been captured with "desmoplastic infantile" but I guess not? Thanks for updating! I'll review again this afternoon.

**Review by jharenza — DISMISSED** [review]
Hi @kgaonkar6 - it looks like `glialneuronal_tumor_subtypes.tsv` and `compiled_molecular_subtypes_with_clinical_pathology_feedback_and_report_info.tsv` are up to date, but the `pbta-histologies.tsv` file is not capturing these changes yet. Can you rerun that?

**Comment by kgaonkar6** [comment]
Sorry about that, I assumed that the values are being carried over correctly since there was no code update in molecular-subtype-integrate. 

I had missed adding tumor_descriptor to `glialneuronal_tumor_subtypes.tsv` so the samples were not getting matched correctly in molecular-subtype-integrate. 

I think now it's carried over to pbta-histologies.tsv :

  | Kids_First_Biospecimen_ID | sample_id | molecular_subtype | cancer_group | harmonized_diagnosis
-- | -- | -- | -- | -- | --
1 | BS_060QB7XB | 7316-2208 | GNT, KIAA1549-BRAF | Diffuse leptomeningeal glioneuronal tumor | Diffuse leptomeningeal glioneuronal tumor,  KIAA1549-BRAF
2 | BS_1KYGSMA7 | 7316-2208 | GNT, KIAA1549-BRAF | Diffuse leptomeningeal glioneuronal tumor | Diffuse leptomeningeal glioneuronal tumor,  KIAA1549-BRAF
3 | BS_2SG8JNMB | 7316-1109 | GNT, other MAPK, FGFR | Rosette-forming glioneuronal tumor | Rosette-forming glioneuronal tumor,  other MAPK, FGFR
4 | BS_3C4YAMKJ | 7316-2204 | GNT, KIAA1549-BRAF | Glial-neuronal tumor NOS | Glial-neuronal tumor NOS,  KIAA1549-BRAF
5 | BS_9X9E86DY | 7316-3629 | GNT, other MAPK | Glial-neuronal tumor NOS | Glial-neuronal tumor NOS,  other MAPK
6 | BS_D8N31T39 | 7316-502 | GNT, RTK | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, RTK
7 | BS_E94QRJDW | 7316-3629 | GNT, other MAPK | Glial-neuronal tumor NOS | Glial-neuronal tumor NOS,  other MAPK
8 | BS_EXGBH3TD | 7316-681 | GNT, BRAF V600E | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, BRAF V600E
9 | BS_NYVVN7SD | 7316-1890 | GNT, RTK | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, RTK
10 | BS_QAG1RDXN | 7316-1890 | GNT, RTK | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, RTK
11 | BS_R94EDP5H | 7316-502 | GNT, RTK | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, RTK
12 | BS_WVS02TZK | 7316-1109 | GNT, other MAPK, FGFR | Rosette-forming glioneuronal tumor | Rosette-forming glioneuronal tumor,  other MAPK, FGFR
13 | BS_X9EGD530 | 7316-2204 | GNT, KIAA1549-BRAF | Glial-neuronal tumor NOS | Glial-neuronal tumor NOS,  KIAA1549-BRAF
14 | BS_XH5JP8DB | 7316-681 | GNT, BRAF V600E | Desmoplastic infantile astrocytoma and ganglioglioma | Desmoplastic infantile astrocytoma and ganglioglioma, BRAF V600E

**Review by jharenza — APPROVED** [review]
Ok - I think we're in business :)

**Pull request merged**
