### PR TITLE
Add guess_max to prevent readr errors

### LINKED ISSUE #682: histology file changes from v12 -> v13
#### What data file(s) does this issue pertain to?
The `pbta-histologies.tsv` file used by most analyses apparently was changed via *line-reordering* from v12 -> v13 data release such that the `molecular_subtyping` column now is by default read as `NA`. This has to do with the `guess_max` functionality of `readr::read_tsv` which default only reads first 1000 rows to guess type.

In data v12, the first non-NA is line 33.
In data >=v13, the first non-NA is always on line 2000 or higher.

All scripts reading this file now give parsing warning messages when working with data release >= v12:

```
## Column read as CHARACTER - good!
> readr::read_tsv("pbta-histologies-v12.tsv")
Parsed with column specification:
cols(
  .default = col_character(),
  OS_days = col_double(),
  age_last_update_days = col_double(),
  normal_fraction = col_double(),
  tumor_fraction = col_double(),
  tumor_ploidy = col_double()
)
See spec(...) for full column specifications.
# A tibble: 2,877 x 33
   Kids_First_Bios… glioma_brain_re… sample_id aliquot_id Kids_First_Part…
   <chr>            <chr>            <chr>     <chr>      <chr>           
 1 BS_007JTNB8      NA               7316-2558 655073     PT_1MW98VR1     
 2 BS_00QJE3E5      NA               7316-2753 612693     PT_ZMKMKCFQ     
 3 BS_00TRPEQX      mixed            7316-2660 577175     PT_MDWPRDBT     
 4 BS_00ZND930      NA               7316-897  478834     PT_Q90R6M3E     
 5 BS_014EVM2D      hemispheric      7316-362  570113     PT_S21ZTKPS     
 6 BS_01DQH017      NA               7316-3299 654356     PT_CYVVA9AB     
 7 BS_01Y5F4PN      other            7316-663  728420     PT_QK4XB83F     
 8 BS_02NZT8CE      hemispheric      7316-1745 549619     PT_2BJF83GQ     
 9 BS_02W5H7K5      NA               7316-1649 711399     PT_J06X17XH     
10 BS_02YBZSBY      hemispheric      7316-2189 711151     PT_VTM2STE3     
# … with 2,867 more rows, and 28 more variables: experimental_strategy <chr>,
#   sample_type <chr>, composition <chr>, tumor_descriptor <chr>,
#   primary_site <chr>, reported_gender <chr>, race <chr>, ethnicity <chr>,
#   age_at_diagnosis_days <chr>, disease_type_old <chr>,
#   disease_type_new <chr>, short_histology <chr>, broad_histology <chr>,
#   broad_composition <chr>, Notes <chr>, germline_sex_estimate <chr>,
#   RNA_library <chr>, OS_days <dbl>, OS_status <chr>, cohort <chr>,
#   age_last_update_days <dbl>, seq_center <chr>, normal_fraction <dbl>,
#   tumor_fraction <dbl>, tumor_ploidy <dbl>, parent_aliquot_id <chr>,
#   cancer_predispositions <chr>, molecular_subtype <chr>

## Column read as LOGICAL - not good :(
> readr::read_tsv("pbta-histologies-v13.tsv")
Parsed with column specification:
cols(
  .default = col_character(),
  OS_days = col_double(),
  age_last_update_days = col_double(),
  normal_fraction = col_double(),
  tumor_fraction = col_double(),
  tumor_ploidy = col_double(),
  molecular_subtype = col_logical()
)
See spec(...) for full column specifications.
Warning: 221 parsing failures.
 row               col           expected actual                       file
2606 molecular_subtype 1/0/T/F/TRUE/FALSE Group3 'pbta-histologies-v13.tsv'
2607 molecular_subtype 1/0/T/F/TRUE/FALSE Group4 'pbta-histologies-v13.tsv'
2608 molecular_subtype 1/0/T/F/TRUE/FALSE Group3 'pbta-histologies-v13.tsv'
2609 molecular_subtype 1/0/T/F/TRUE/FALSE Group3 'pbta-histologies-v13.tsv'
2610 molecular_subtype 1/0/T/F/TRUE/FALSE Group3 'pbta-histologies-v13.tsv'
.... ................. .................. ...... ..........................
See problems(...) for more details.
```

This can be addressed in a few ways:

1) Add the argument `guess_max = 2500` or some rather large number is given to `readr::read_tsv` so that this column is parsed correctly
2) Explicitly define this column as character, as in: 
`readr::read_tsv(file, col_types = readr::cols(molecular_subtype = readr::col_character()))`

### PR DESCRIPTION
**Pull request by jashapiro**
#### What scientific question is your analysis addressing?

Fix errors/warnings related to readr not correctly guessing histology file data types as described in #682

#### What was your approach?

Search for all usage of `readr::read_tsv()` (explicitly scoped and not) that read in the `pbta-histologies.tsv` file and add `guess_max = 10000` where an alternative method was not already present.

#### What GitHub issue does your pull request address?

Closes #682

#### Which areas should receive a particularly close look?

Did I miss any?

#### What is your summary of the results?

Should not change any results, but should reduce warnings.
[histology file changes from v12 -> v13](https://app.gitkraken.com/glo/card/efdb8558f9e04e3a847c55c4e8ba42cd)

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
I am noticing a lot of changes to Rmd files that are not accompanied with changes to HTML files, which means they will be out of sync.

**Comment by jashapiro** [comment]
> I am noticing a lot of changes to Rmd files that are not accompanied with changes to HTML files, which means they will be out of sync.

That is a very good point. I will go back and rerun all changed notebooks before this merges. Downgrading to draft.

**Comment by sjspielman** [comment]
I'm finding quite a few missed ones - going to do a round of sleuthing, and then we'll check again if they are all cleaned. Notably, this argument is also a good choice `col_types = readr::cols(molecular_subtype = readr::col_character())` and I feel fine letting it through as alternative to `guess_max`. I don't see a super compelling (aka non-OCD-oriented) reason to make *all* `read_tsv` use the same flavor argument. Any disagreement there?

**Comment by jaclyn-taroni** [comment]
guess_max() is arguably a bit more future-proof albeit less _principled_.

**Comment by sjspielman** [comment]
Note, I think this file still needs to be re-knitted: `analyses/molecular-subtyping-HGG/01-HGG-molecular-subtyping-defining-lesions.Rmd`.

**Comment by jaclyn-taroni** [comment]
We are going to focus on #571 this week - I think anything that is not integral to getting that set of figures will probably need to wait a little bit. Particularly because CI takes a considerable amount of time to run + something looked amiss in HGG possibly and therefore I will need to look carefully at that before we merge this.

**Comment by jaclyn-taroni** [comment]
@jashapiro do you think this is worth revisiting (not necessarily by you!) this sprint or should we close this?

**Comment by sjspielman** [comment]
I'll clean up these conflicts now!

**Comment by sjspielman** [comment]
Note, I am letting through any situations where something like `col_types = cols(molecular_subtype = col_character())` is used rather than `guess_max=10000`. Any strong objections @jashapiro @jaclyn-taroni ? Would you prefer to see these changed to `guess_max=10000`? On the flip side, I am changing the `read.delim()`'s I find reading in the histologies file to use `readr` instead. Apparently this is My Line.

**Pull request merged**
