### PR TITLE
add v18 release

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
V18 data release

#### What was your approach?
- changes:
  - Add RNA independent specimen lists from [#795](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/795) and [#797](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/797)
  - Update DNA independent specimen lists per comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691526896)
  - Add LGAT fusion summary file from [#808](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/808) and [#830](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/830)
  - Update fusion files per comment [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691529675)
- Add kinase domain and reciprocal information to pbta-fusion-putative-oncogenic.tsv per [#812](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/812) and [#816](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/816) and [#821](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/821)
  - Add 8 rRNA-depleted, total stranded RNA-Seq for tumors which previously had polyA sequencing performed: BS_FXJY0MNH, BS_KABQQA0T, BS_D7XRFE0R, BS_SHJA4MR0, BS_HE0WJRW6, BS_8QB4S4VA, BS_FN07P04C, BS_SB12W1XT per [#749](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/749)
  - Update pbta-histologies.tsv:
    - Add new RNA samples above
    - Pull latest clinical data
    - Add extent of tumor resection per [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issue-688364970)
    - Rerun molecular subtyping modules to date

#### What GitHub issue does your pull request address?
#750 

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
no

#### What types of results are included (e.g., table, figure)?
NA

#### What is your summary of the results?
NA

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [x] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?
- [x] Was download-data.sh tested and did it complete without error?

### CODE REVIEW

**Comment by jharenza** [comment]
note: will need to update release notes to include both histologies files. cc @kgaonkar6

**Comment by jharenza** [comment]
Just leaving a note - all files except for `pbta-histologies.tsv` are updated on S3 and download works. We have added `pbta-histologies-base.tsv` per [this issue](url) and are currently in the stage of rerunning molecular subtyping for the new histologies file.

**Comment by jharenza** [comment]
Wanted to docunent on this PR some intermediate QC [here](https://github.com/d3b-center/D3b-codes/tree/master/OpenPBTA_v18_release_QC):
- QC on the RNA-Seq merge files
- `pbta-histologies-base.tsv` construction to include:
  - BIXU-generated fields from v17
  - Updated metadata for new RNA-Seq samples
  - `broad_histology` and `short_histology` mapping from `pathology_diagnosis` and `pathology_free_text_diagnosis`
  - `CNS_region` logic

**Comment by kgaonkar6** [comment]
@jharenza @jaclyn-taroni  @cansavvy the following output files generated as part of base subtyping run are uploaded in s3.  Details of other modules re-run are described in #861 

| Module |  Reason |Brief Description | output
|--------|----------|--------|------
| [`collapse-rnaseq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/collapse-rnaseq) | adding 8 samples #749 and used in subtyping  | Collapses RSEM FPKM matrices such that gene symbols are de-duplicated. | `results/pbta-gene-expression-rsem-fpkm-collapsed.polya.rds` (included in data download; too large for tracking via GitHub) <br> `results/pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` (included in data download; too large for tracking via GitHub)
| [`fusion_filtering`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) | adding 8 samples #749 and used in subtyping  | Standardizes, filters, and prioritizes fusion calls updated in #808 and #830 | `results/pbta-fusion-putative-oncogenic.tsv`(included in data download) <br> `results/pbta-fusion-recurrent-fusion-byhistology.tsv` (included in data download) <br> `results/pbta-fusion-recurrent-fusion-bysample.tsv` (included in data download) <br> `results/fusion_summary_lgat_foi.tsv` (included in data download)
| [`fusion-summary`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion-summary)| adding 8 samples #749 and used in subtyping  | Generate summary tables from fusion files updated in  #812 and #816 and #821 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691529675) | `results/fusion_summary_embryonal_foi.tsv` (included in data download) <br> `results/fusion_summary_ependymoma_foi.tsv` (included in data download) <br> `results/fusion_summary_ewings_foi.tsv`
| [`independent-samples`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/independent-samples) | adding 8 samples #749 and used in subtyping  | Generates independent specimen lists for WGS/WXS samples updated in  #795 and #797 and [comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/750#issuecomment-691526896)| `results/independent-specimens.wgs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary.tsv` (included in data download) <br> `results/independent-specimens.wgswxs.primary-plus.tsv` (included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-stranded.tsv`(included in data download) <br> `results/independent-specimens.rnaseq.primary-plus-polya.tsv` (included in data download)
| [`molecular-subtyping-integrate`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-integrate) |  to add subtyping to base histology | Add molecular subtype information to base histology | `results/pbta-histologies.tsv`(included in data download)

**Review by jaclyn-taroni — APPROVED** [review]
I think we're ready to merge!

**Pull request merged**
