### PR TITLE
Rerun the count-contributions module with real stats

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
I followed the instructions here for running this on the `AlexsLemonade/master` branch: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/count-contributions#running-the-module-manually

And have committed the real stats!

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Added a `workflow_dispatch` trigger so we have another option for running this "manually." I don't think we need to specify any inputs or anything, but obviously I have not tested this yet!

**Comment by sjspielman** [comment]
Chiming in here because I noticed this module was not added to `analyses/README.md` in #1523. It may be convenient to add in that documentation in this PR.

**Comment by jaclyn-taroni** [comment]
> Chiming in here because I noticed this module was not added to `analyses/README.md` in #1523. It may be convenient to add in that documentation in this PR.

Done!

**Review by jashapiro — APPROVED** [review]
LGTM!

**Comment by jaclyn-taroni** [comment]
I'm going to get this merged in the interest of seeing if the workflow dispatch works as currently configured.

**Pull request merged**
