### PR TITLE
V22 rerun figures for survival/tp53 telomerase

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
Rerunning survival figures for v22.

#### What was your approach?
Reran:
```
Rscript --vanilla scripts/fig4-hgg-kaplan-meier.R
Rscript --vanilla scripts/fig4-hgg-subtype-forest-plot.R
Rscript --vanilla scripts/fig5-forest-plot.R
Rscript --vanilla scripts/fig4-tp53-telomerase-panels.R
```

#### What GitHub issue does your pull request address?
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1368

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
Reran all 4 scripts in full.
Updated the x-axis code to show error bars for the tp53 telomerase FP.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by sjspielman** [comment]
Thanks for opening this fresh PR! Thinking about it a bit more, I think it would be very appropriate to also use this PR to update the other figures in `scripts/fig4-tp53-telomerase-panels.R`. The tp53 rerun has been merged (#1461), and we are just waiting on checks to merge in #1475 (this is running through CI now quickly with a cache, so will get merged soon I suspect!). 

Doing this will involve:
+ Re-running that script once both those PRs are merged
+ Updating groups here as needed: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0c2b89ed5a8a3f9adb1963c4b54d924c9af0dfb1/figures/scripts/fig4-tp53-telomerase-panels.R#L251-L263
+ Making sure the seed set here still ensures that hypermutator points are all visible with the updated cancer groups. (when setting this originally I tried a bunch of seeds to make sure the hypermutator points aren't stacked on top of each other):
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/0c2b89ed5a8a3f9adb1963c4b54d924c9af0dfb1/figures/scripts/fig4-tp53-telomerase-panels.R#L126-L127
+ Checking in to make sure we've got all the right hypermutators

**Comment by sjspielman** [comment]
Noting this PR also closes #1417.

@jharenza can you also address #1373 for the forest plot here? I had missed that previously. The plot `km_hgg_panel.pdf` already has wording updated, but we need to fix `forest_hgg_subtypes.pdf`.  Thanks!

**Comment by jharenza** [comment]
@sjspielman this should be ready now. Note: I used the same cancer groups as in interaction plots (minus "Other"
) to 1) be consistent with something else and 2) to include the "other embryonal tumor", which contains the new NBL metastasis hypermutator. Seed still works fine.

**Review by sjspielman — COMMENTED** [review]
I do think we need to change the seed here (line 349 in `fig4-tp53-telomerase-panels.R`), since some of the hypermutator points are on top of each other. I tested out some seeds, and `12` works nicely to avoid point overlap! Otherwise, this looks good!

I don't think we'll need to add any further `useDingbats = FALSE` to any plots that don't already have it. That argument is mostly helpful for text and points, and all the jitter plots have it already in their `ggsave()`.

**Comment by jharenza** [comment]
ok @sjspielman - updated seed and reran. I was looking at mainly whether they were visible so was thinking _some_ overlap was ok.. I see what you mean now!

**Review by sjspielman — APPROVED** [review]
🚀

**Comment by sjspielman** [comment]
This code does not run through CI, so merging before checks complete.

**Pull request merged**
