### PR TITLE
Delete accidentally committed old results/reference

### PR DESCRIPTION
**Pull request by kgaonkar6**
### Purpose/implementation Section
Unfortunately certain old results and reference files got committed to the repo in fusion_filtering analysis. I'm adding this PR to remove those files.

#### What was your approach? 
git rm old files ; commit

#### What types of results are included (e.g., table, figure)?
Table

#### What is your summary of the results?
3213 PutativeDriverFusion.tsv will be used for oncoprint visualization.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
umm.. is this the correct way to add another PR when I already have an existing PR for changes to dockerfile for a different issue ? https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/312 

Please let me know if I should close this PR and resubmit one when the dockerfile changes get committed.

Thanks,
Krutika

**Comment by cgreene** [comment]
@kgaonkar6 : It looks like this branch started from the branch from #312 instead of the upstream (this repository) master. It meant that until #312 was merged, those changes would also show up here. I took a look and approved #312, so things here should work well - thanks for checking!

**Comment by jaclyn-taroni** [comment]
Just to confirm -- this is what should be on the master branch, correct @kgaonkar6 : https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering/results

**Comment by kgaonkar6** [comment]
> https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering/results

yup, correct! The PutativeDriverFusion.tsv is also the same file in the v11 release.

**Comment by jaclyn-taroni** [comment]
Great thank you

**Pull request merged**
